INSERT INTO venues (id, name, address, city, country, capacity, surface, image) 
VALUES (694, 'Olympiastadion Berlin', 'Olympischer Platz 3', 'Berlin', 'Germany', 77116, 'grass', 'https://media.api-sports.io/football/venues/694.png'), 
      (700, 'Allianz Arena', 'Werner-Heisenberg-Allee 25', 'München', 'Germany', 75000, 'grass', 'https://media.api-sports.io/football/venues/700.png'), 
      (714, 'Merkur Spiel-Arena', 'Arena-Str. 1', 'Düsseldorf', 'Germany', 54600, 'grass', 'https://media.api-sports.io/football/venues/714.png'), 
      (12717, 'Europa-Park Stadion', 'Achim-Stocker-Straße 1', 'Freiburg im Breisgau', 'Germany', 34700, 'grass', 'https://media.api-sports.io/football/venues/12717.png'), 
      (752, 'VOLKSWAGEN ARENA', 'In den Allerwiesen 1', 'Wolfsburg', 'Germany', 30000, 'grass', 'https://media.api-sports.io/football/venues/752.png'), 
      (755, 'wohninvest WESERSTADION', 'Franz-Böhmert-Straße 1c', 'Bremen', 'Germany', 42358, 'grass', 'https://media.api-sports.io/football/venues/755.png'), 
      (703, 'Stadion im BORUSSIA-PARK', 'Hennes-Weisweiler-Allee 1', 'Mönchengladbach', 'Germany', 54057, 'grass', 'https://media.api-sports.io/football/venues/703.png'), 
      (11899, 'MEWA ARENA', 'Eugen-Salomon-Straße 1', 'Mainz', 'Germany', 34034, 'grass', 'https://media.api-sports.io/football/venues/11899.png'), 
      (702, 'Signal-Iduna-Park', 'Strobelalle 50', 'Dortmund', 'Germany', 81365, 'grass', 'https://media.api-sports.io/football/venues/702.png'), 
      (18858, 'Heinz von Heiden-Arena', 'Robert-Enke-Str. 3', 'Hannover', 'Germany', 49000, 'grass', 'https://media.api-sports.io/football/venues/18858.png'), 
      (724, 'PreZero Arena', 'Dietmar-Hopp-Straße 1', 'Sinsheim', 'Germany', 30164, 'grass', 'https://media.api-sports.io/football/venues/724.png'), 
      (699, 'BayArena', 'Bismarckstr. 122-124', 'Leverkusen', 'Germany', 30210, 'grass', 'https://media.api-sports.io/football/venues/699.png'), 
      (10491, 'Deutsche Bank Park', 'Mörfelder Landstr. 362', 'Frankfurt am Main', 'Germany', 52300, 'grass', 'https://media.api-sports.io/football/venues/10491.png'), 
      (698, 'WWK Arena', 'Bürgermeister Ulrich-Straße 90', 'Augsburg', 'Germany', 30662, 'grass', 'https://media.api-sports.io/football/venues/698.png'), 
      (713, 'Max-Morlock-Stadion', 'Max-Morlock-Platz 1', 'Nürnberg', 'Germany', 50000, 'grass', 'https://media.api-sports.io/football/venues/713.png'), 
      (750, 'Mercedes-Benz-Arena', 'Mercedesstrasse 87', 'Stuttgart', 'Germany', 60469, 'grass', 'https://media.api-sports.io/football/venues/750.png'), 
      (738, 'Red Bull Arena', 'Am Sportforum 3', 'Leipzig', 'Germany', 47069, 'grass', 'https://media.api-sports.io/football/venues/738.png'), 
      (741, 'VELTINS-Arena', 'Arenaring 1', 'Gelsenkirchen', 'Germany', 62271, 'grass', 'https://media.api-sports.io/football/venues/741.png'), 
      (720, 'Volksparkstadion', 'Sylvester Allee 7', 'Hamburg', 'Germany', 57030, 'grass', 'https://media.api-sports.io/football/venues/720.png'), 
      (751, 'Vonovia Ruhrstadion', 'Castropher Straße 145', 'Bochum', 'Germany', 30748, 'grass', 'https://media.api-sports.io/football/venues/751.png'), 
      (10490, 'Jahnstadion Regensburg', 'Franz-Josef-Strauß-Allee, Oberisling', 'Regensburg', 'Germany', 15224, 'grass', 'https://media.api-sports.io/football/venues/10490.png'), 
      (718, 'Sportpark Ronhof Thomas Sommer', 'Laubenweg 60', 'Fürth', 'Germany', 18000, 'grass', 'https://media.api-sports.io/football/venues/718.png'), 
      (733, 'MDCC-Arena', 'Friedrich-Ebert-Straße 69', 'Magdeburg', 'Germany', 27250, 'grass', 'https://media.api-sports.io/football/venues/733.png'), 
      (723, 'Voith-Arena', 'Schloßhaustraße 160', 'Heidenheim an der Brenz', 'Germany', 15000, 'grass', 'https://media.api-sports.io/football/venues/723.png'), 
      (705, 'Merck-Stadion am Böllenfalltor', 'Nieder-Ramstädter Straße 170', 'Darmstadt', 'Germany', 17468, 'grass', 'https://media.api-sports.io/football/venues/705.png'), 
      (748, 'Stadion An der Alten Försterei', 'Hämmerlingstraße 80-88, Köpenick', 'Berlin', 'Germany', 22467, 'grass', 'https://media.api-sports.io/football/venues/748.png'), 
      (707, 'Rudolf-Harbig-Stadion', 'Lennéstraße 12', 'Dresden', 'Germany', 32066, 'grass', 'https://media.api-sports.io/football/venues/707.png'), 
      (726, 'Audi-Sportpark', 'Am Sportpark 1', 'Ingolstadt', 'Germany', 15729, 'grass', 'https://media.api-sports.io/football/venues/726.png'), 
      (18622, 'Home Deluxe Arena', 'Paderborner Str. 89', 'Paderborn', 'Germany', 15306, 'grass', 'https://media.api-sports.io/football/venues/18622.png'), 
      (745, 'Millerntor-Stadion', 'Auf dem Heiligengeistfeld', 'Hamburg', 'Germany', 29546, 'grass', 'https://media.api-sports.io/football/venues/745.png'), 
      (730, 'Schauinsland-Reisen-Arena', 'Margaretenstr. 5-7', 'Duisburg', 'Germany', 31514, 'grass', 'https://media.api-sports.io/football/venues/730.png'), 
      (697, 'SchücoArena', 'Melanchthonstr. 31a', 'Bielefeld', 'Germany', 27300, 'grass', 'https://media.api-sports.io/football/venues/697.png'), 
      (740, 'BWT-Stadion am Hardtwald', 'Jahnstr. 1', 'Sandhausen', 'Germany', 14508, 'grass', 'https://media.api-sports.io/football/venues/740.png'), 
      (712, 'Erzgebirgsstadion', 'Lößnitzer Str. 95', 'Aue', 'Germany', 16080, 'grass', 'https://media.api-sports.io/football/venues/712.png'), 
      (725, 'Holstein-Stadion', 'Westring 501', 'Kiel', 'Germany', 15034, 'grass', 'https://media.api-sports.io/football/venues/725.png'), 
      (731, 'RheinEnergieStadion', 'Aachener Str. 999', 'Köln', 'Germany', 50076, 'grass', 'https://media.api-sports.io/football/venues/731.png'), 
      (708, 'Eintracht-Stadion', 'Hamburger Straße 210', 'Braunschweig', 'Germany', 23325, 'grass', 'https://media.api-sports.io/football/venues/708.png'), 
      (728, 'Fritz-Walter-Stadion', 'Fritz-Walter-Straße 1', 'Kaiserslautern', 'Germany', 49780, 'grass', 'https://media.api-sports.io/football/venues/728.png'), 
      (757, 'flyeralarm-Arena', 'Mittlerer Dallenbergweg 49', 'Würzburg', 'Germany', 13080, 'grass', 'https://media.api-sports.io/football/venues/757.png'), 
      (11900, 'BBBank Wildpark', 'Adenauerring 17', 'Karlsruhe', 'Germany', 29699, 'grass', 'https://media.api-sports.io/football/venues/11900.png'), 
      (695, 'Städtisches Stadion an der Grünwalder Straße', 'Grünwalder Straße 4', 'München', 'Germany', 21272, 'grass', 'https://media.api-sports.io/football/venues/695.png'), 
      (737, 'Preußen-Stadion', 'Am Berg Fidel 51', 'Münster', 'Germany', 18050, 'grass', 'https://media.api-sports.io/football/venues/737.png'), 
      (749, 'Alpenbauer Sportpark', 'Am Sportpark 9', 'Unterhaching', 'Germany', 15053, 'grass', 'https://media.api-sports.io/football/venues/749.png'), 
      (758, 'GGZ Arena', 'Eckersbach', 'Zwickau', 'Germany', 10134, 'grass', 'https://media.api-sports.io/football/venues/758.png'), 
      (12457, 'Leuna Chemie Stadion', 'Kantstraße 2', 'Saale', 'Germany', 15065, 'grass', 'https://media.api-sports.io/football/venues/12457.png'), 
      (10640, 'WIRmachenDRUCK Arena', 'Fautenhau 1', 'Aspach', 'Germany', 10001, 'grass', 'https://media.api-sports.io/football/venues/10640.png'), 
      (734, 'Hänsch-Arena', 'Lathener Str. 15, Neustadt', 'Meppen', 'Germany', 16500, 'grass', 'https://media.api-sports.io/football/venues/734.png'), 
      (753, 'BRITA-Arena', 'Berliner Straße 9', 'Wiesbaden', 'Germany', 13144, 'grass', 'https://media.api-sports.io/football/venues/753.png'), 
      (711, 'Stadion der Freundschaft', 'Am Eliaspark 1', 'Cottbus', 'Germany', 22528, 'grass', 'https://media.api-sports.io/football/venues/711.png'), 
      (722, 'Ostseestadion', 'Kopernikusstraße 17', 'Rostock', 'Germany', 29000, 'grass', 'https://media.api-sports.io/football/venues/722.png'), 
      (18859, 'Grotenburg-Stadion', 'Tiergartenstraße 165, Bockum', 'Krefeld', 'Germany', 34500, 'grass', 'https://media.api-sports.io/football/venues/18859.png'), 
      (11901, 'Stadion am Lotter Kreuz', 'Jahnstraße 8', 'Lotte', 'Germany', 10059, 'grass', 'https://media.api-sports.io/football/venues/11901.png'), 
      (735, 'Bremer Brücke', 'Scharnhorststraße 50, Schinkel', 'Osnabrück', 'Germany', 16667, 'grass', 'https://media.api-sports.io/football/venues/735.png'), 
      (704, 'Ernst-Abbe-Sportfeld', 'Oberaue 3', 'Jena', 'Germany', 15500, 'grass', 'https://media.api-sports.io/football/venues/704.png'), 
      (715, 'Südstadion', 'Vorgebirgsglacisweg 2, Zollstock', 'Köln', 'Germany', 14944, 'grass', 'https://media.api-sports.io/football/venues/715.png'), 
      (10639, 'OSTALB ARENA', 'Stadionweg 3', 'Aalen', 'Germany', 14500, 'grass', 'https://media.api-sports.io/football/venues/10639.png'), 
      (2701, 'Stadion Chemnitz', 'Gellertstr.', 'Chemnitz', 'Germany', 18712, 'grass', 'https://media.api-sports.io/football/venues/2701.png'), 
      (10655, 'Sportplatz Grubenstraße', 'Grubenstr. 65', 'Erfurt', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/10655.png'), 
      (2727, 'Weserstadion Platz 11', 'Franz-Böhmert-Straße 1c', 'Bremen', 'Germany', 5500, 'grass', 'https://media.api-sports.io/football/venues/2727.png'), 
      (2728, 'Stadion am Bruchweg', 'Dr.-Martin-Luther-King-Weg 20', 'Mainz', 'Germany', 13508, 'grass', 'https://media.api-sports.io/football/venues/2728.png'), 
      (2708, 'PSD Bank Arena', 'Am Erlenbruch 1', 'Frankfurt am Main', 'Germany', 12542, 'grass', 'https://media.api-sports.io/football/venues/2708.png'), 
      (18782, 'MS Technologie Arena', 'Im Friedengrund 1/3', 'Villingen-Schwenningen', 'Germany', 16000, 'grass', 'https://media.api-sports.io/football/venues/18782.png'), 
      (1727, 'Sportpark Höhenberg', 'Merheimer Heide', 'Köln', 'Germany', 10001, 'grass', 'https://media.api-sports.io/football/venues/1727.png'), 
      (2704, 'Stadion Essen', 'Hafenstraße 97a, Bergeborbeck', 'Essen', 'Germany', 20650, 'grass', 'https://media.api-sports.io/football/venues/2704.png'), 
      (2713, 'Karl-Liebknecht-Stadion', 'Karl-Liebknecht-Straße 90, Babelsberg', 'Potsdam', 'Germany', 10787, 'grass', 'https://media.api-sports.io/football/venues/2713.png'), 
      (706, 'Kehdinger Stadion', 'Am Sportplatz', 'Drochtersen', 'Germany', 8300, 'grass', 'https://media.api-sports.io/football/venues/706.png'), 
      (2712, 'EBRA-Stadion im Wiesental', 'Brühlstr. 17', 'Ravensburg', 'Germany', 7000, 'grass', 'https://media.api-sports.io/football/venues/2712.png'), 
      (10508, 'Dietmar-Scholze-Stadion an der Lohmühle', 'Bei der Lohmühle 13', 'Lübeck', 'Germany', 17869, 'grass', 'https://media.api-sports.io/football/venues/10508.png'), 
      (2716, 'Dietmar-Hopp-Sportpark', 'Schwetzinger Str. 92', 'Walldorf', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/2716.png'), 
      (2707, 'Moselstadion', 'Zeughausstr.', 'Trier', 'Germany', 10805, 'grass', 'https://media.api-sports.io/football/venues/2707.png'), 
      (2710, 'Sparda-Bank-Hessen-Stadion', 'Bieberer Straße 282', 'Offenbach', 'Germany', 20500, 'grass', 'https://media.api-sports.io/football/venues/2710.png'), 
      (2718, 'Lohrheidestadion', 'Lohrheidestraße 81-83, Wattenscheid', 'Bochum', 'Germany', 16233, 'grass', 'https://media.api-sports.io/football/venues/2718.png'), 
      (2706, 'Stadion am Panzenberg', 'Landwehrstr. 6', 'Bremen', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/2706.png'), 
      (2702, 'Edmund-Plambeck-Stadion', 'Ochsenzoller Str. 58', 'Norderstedt', 'Germany', 5068, 'grass', 'https://media.api-sports.io/football/venues/2702.png'), 
      (2709, 'Joyetech-Arena', 'An der Ammerke 3', 'Barsinghausen', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/2709.png'), 
      (2717, 'Stadion am Neding', 'Speyerstr. 2', 'Hauenstein', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/2717.png'), 
      (2715, 'Waldstadion Homburg', 'Kurt-Conrad-Str. 8', 'Homburg', 'Germany', 21813, 'grass', 'https://media.api-sports.io/football/venues/2715.png'), 
      (742, 'Willy-Sachs-Stadion', 'Anderl Kupfer Platz 2', 'Schweinfurt', 'Germany', 15060, 'grass', 'https://media.api-sports.io/football/venues/742.png'), 
      (701, 'Friedrich-Ludwig-Jahn-Sportpark', 'Cantianstrasse 24', 'Berlin', 'Germany', 19708, 'grass', 'https://media.api-sports.io/football/venues/701.png'), 
      (2700, 'Sportpark Nord', 'Kölnstraße 250', 'Bonn', 'Germany', 10164, 'grass', 'https://media.api-sports.io/football/venues/2700.png'), 
      (2724, 'Kleiner-Arena', 'Gleiwitzer Str. 28', 'Remchingen', 'Germany', 3800, 'grass', 'https://media.api-sports.io/football/venues/2724.png'), 
      (11930, 'Stadion Ludwigspark', 'Camphauser Straße', 'Saarbrücken', 'Germany', 35286, 'grass', 'https://media.api-sports.io/football/venues/11930.png'), 
      (18681, 'Röser-Arena Dorfmerkingen', 'Felsenstr. 4', 'Dorfmerkingen', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/18681.png'), 
      (18682, 'Morlautern Kunstrasenplatz', 'Freiherr-vom-Stein-Str. 12', 'Kaiserslautern', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18682.png'), 
      (2720, 'Kunstrasenplatz Talwiese Rielasingen K', 'Dr.-Fritz-Guth-Str.', 'Rielasingen-Worblingen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/2720.png'), 
      (2703, 'Friedensstadion', 'Spiegelsbergenweg 79', 'Halberstadt', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/2703.png'), 
      (12719, 'LTS-Sportanlage 1', 'Honholdstr. 1', 'Bremerhaven', 'Germany', 7000, 'grass', 'https://media.api-sports.io/football/venues/12719.png'), 
      (2721, 'Neetze Jahn-Stadion A-Platz', 'Bleckeder Landstr. 21', 'Neetze', 'Germany', 1079, 'grass', 'https://media.api-sports.io/football/venues/2721.png'), 
      (2722, 'Ernst-Wagener-Stadion', 'Matthias-Claudius-Str., Eichede', 'Steinburg', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/2722.png'), 
      (1726, 'Pulverwaldstadion', 'Jahnstr. 6', 'Erndtebrück', 'Germany', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/1726.png'), 
      (1880, 'Stadion Oberwerth', 'Jupp-Gauchel-Str. 10', 'Koblenz', 'Germany', 9500, 'grass', 'https://media.api-sports.io/football/venues/1880.png'), 
      (754, 'Manfred-Werner-Stadion', 'Bredstedter Str. 2, Weiche', 'Flensburg', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/754.png'), 
      (1791, 'Häcker Wiehenstadion', 'Auf der Drift 36, Schwenningdorf', 'Rödinghausen', 'Germany', 2489, 'grass', 'https://media.api-sports.io/football/venues/1791.png'), 
      (1878, 'Alfred-Kunze-Sportpark', 'Am Sportpark 2', 'Leipzig', 'Germany', 4999, 'grass', 'https://media.api-sports.io/football/venues/1878.png'), 
      (747, 'Donaustadion', 'Stadionstr. 17', 'Ulm', 'Germany', 19500, 'grass', 'https://media.api-sports.io/football/venues/747.png'), 
      (1910, 'Kunstrasenplatz SPA Hastedt', 'Hastedter Osterdeich', 'Bremen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/1910.png'), 
      (732, 'Stadion am Hölzchen', 'Arneburger Straße 83', 'Stendal', 'Germany', 6500, 'grass', 'https://media.api-sports.io/football/venues/732.png'), 
      (1762, '53acht Arena', 'Wischenstr. 46', 'Edewecht', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/1762.png'), 
      (1828, 'SIBRE Sportzentrum Haarwasen Haiger', 'Sportplatz Str. 14', 'Haiger', 'Germany', 4204, 'grass', 'https://media.api-sports.io/football/venues/1828.png'), 
      (739, 'Stadion Niederrhein', 'Lindnerstraße 2-6', 'Oberhausen', 'Germany', 21318, 'grass', 'https://media.api-sports.io/football/venues/739.png'), 
      (18860, 'KRAMSKI-Arena', 'Adolf-Richter-Str. 3', 'Pforzheim', 'Germany', 8438, 'grass', 'https://media.api-sports.io/football/venues/18860.png'), 
      (710, 'URSAPHARM-Arena an der Kaiserlinde', 'Lindenstraße 7', 'Spiesen-Elversberg', 'Germany', 9970, 'grass', 'https://media.api-sports.io/football/venues/710.png'), 
      (746, 'Hans-Weber Stadion', 'Im Hölzel 2', 'Rheinau', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/746.png'), 
      (1792, 'Sportplatz Dassendorf', 'Bornweg / Wendelweg', 'Dassendorf', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/1792.png'), 
      (756, 'EWR-Arena', 'Alzeyer Straße 131', 'Worms', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/756.png'), 
      (3254, 'Neuer Tivoli', 'Krefelder Straße', 'Aachen', 'Germany', 32960, 'grass', 'https://media.api-sports.io/football/venues/3254.png'), 
      (3255, 'Stadion an der Düsternortstraße', 'Düsternortstr.', 'Delmenhorst', 'Germany', 7000, 'grass', 'https://media.api-sports.io/football/venues/3255.png'), 
      (3256, 'Parkstadion', 'Friedrich-Ebert-Allee / Am Parkstadion', 'Baunatal', 'Germany', 12000, 'grass', 'https://media.api-sports.io/football/venues/3256.png'), 
      (3257, 'Liqui-Moly-Stadion', 'Am Sportplatz 8', 'Eichstätt', 'Germany', 2830, 'grass', 'https://media.api-sports.io/football/venues/3257.png'), 
      (11937, 'Marko Mock Arena', 'Vinnenweg 100', 'Bremen', 'Germany', 5100, 'grass', 'https://media.api-sports.io/football/venues/11937.png'), 
      (3259, 'Salmtalstadion', 'Salmaue', 'Salmtal', 'Germany', 10300, 'grass', 'https://media.api-sports.io/football/venues/3259.png'), 
      (3262, 'Albert-Kuntz-Sportpark', 'Parkallee 8b', 'Nordhausen', 'Germany', 8088, 'grass', 'https://media.api-sports.io/football/venues/3262.png'), 
      (3263, 'Carl-Benz-Stadion', 'Theodor-Heuss-Anlage 25', 'Mannheim', 'Germany', 25667, 'grass', 'https://media.api-sports.io/football/venues/3263.png'), 
      (5699, 'Jugendleistungszentrum Kurtekotten', 'Knochenbergsweg', 'Leverkusen', 'Germany', 1400, 'grass', 'https://media.api-sports.io/football/venues/5699.png'), 
      (5700, 'Fußballpark BVB Hohenbuschei', 'Addi Preißler Allee 9, Brackel', 'Dortmund', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/5700.png'), 
      (5706, 'Sportanlage Gesamtschule Ückendorf', 'Bochumer Straße 190, Ückendorf', 'Gelsenkirchen', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/5706.png'), 
      (6430, 'Jahnstadion', 'Jahnstr. 25', 'Rosenheim', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/6430.png'), 
      (11969, 'NGN-Arena', 'Schulstr. 6', 'Aubstadt', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/11969.png'), 
      (6432, 'Rosenaustadion', 'Stadionstraße 21', 'Augsburg', 'Germany', 28000, 'grass', 'https://media.api-sports.io/football/venues/6432.png'), 
      (6433, 'Hans-Walter-Wild-Stadion', 'Am Sportpark 3', 'Bayreuth', 'Germany', 21500, 'grass', 'https://media.api-sports.io/football/venues/6433.png'), 
      (6434, 'SMR-Arena', 'Jahnstraße 7', 'Buchbach', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/6434.png'), 
      (6435, 'Stadion am See', 'Am See', 'Garching bei München', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/6435.png'), 
      (6436, 'Sportanlage Burgfarrnbach Platz 1', 'Tulpenweg 60', 'Fürth', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/6436.png'), 
      (6437, 'Sportpark Heimstetten', 'Am Sportpark 2, Heimstetten', 'Kirchheim bei München', 'Germany', 3100, 'grass', 'https://media.api-sports.io/football/venues/6437.png'), 
      (6438, 'Vöhlin-Stadion', 'Dietenheimer Str. 60 / Gottfried-Hart-Str.', 'Illertissen', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/6438.png'), 
      (6439, 'Memminger Arena', 'Bodenseestraße 44', 'Memmingen', 'Germany', 7000, 'grass', 'https://media.api-sports.io/football/venues/6439.png'), 
      (11970, 'Max-Morlock-Platz im Sportpark Valznerweiher', 'Valznerweiherstr. 200', 'Nürnberg', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/11970.png'), 
      (6441, 'Georg-Weber-Stadion', 'Donauwörther Str. 43 / Fasanenweg', 'Rain', 'Germany', 3400, 'grass', 'https://media.api-sports.io/football/venues/6441.png'), 
      (6442, 'Sportanlage Reuthinger Weg', 'Reuthinger Weg 8', 'Passau', 'Germany', 2760, 'grass', 'https://media.api-sports.io/football/venues/6442.png'), 
      (6443, 'Stadion am Schönbusch', 'Kleine Schönbuschallee 92', 'Aschaffenburg', 'Germany', 9000, 'grass', 'https://media.api-sports.io/football/venues/6443.png'), 
      (6444, 'Wacker-Arena', 'Franz-Alexander-Str. 7', 'Burghausen', 'Germany', 10200, 'grass', 'https://media.api-sports.io/football/venues/6444.png'), 
      (6445, 'Adolf-Jäger-Kampfbahn', 'Griegstraße 62', 'Hamburg', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/6445.png'), 
      (10641, 'HSC-Stadion Constantinstraße', 'Constantinstr. 86', 'Hannover-List', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/10641.png'), 
      (6447, 'Wolfgang-Meyer-Sportanlage', 'Hagenbeckstr. 124', 'Hamburg', 'Germany', 2018, 'grass', 'https://media.api-sports.io/football/venues/6447.png'), 
      (12696, '96 Das Stadion', 'Clausewitzstr. 4', 'Hannover', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/12696.png'), 
      (6449, 'Wilhelm-Langrehr-Stadion', 'Hannoversche Straße 90-92', 'Garbsen', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/6449.png'), 
      (6450, 'Stadion an der Meldorfer Straße', 'Meldorfer Str. 30', 'Heide', 'Germany', 11000, 'grass', 'https://media.api-sports.io/football/venues/6450.png'), 
      (6451, 'Citti Fussball Park - Projensdorf (Platz A)', 'Steenbeker Weg 150-152', 'Kiel', 'Germany', 1200, 'grass', 'https://media.api-sports.io/football/venues/6451.png'), 
      (6452, 'Sportplatz Waldsportstätten', 'Dickeler Str.', 'Rehden', 'Germany', 4350, 'grass', 'https://media.api-sports.io/football/venues/6452.png'), 
      (6453, 'Marschwegstadion', 'Marschweg 25', 'Oldenburg', 'Germany', 15552, 'grass', 'https://media.api-sports.io/football/venues/6453.png'), 
      (6454, 'AOK Stadion', 'Allerpark 2', 'Wolfsburg', 'Germany', 5200, 'grass', 'https://media.api-sports.io/football/venues/6454.png'), 
      (6455, 'Arena zur Vogtlandweide', 'Ziegeleiweg 20', 'Auerbach', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/6455.png'), 
      (6456, 'Poststadion', 'Lehrterstr. 59, Moabit', 'Berlin', 'Germany', 12000, 'grass', 'https://media.api-sports.io/football/venues/6456.png'), 
      (6457, 'Wesenitzsportpark', 'Clara-Zetkin-Str. 6', 'Bischofswerda', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/6457.png'), 
      (11973, 'Olympiapark-Amateurstadion', 'Friedrich-Friesen-Allee', 'Berlin', 'Germany', 5400, 'grass', 'https://media.api-sports.io/football/venues/11973.png'), 
      (6459, 'HOWOGE-Arena Hans Zoschke', 'Normannenstraße 26-28, Lichtenberg', 'Berlin', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/6459.png'), 
      (6460, 'Bruno-Plache-Stadion', 'Connewitzer Straße 21, Probstheida', 'Leipzig', 'Germany', 10900, 'grass', 'https://media.api-sports.io/football/venues/6460.png'), 
      (6461, 'Stadion Vogelgesang', 'Birkenweg 45', 'Rathenow', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/6461.png'), 
      (6462, 'Bonava-Arena im Friesenstadion', 'Hangelsberger Chaussee 1', 'Fürstenwalde', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/6462.png'), 
      (6463, 'bluechip-Arena', 'Ernst-Grube-Straße', 'Meuselwitz', 'Germany', 5260, 'grass', 'https://media.api-sports.io/football/venues/6463.png'), 
      (6464, 'Kaiserstuhlstadion', 'Stadenweg 13', 'Bahlingen', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/6464.png'), 
      (6465, 'BIZERBA-Arena', 'Tübinger Str. 71', 'Balingen', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/6465.png'), 
      (6466, 'Städtisches Stadion im Sportzentrum am Prischoß', 'Prischoßstr. 57', 'Alzenau', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/6466.png'), 
      (6467, 'Waldstadion Gießen', 'Zum Waldsportplatz 10', 'Gießen', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/6467.png'), 
      (12274, 'Dreisamstadion', 'Schwarzwaldstraße 193', 'Freiburg im Breisgau', 'Germany', 25000, 'grass', 'https://media.api-sports.io/football/venues/12274.png'), 
      (6469, 'Dietmar-Hopp-Stadion', 'Silbergasse 45, Hoffenheim', 'Sinsheim', 'Germany', 6350, 'grass', 'https://media.api-sports.io/football/venues/6469.png'), 
      (6470, 'Sportpark Husterhöhe', 'Georgia Avenue 1', 'Pirmasens', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/6470.png'), 
      (6471, 'BELKAW-Arena', 'Paffrather Str. 133', 'Bergisch Gladbach', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/6471.png'), 
      (6472, 'Stadion Rote Erde', 'Strobelallee 50', 'Dortmund', 'Germany', 25000, 'grass', 'https://media.api-sports.io/football/venues/6472.png'), 
      (6473, 'Grenzlandstadion', 'Seminarstr. 20, Rheydt', 'Mönchengladbach', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/6473.png'), 
      (6474, 'Paul-Janes-Stadion', 'Flinger Broich 87, Flingern Nord', 'Düsseldorf', 'Germany', 7150, 'grass', 'https://media.api-sports.io/football/venues/6474.png'), 
      (6475, 'PCC-Stadion', 'Rheindeichstr. 50 / Dammstraße, Homberg', 'Duisburg', 'Germany', 3260, 'grass', 'https://media.api-sports.io/football/venues/6475.png'), 
      (6476, 'Franz-Kremer-Stadion', 'Franz-Kremer-Allee 1-3', 'Köln', 'Germany', 5457, 'grass', 'https://media.api-sports.io/football/venues/6476.png'), 
      (11974, 'Liebelt-Arena', 'Wiedenbrücker Str. 83', 'Lippstadt', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/11974.png'), 
      (11975, 'Parkstadion', 'Ernst-Kuzzora-Weg 1', 'Gelsenkirchen', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/11975.png'), 
      (6479, 'Stauseekampfbahn', 'Lippspieker', 'Haltern am See', 'Germany', 1600, 'grass', 'https://media.api-sports.io/football/venues/6479.png'), 
      (6480, 'Stadion am Zoo', 'Hubertusallee 4', 'Wuppertal', 'Germany', 23067, 'grass', 'https://media.api-sports.io/football/venues/6480.png'), 
      (7175, 'Porschestadion', 'Berliner Ring 45', 'Wolfsburg', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/7175.png'), 
      (8083, 'Sportplatz Ulmenweg', 'Ulmenweg', 'Merseburg', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/8083.png'), 
      (18690, 'Sportanlage Gilching', 'Talhofstraße 13', 'Gilching', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/18690.png'), 
      (8085, 'Sportplatz Landwehrstraße', 'Landwehrstr.', 'Wasserburg am Inn', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8085.png'), 
      (8086, 'Waldstadion Aplerbeck', 'Schwerter Str. 238', 'Dortmund', 'Germany', 2120, 'grass', 'https://media.api-sports.io/football/venues/8086.png'), 
      (8087, 'Sportanlage Erlangen Paul-Gossen-Strasse', 'Paul-Gossen-Str. 58', 'Erlangen', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8087.png'), 
      (8088, 'Kräuter Mix Arena', 'Alte Untersambacher Str. 4', 'Abtswind', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8088.png'), 
      (8089, 'Rudolf-Kalweit-Stadion', 'Bischofsholer Damm 119, Bult', 'Hannover', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/8089.png'), 
      (8090, 'Haag-Park-Arena', 'Hoher Weg 86, Rheingönheim', 'Ludwigshafen am Rhein', 'Germany', 2000, null, 'https://media.api-sports.io/football/venues/8090.png'), 
      (8091, 'Werner-Seelenbinder-Sportplatz', 'Brielower Str. 7', 'Brandenburg an der Have', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8091.png'), 
      (8092, 'Nidda-Sportfeld', 'Am Sportfeld', 'Bad Vilbel', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/8092.png'), 
      (8094, 'Sportplatz Dieselstraße', 'Dieselstraße 6', 'Hamburg', 'Germany', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/8094.png'), 
      (8095, 'Sportpark Johannisau', 'Johannistr. 45', 'Fulda', 'Germany', 18000, 'grass', 'https://media.api-sports.io/football/venues/8095.png'), 
      (12468, 'Mainz Albert-Schweitzer-Strasse Kunstrasen', 'Albert-Schweitzer-Str. 19', 'Mainz', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12468.png'), 
      (8096, 'Städtisches Stadion Grüne Au', 'Oelsnitzer Straße 101', 'Hof', 'Germany', 8096, 'grass', 'https://media.api-sports.io/football/venues/8096.png'), 
      (8097, 'Volksparkstadion Mariendorf', 'Prühßstraße 90', 'Berlin', 'Germany', 9000, 'grass', 'https://media.api-sports.io/football/venues/8097.png'), 
      (8099, 'Sportpark am Möhlenkamp', 'Möhlenkamp 26', 'Bordesholm', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/8099.png'), 
      (8100, 'Friedrich-Ebert-Stadion', 'An der Pottkuhle 1', 'Hildesheim', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/8100.png'), 
      (8101, 'Sportplatz Ellernreihe', 'Ellernreihe 88', 'Hamburg', 'Germany', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/8101.png'), 
      (8103, 'BSV-Arena', 'Brunnenweg', 'Stuhr', 'Germany', 2200, 'grass', 'https://media.api-sports.io/football/venues/8103.png'), 
      (8104, 'Otto-Koch-Kampfbahn', 'Seppenser Mühlenweg 44', 'Buchholz in der Nordheide', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8104.png'), 
      (8105, 'Stadion Müllerwiese', 'Humboldtstr. 10', 'Bautzen', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8105.png'), 
      (8106, 'Ernst-Abbe-Sportfeld Platz 3', 'Oberaue 3', 'Jena', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8106.png'), 
      (8107, 'Horst-Neuhoff-Sportplatz', 'Hauptstr. 121', 'Wuppertal', 'Germany', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/8107.png'), 
      (8108, 'Sportanlage Jahnstraße', 'Jahnstraße 23-25', 'Dachau', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8108.png'), 
      (8109, 'Sportanlage Deisenhofen - Platz 1', 'Am Sportplatz 22', 'Deisenhofen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8109.png'), 
      (8112, 'Westkampfbahn', 'Papiermühle, Gürzenich', 'Düren', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8112.png'), 
      (8113, 'Sportplatz an der Staustufe', 'Mönchhofstr., Eddersheim', 'Hattersheim', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8113.png'), 
      (8114, 'Ilburg-Stadion', 'Hainicher Aue 1', 'Eilenburg', 'Germany', 5600, 'grass', 'https://media.api-sports.io/football/venues/8114.png'), 
      (8115, 'Fuchs-Park-Stadion', 'Pödeldorfer Straße 180', 'Bamberg', 'Germany', 5200, 'grass', 'https://media.api-sports.io/football/venues/8115.png'), 
      (8116, 'Rasenplatz Eintracht- Platz', 'Nienburger Str.', 'Celle', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8116.png'), 
      (12101, 'Sportanlage Am Rosenhag', 'Melanchthonstraße 52 D', 'Berlin', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12101.png'), 
      (8117, 'Gustav-Wegner-Stadion', 'Am Rhumekanal 3', 'Northeim', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8117.png'), 
      (10643, 'Kunstrasenplatz 2 Stadtallendorf', 'Herrenwaldstr.', 'Stadtallendorf', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10643.png'), 
      (8119, 'Sportanlage Langenau', 'Langenaustraße 17', 'Erlangen', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/8119.png'), 
      (12469, 'Friedrich-Ludwig-Jahn-Sportpark Nebenplatz 1', 'Cantianstrasse 24', 'Berlin', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12469.png'), 
      (8120, 'Gigaset Arena', 'Am Hünting 19', 'Bocholt', 'Germany', 4999, 'grass', 'https://media.api-sports.io/football/venues/8120.png'), 
      (8121, 'Kunstrasenplatz FSV Duisburg', 'Warbruckstr.', 'Duisburg', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8121.png'), 
      (8122, 'Freie Turner-Stadion', 'Herzogin-Elisabeth-Str. 78', 'Braunschweig', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/8122.png'), 
      (8123, 'Stadion am Wasserturm', 'Am Wasserturm, Engers', 'Neuwied', 'Germany', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/8123.png'), 
      (8124, 'Kunstrasenplatz Kurt-Bornhoff-Sportpark', 'Hans-Schaeven-Weg', 'Frechen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8124.png'), 
      (8125, 'SPA Bürgerpark Platz 2', 'Adolf-Hoff-Weg', 'Bremerhaven', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8125.png'), 
      (8126, 'GWG-Stadion A-Platz', 'Winkeler Str. 2', 'Gifhorn', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/8126.png'), 
      (8127, 'RasenPlatz Ginsheim-Gustavsburg', 'Vorm Anthaupt', 'Ginsheim-Gustavsburg', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8127.png'), 
      (8129, 'Sportplatz am Wildpark', 'Kapellenstr. 40, Gonsenheim', 'Mainz', 'Germany', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/8129.png'), 
      (10334, null, 'Unterhofer Straße 11', 'Großbardorf', 'Germany', 4300, 'grass', 'https://media.api-sports.io/football/venues/10334.png'), 
      (8133, 'Stadion SV Göppingen', 'Hohenstaufenstr. 116', 'Göppingen', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8133.png'), 
      (8134, 'Sportplatz Hagen I', 'Blumenstr.', 'Hagen im Bremischen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8134.png'), 
      (8135, 'Sportplatz an der Kastanienallee', 'Kastanienallee 75, Kesselstadt', 'Hanau', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8135.png'), 
      (8136, 'Maierhofer Bau - Stadion', 'Prof.-Reger-Str. 23, Hankofen', 'Leiblfing', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8136.png'), 
      (8137, 'Stadion am Hessenhaus', 'Hitchin Strasse 32, Büdesheim', 'Bingen', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8137.png'), 
      (8138, 'Waldstadion', 'Burgsteg 14', 'Heeslingen', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/8138.png'), 
      (8139, 'BSA Hemelingen - Platz 1', 'Hemelinger Heerstr. 112', 'Bremen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8139.png'), 
      (8140, 'Stadion im Sportzentrum Hennef', 'Fritz-Jacobi-Straße 24', 'Hennef', 'Germany', 2258, 'grass', 'https://media.api-sports.io/football/venues/8140.png'), 
      (8141, 'ProWin Stadion am Wallenborn', 'Landstuhlstr.', 'Eppelborn', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8141.png'), 
      (8142, 'Ernst-Reuter-Sportfeld', 'Onkel-Tom-Str. 40, Zehlendorf', 'Berlin', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/8142.png'), 
      (8143, 'Hahn Air Sportpark', 'Am Bürgeracker 24', 'Dreieich', 'Germany', 2621, 'grass', 'https://media.api-sports.io/football/venues/8143.png'), 
      (8144, 'Auestadion', 'Am Sportzentrum', 'Kassel', 'Germany', 18737, 'grass', 'https://media.api-sports.io/football/venues/8144.png'), 
      (8146, 'Sportplatz Hoffeldstrasse', 'Hoffeldstrasse 106', 'Hilden', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8146.png'), 
      (8147, 'Sportplatz Ilshofen', 'Haller Strasse 1', 'Ilshofen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8147.png'), 
      (8148, 'BZA Süd-Ost', 'Geisenfelder Straße 1, Ringsee', 'Ingolstadt', 'Germany', 11418, 'grass', 'https://media.api-sports.io/football/venues/8148.png'), 
      (8150, 'Hans-Mohr-Sportplatz', 'Erich-Kästner-Weg 100', 'Kiel', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/8150.png'), 
      (8151, 'Hafenstadion', 'Ziegeleiweg 2a', 'Torgau', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/8151.png'), 
      (8152, 'Professor Erich Greipl Stadion', 'Leuchtenbergstr. 25', 'Ismaning', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8152.png'), 
      (8154, 'Sportpark am Kaulbachweg', 'Kaulbachweg 31', 'Regensburg', 'Germany', 4500, 'grass', 'https://media.api-sports.io/football/venues/8154.png'), 
      (18691, 'Herkules Arena', 'Breitenbacher Straße, Kaan-Marienborn', 'Siegen', 'Germany', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/18691.png'), 
      (8156, 'Sportpark Rote Teufel Platz 7', 'Werner-Liebrich-Str. 1', 'Mehlingen', 'Germany', 600, 'grass', 'https://media.api-sports.io/football/venues/8156.png'), 
      (8159, 'Ostfriesland-Stadion', 'Sielweg 10', 'Emden', 'Germany', 7200, 'grass', 'https://media.api-sports.io/football/venues/8159.png'), 
      (8160, 'Stadion Alte Mühle', 'Laufener Str. 25', 'Kirchanschöring', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8160.png'), 
      (8162, 'ABT-Arena', 'Kieswerkstr. 10', 'Durach', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8162.png'), 
      (8163, 'KrayArena', 'Buderusstr. 20a, Kray', 'Essen', 'Germany', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/8163.png'), 
      (8164, 'Werner-Seelenbinder-Stadion', 'Straße des Friedens 42', 'Luckenwalde', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8164.png'), 
      (8165, 'Lupo Stadio', 'Hubertusstr. 10', 'Wolfsburg', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/8165.png'), 
      (8167, 'Sportpark Martinroda', 'Schulstr.', 'Martinroda', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8167.png'), 
      (8168, 'Stadion An der Oststraße', 'Oststrasse', 'Meinerzhagen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8168.png'), 
      (10666, 'Kunstrasenplatz Rheinstadion', 'Kapellenstr. 1', 'Monheim am Rhein', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10666.png'), 
      (8170, 'Sportpark Pichterich', 'Pichterichstraße 71', 'Neckarsulm', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/8170.png'), 
      (8171, 'Parkstadion', 'Pappelallee 17', 'Neustrelitz', 'Germany', 7000, 'grass', 'https://media.api-sports.io/football/venues/8171.png'), 
      (18784, 'Wolfgang Krohn Arena', 'Sachsenweg 91', 'Hamburg', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18784.png'), 
      (8173, 'Waldsportplatz Oberachern', 'Waldstraße 3, Oberachern', 'Achern', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/8173.png'), 
      (18645, 'Orafol-Arena', 'André-Pican-Str. 41a', 'Oranienburg', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/18645.png'), 
      (8176, 'Sportplatz Blomkamp', 'Blomkamp 32', 'Hamburg', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8176.png'), 
      (8177, 'Sportpark Breite Bruch', 'Neuenbekener Str. 25', 'Paderborn', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/8177.png'), 
      (8178, 'Jonny Rehbein Sportplatz', 'Brucknerstr. 24', 'Hamburg', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/8178.png'), 
      (12470, 'Waldsportplatz', 'Waldstraße 24b', 'Petershagen/Eggersdorf', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12470.png'), 
      (8180, 'Sportplatz an der Travemünder Allee', 'Travemünder Allee', 'Lübeck', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8180.png'), 
      (18646, 'Stadion an der Reichertshausener Straße', 'Reichertshauser Str. 4', 'Pipinsried', 'Germany', 7000, 'grass', 'https://media.api-sports.io/football/venues/18646.png'), 
      (8182, 'Sternquell-Arena', 'Nach dem Stadion 25', 'Plauen', 'Germany', 12000, 'grass', 'https://media.api-sports.io/football/venues/8182.png'), 
      (8185, 'Sportplatz an der Gistlstraße', 'Gistlstraße 2', 'Pullach im Isartal', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8185.png'), 
      (8187, 'Sportplatz Roland', 'Vorhelmer Straße 441, Roland', 'Beckum', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8187.png'), 
      (8188, 'Wersestadion', 'August-Kirchner-Straße 14', 'Ahlen', 'Germany', 12500, 'grass', 'https://media.api-sports.io/football/venues/8188.png'), 
      (2726, 'Hermann-Neuberger-Stadion', 'Stadionstrasse', 'Völklingen', 'Germany', 12000, 'grass', 'https://media.api-sports.io/football/venues/2726.png'), 
      (8191, 'MEGA-Stadion Sandstraße', 'Sandstr. 77a, Baumberg', 'Monheim am Rhein', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/8191.png'), 
      (8192, 'Bezirkssportanlage Im Holtkamp', 'Im Holtkamp 80 / Westerwaldstraße 43, Hamborn', 'Duisburg', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/8192.png'), 
      (8193, 'Wasen-Stadion', 'Talstr. 17 / Auf dem Wasen', 'Freiberg', 'Germany', 4500, 'grass', 'https://media.api-sports.io/football/venues/8193.png'), 
      (18621, 'IMS Arena', 'Siemensstr. 2', 'Velbert', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/18621.png'), 
      (8195, 'Sportanlage Schetters Busch', 'Friedhofstr. 17A', 'Essen', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/8195.png'), 
      (8196, 'Ernst-Lehner-Stadion', 'Stauffenbergstr. 19', 'Augsburg', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/8196.png'), 
      (10356, null, 'Riedstraße 59', 'Schwabmünchen', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/10356.png'), 
      (8198, 'BZA Schwachhausen', 'Konrad-Adenauer-Allee 86-88', 'Bremen', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/8198.png'), 
      (18692, 'MARena', 'Zum Sportpark 1', 'Pyrbaum', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/18692.png'), 
      (8200, 'Walter-Mundorf-Stadion', 'Am Stadion 1', 'Siegburg', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/8200.png'), 
      (12471, 'Rasenplatz Fischerstraße', 'Fischerstr. 15', 'Berlin', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12471.png'), 
      (8206, 'Sportzentrum an der Römerstraße', 'Römerstr.', 'Straelen am Niederrhein', 'Germany', 2300, 'grass', 'https://media.api-sports.io/football/venues/8206.png'), 
      (8207, 'Energie Arena', 'Wriezener Straße 30e', 'Strausberg', 'Germany', 7500, 'grass', 'https://media.api-sports.io/football/venues/8207.png'), 
      (8210, 'Robert-Schlienz-Stadion', 'Mercedesstr. 109, Bad Cannstatt', 'Stuttgart', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8210.png'), 
      (8211, 'GAZİ-Stadion auf der Waldau', 'Guts-Muths Weg 4, Waldau', 'Stuttgart', 'Germany', 11436, 'grass', 'https://media.api-sports.io/football/venues/8211.png'), 
      (8212, 'Sportzentrum Uphusen', 'Arenkamp 3, Uphusen', 'Achim', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8212.png'), 
      (8213, 'Stadion Eckener Straße', 'Eckener Straße 24', 'Flensburg', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/8213.png'), 
      (8214, 'Sportplatz Velbert Birth', 'Von-Humboldt-Str. 66', 'Velbert', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8214.png'), 
      (8215, 'Werner-Seelenbinder-Sportpark', 'Neukölln', 'Berlin', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8215.png'), 
      (8217, 'Mommsenstadion', 'Waldschulallee 34-45', 'Berlin', 'Germany', 15005, 'grass', 'https://media.api-sports.io/football/venues/8217.png'), 
      (8231, 'Stadion Hoheluft', 'Lokstedter Steindamm 87, Hoheluft', 'Hamburg', 'Germany', 5004, 'artificial turf', 'https://media.api-sports.io/football/venues/8231.png'), 
      (8221, 'JODA Sportpark', 'Am Sportplatz / Dorfstr. 1', 'Todesfelde', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/8221.png'), 
      (8222, 'Stadion an der Feuerbachstraße', 'Feuerbachstrasse 82, Bilk', 'Düsseldorf', 'Germany', 13000, 'grass', 'https://media.api-sports.io/football/venues/8222.png'), 
      (9744, null, 'Unterer Talweg 100', 'Augsburg', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/9744.png'), 
      (8226, 'Sport- und Freizeitzentrum Sandersdorf', 'Am Sportzentrum 17', 'Sandersdorf-Brehna', 'Germany', 7000, 'grass', 'https://media.api-sports.io/football/venues/8226.png'), 
      (8227, 'Sportanlage an der Isar', 'Bergstr. 4a', 'Unterföhring', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8227.png'), 
      (8229, 'Stadion an der Alexanderstraße', 'Alexanderstr. 98, Bürgerfelde', 'Oldenburg', 'Germany', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/8229.png'), 
      (8230, 'Rhein-Neckar-Stadion', 'Theodor-Heuss-Anlage 19', 'Mannheim', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/8230.png'), 
      (8232, 'Südstadion', 'Schülerstr. 36', 'Griesheim', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8232.png'), 
      (8233, 'Manfred-Zollner-Stadion', 'Huthgartenstraße 33, Vilzing', 'Cham', 'Germany', 3480, 'grass', 'https://media.api-sports.io/football/venues/8233.png'), 
      (8234, 'Stadion in den Lahnauen', 'Georg-Ohm Str., Waldgirmes', 'Lahnau', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/8234.png'), 
      (12472, 'Polygonvatro-Arena', 'Westring 260', 'Herne', 'Germany', 32000, 'grass', 'https://media.api-sports.io/football/venues/12472.png'), 
      (8237, 'Jahnstadion', 'Ostring 116', 'Rheda-Wiedenbrück', 'Germany', 2550, 'grass', 'https://media.api-sports.io/football/venues/8237.png'), 
      (8238, 'Sepp-Endres-Sportanlage', 'Mainaustraße 32, Zellerau', 'Würzburg', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/8238.png'), 
      (8631, 'Stadion an der Kreuzeiche', 'An der Kreuzeiche 4', 'Reutlingen', 'Germany', 15228, 'grass', 'https://media.api-sports.io/football/venues/8631.png'), 
      (8632, 'Stadion an der Waldstraße', 'Waldstr. 1', 'Waldalgesheim', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/8632.png'), 
      (12725, 'neu.sw Stadion', 'Badeweg 6', 'Neubrandenburg', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/12725.png'), 
      (8634, 'Leimbachstadion', 'Leimbachstr. 230', 'Siegen', 'Germany', 18716, 'grass', 'https://media.api-sports.io/football/venues/8634.png'), 
      (8635, 'Stadion Vegesack', 'Vegesascker Bahnhofsplatz', 'Bremen', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8635.png'), 
      (8636, 'Uwe-Becker-Stadion', 'Am Schießhaus 8, Pfeddersheim', 'Worms', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8636.png'), 
      (18693, 'Ernst-Abbe-Sportfeld Platz 6', 'Oberaue 3', 'Jena', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18693.png'), 
      (8638, 'Grümmi-Arena', 'Geerdtstr. 14', 'Neumünster', 'Germany', 9999, 'grass', 'https://media.api-sports.io/football/venues/8638.png'), 
      (8639, 'Jade-Stadion', 'Friedenstraße 111', 'Wilhelmshaven', 'Germany', 7500, 'grass', 'https://media.api-sports.io/football/venues/8639.png'), 
      (12473, 'Sportplatz Leistikowstraße', 'Leistikowstraße, Finkenkrug', 'Falkensee', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/12473.png'), 
      (8640, 'Karl-Heitz-Stadion', 'Badstr. 22', 'Offenburg', 'Germany', 15000, 'grass', 'https://media.api-sports.io/football/venues/8640.png'), 
      (8641, 'Sportplatz In der Au', 'In der Au', 'Roßbach', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8641.png'), 
      (8642, 'Palmberg-Stadion', 'Rudolf-Hartmann-Straße 15', 'Schönberg', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/8642.png'), 
      (8643, 'Jahnsportplatz', 'Goethestrasse', 'Wismar', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/8643.png'), 
      (8644, 'ETV-Sportzentrum Hoheluft', 'Lokstedter Steindamm 75-77, Eppendorf', 'Hamburg', 'Germany', 1200, 'artificial turf', 'https://media.api-sports.io/football/venues/8644.png'), 
      (8645, 'WECO-Arena im Sportpark Germania', 'Sportplatzweg 2, Übersetzig', 'Windeck-Dattenfeld', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/8645.png'), 
      (8646, 'Friedrich-Meyer-Stadion', null, null, 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/8646.png'), 
      (8647, 'Westpfalzstadion', 'Hofenfelsstr. 162', 'Zweibrücken', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/8647.png'), 
      (10573, 'Waldstadion', 'Kiefernweg 87', 'Wegberg-Beeck', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/10573.png'), 
      (10668, 'Ernst-Reuter-Kampfbahn', 'Luisenstraße 35', 'Mönchengladbach', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/10668.png'), 
      (10669, 'Waldstadion', 'Strangheidgesweg 100', 'Alfter', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10669.png'), 
      (10670, 'Stadion am Sportzentrum', 'Klausdorfer Str. 78e', 'Altenholz', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/10670.png'), 
      (10370, 'Saar-Blies-Stadion', 'Stadionstr., Auersmacher', 'Kleinblittersdorf', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/10370.png'), 
      (12474, 'Sportpark Concordia Wiemelhausen', 'Glücksburger Str. 25', 'Bochum', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12474.png'), 
      (10672, 'Dudenhofen Rasen', 'Iggelheimer Str. 38', 'Dudenhofen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10672.png'), 
      (11989, 'BZA Schorlemerstrasse', 'Schorlemerstr. 61, Niederkassel', 'Düsseldorf', 'Germany', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/11989.png'), 
      (10374, 'Sportplatz Bruck', 'Tennenloherstraße 68', 'Erlangen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10374.png'), 
      (12728, 'Sportpark Mittwald (Kunstrasenplatz)', 'Koloniestr. 63', 'Espelkamp', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12728.png'), 
      (10674, 'Heidewaldstadion', 'Heidewaldstraße 27', 'Gütersloh', 'Germany', 12500, 'grass', 'https://media.api-sports.io/football/venues/10674.png'), 
      (10675, 'Sportanlage Ederener Straße', 'Ederener Str. / Am Sportplatz', 'Aldenhoven', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/10675.png'), 
      (18870, 'Rasenplatz Friedberg', 'Burgfeldstr. 5a', 'Hessen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18870.png'), 
      (10677, 'Montanhydraulik-Stadion', 'Jahnstr 7.', 'Holzwickede', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/10677.png'), 
      (10679, 'Friesen-Stadion', 'Am Hasselberg 32', 'Husum', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/10679.png'), 
      (12611, 'Ligaplatz SV Friedrichsort', 'Steenbarg, Friedrichsort', 'Kiel', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/12611.png'), 
      (10384, 'Sportplatz Kölner Straße', 'Kölner Str. 368a', 'Krefeld', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/10384.png'), 
      (18648, 'Gerd-Müller-Stadion', 'Anton-Jaumann-Industriepark 6', 'Nördlingen', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/18648.png'), 
      (10391, 'Rasenplatz Freizeitpark', 'Münstereifeler Str.', 'Rheinbach', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10391.png'), 
      (10680, 'Sportplatz Am Böttinger', 'Friedrich-Ebert-Str. 301', 'Velbert', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10680.png'), 
      (10681, 'Sportpark Sandweg', 'Sandweg 3, Geismar', 'Göttingen', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/10681.png'), 
      (10682, 'Uhlenkrugstadion', 'Am Uhlenkrug 40, Stadtwald', 'Essen', 'Germany', 9950, 'grass', 'https://media.api-sports.io/football/venues/10682.png'), 
      (12702, 'Mainz Golden Eagles Stadium', 'Auf der langen Lein 2', 'Mainz-Mombach', 'Germany', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/12702.png'), 
      (10683, 'Baumhof Arena', 'Eickerstr. 23 / Im Baumhof 20', 'Sprockhövel', 'Germany', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/10683.png'), 
      (10396, 'Sportplatz Lüntenbeck', 'Bahnstr. 202c', 'Wuppertal', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10396.png'), 
      (11991, 'Meeschestadion', 'Lessingstr.', 'Wolfenbüttel', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/11991.png'), 
      (12475, 'Lhoist Sportpark', 'Silberberger Weg 3', 'Wülfrath', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/12475.png'), 
      (10685, 'Stadion am Hombruchsfeld', 'Am Hombruchsfeld 71, Hombruch', 'Dortmund', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10685.png'), 
      (10686, 'Stadtisches Stadion im Heinepark', 'Kleiner Damm', 'Rudolstadt', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/10686.png'), 
      (10687, 'Sportzentrum Friesdorf', 'Margaretenstr., Friesdorf', 'Bonn', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10687.png'), 
      (10688, 'Sportanlage Faulbacher Straße', 'Faulbacher Str.', 'Hadamar', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/10688.png'), 
      (10689, 'Stadion am Freibad', 'Am Freibad 14', 'Dinslaken', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/10689.png'), 
      (10690, 'Sportplatz Lank', 'Nierster Str. 90', 'Meerbusch', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/10690.png'), 
      (10691, 'Willy-Lemkens-Sportpark', 'Balberger Str.', 'Sonsbeck', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10691.png'), 
      (10692, 'Christian-Rötzel-Kampfbahn', 'Lobbericher Str., 41334 Nettetal', 'Nettetal', 'Germany', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/10692.png'), 
      (18649, 'Heimersheim Kunstrasen', 'Im Bülland', 'Bad Neuenahr-Ahrweiler', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18649.png'), 
      (12729, 'Sportplatz Ammerthal', 'Pürschläger-Weg 2', 'Ammerthal', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12729.png'), 
      (12076, 'Xaver-Bertsch-Sportpark', 'Am Stadion 3', 'Ansbach', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/12076.png'), 
      (12612, 'Sportplatz Hans-Wagner-Weg', 'Teutoburger Str. 176', 'Oberhausen', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12612.png'), 
      (10693, 'Waldstadion', 'Schwetzinger Str. 92', 'Walldorf', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/10693.png'), 
      (10694, 'Kunstrasenplatz Glesch', 'Jahn Str. 10', 'Bergheim', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10694.png'), 
      (10695, 'Heinz-Dettmer-Stadion', 'Steinfelder Str.', 'Lohne', 'Germany', 7150, 'grass', 'https://media.api-sports.io/football/venues/10695.png'), 
      (10696, 'Kampfbahn Hameln', 'Tönebönweg', 'Hameln', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10696.png'), 
      (18650, 'RAFI-Stadion', 'Jahnstraße 17', 'Berg', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/18650.png'), 
      (10697, 'Hasestadion', 'Hastruper Weg 1', 'Bersenbrück', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/10697.png'), 
      (18651, 'Bevern Platz A', 'Calhorner Str. 20', 'Oldenburg', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18651.png'), 
      (10699, 'Städtisches Stadion', 'Sportzentrum 11', 'Bruchsal', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/10699.png'), 
      (12477, 'Kunstrasenplatz An der Windmühle', 'An der Windmühle 24', 'Essen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12477.png'), 
      (12478, 'Sportplatz Bövinghausen', 'Provinzialstr. 273', 'Dortmund', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12478.png'), 
      (10701, 'Sportplatz Gramkowweg', 'Gramkowweg', 'Hamburg', 'Germany', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/10701.png'), 
      (10702, 'SV Deutz Kunstrasenplatz', 'Dr. Simons Str. 10', 'Köln', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10702.png'), 
      (18871, 'Stadion Babelsberg', 'Friedhofsweg', 'Dillingen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18871.png'), 
      (10705, 'OBI-Arena', 'Bentlager Weg 40', 'Rheine', 'Germany', 7500, 'grass', 'https://media.api-sports.io/football/venues/10705.png'), 
      (18699, 'FC Eldagsen A-Platz', 'Hindenburgallee 7', 'Springe', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18699.png'), 
      (10706, 'Emmelshausen Kunstrasen', 'Hunsrückhöhenstr.', 'Emmelshausen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10706.png'), 
      (10707, 'Bremenstadion', 'Bremenplatz 33', 'Ennepetal', 'Germany', 6200, 'grass', 'https://media.api-sports.io/football/venues/10707.png'), 
      (10708, 'Stimberg-Stadion', 'Stimbergstraße 175', 'Oer-Erkenschwick', 'Germany', 20000, 'grass', 'https://media.api-sports.io/football/venues/10708.png'), 
      (11272, 'Sportzentrum Erlensee', 'Konrad-Adenauer Str. 23A, Langendiebach', 'Erlensee', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/11272.png'), 
      (18652, 'Röntgen-Stadion', 'Wupperstr. 21', 'Remscheid', 'Germany', 12463, 'grass', 'https://media.api-sports.io/football/venues/18652.png'), 
      (18872, 'Sportplatz Steinbach', 'Oppenröder Straße 1, Steinbach', 'Fernwald', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/18872.png'), 
      (10712, 'Sportplatz Bamenohl', 'Im Ohl 9', 'Finnentrop', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10712.png'), 
      (12480, 'Rasenplatz Fortuna Heddesheim NR', 'Ahornstr. 78', 'Heddesheim', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/12480.png'), 
      (10713, 'Kunstrasenplatz Jean-Löring-Sportpark', 'Am Vorgebirgstor/Ecke Vorgebirgstraße', 'Köln', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10713.png'), 
      (12481, 'Helmut-Rahn-Sportanlage Kunstrasen unten', 'Raumerstraße 59, Frohnhausen', 'Essen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12481.png'), 
      (12482, 'Sportplatz Fußgönheim', 'Jahnstr. 2', 'Fußgönheim', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/12482.png'), 
      (10714, 'Stadion Ratingen', 'Am Stadion', 'Ratingen', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/10714.png'), 
      (10716, 'Sportpark Gievenbeck', 'Gievenbecker Weg 200, Gievenbeck', 'Münster', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/10716.png'), 
      (10717, 'Sportanlage Bunnsackerweg - Platz 1', 'Bunnsackerweg 28', 'Bremen', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/10717.png'), 
      (10718, '24nexx Arena', 'Jürgen-Graef-Allee 4', 'Hamm', 'Germany', 8500, 'grass', 'https://media.api-sports.io/football/venues/10718.png'), 
      (18700, 'Rasenplatz TuS Hiltrup', 'Osttor 85', 'Münster', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18700.png'), 
      (12483, 'Kirchenberg-Stadion', 'Berliner Allee 54, Ostfeld', 'Hagen', 'Germany', 7000, 'grass', 'https://media.api-sports.io/football/venues/12483.png'), 
      (10721, 'Salus Park', 'Schulzentrum Sudeten Str. 35', 'Hürth', 'Germany', 800, 'artificial turf', 'https://media.api-sports.io/football/venues/10721.png'), 
      (12484, 'Hembergstadion', 'Immermannstr. 10', 'Iserlohn', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/12484.png'), 
      (10723, 'Sportpark Krieschow', 'Am Sportplatz 6', 'Kolkwitz', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10723.png'), 
      (18653, 'Sportzentrum am Hungerbachweg', 'Hungerbachweg 1', 'Landsberg am Lech', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18653.png'), 
      (10725, 'Waldstadion Ludwigsfelde Kunstrasenplatz', 'Str. der Jugend', 'Ludwigsfelde', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10725.png'), 
      (12486, 'Sportplatz GS Heidelberger Strasse', 'Heidelberger Str. 75', 'Düsseldorf', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12486.png'), 
      (18654, 'Julius-Hirsch-Sportanlage 1', 'Harbigstr. 40', 'Berlin', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/18654.png'), 
      (10727, 'Stadion an der Kirschenallee', 'Philippsburger Str. 52, Mechtersheim', 'Römerberg', 'Germany', 2186, 'grass', 'https://media.api-sports.io/football/venues/10727.png'), 
      (10728, 'Sportpark Lankow', 'Ratzeburger Str. 44', 'Schwerin', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/10728.png'), 
      (10729, 'Stadion Meiendorf', 'Meiendorfer Str. 196 / Ellerhoorn', 'Hamburg', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/10729.png'), 
      (10730, 'Schul- & Sportzentrum', 'Judengäßchen', 'Mülheim-Kärlich', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/10730.png'), 
      (12615, 'RuhrStadion', 'Friesenstraße 101, Styrum', 'Mülheim an der Ruhr', 'Germany', 6000, 'artificial turf', 'https://media.api-sports.io/football/venues/12615.png'), 
      (10732, 'ENSO-Oberlausitz-Arena', 'Friedrich-Ludwig-Jahn-Straße 1', 'Neugersdorf', 'Germany', 3270, 'grass', 'https://media.api-sports.io/football/venues/10732.png'), 
      (12487, 'Waldstadion Kirrlach', 'Südliche Waldstr. 2', 'Kirrlach', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/12487.png'), 
      (10734, 'Sportplatz Pampow', 'Gartenweg 28', 'Pampow', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/10734.png'), 
      (18793, 'Parkstadion Obenende', 'Hans-Nolte-Straße 1', 'Papenburg', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/18793.png'), 
      (10735, 'Kunstrasenplatz Helmut-Kusserow-Sportanlage', 'Ecke Escher Str. / Pescher Str.', 'Köln', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10735.png'), 
      (10737, 'Jugendstadion am Preußenstadion', 'Hammer Str. 302', 'Münster', 'Germany', 1300, 'artificial turf', 'https://media.api-sports.io/football/venues/10737.png'), 
      (10738, 'Sportplatz Heinrich-Zille-Straße', 'Heinrich-Zille-Straße 32', 'Stahnsdorf', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10738.png'), 
      (12488, 'Maingau-Energie-Stadion', 'Korbeineweg, Jügesheim', 'Rodgau', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/12488.png'), 
      (10739, 'Sportplatz am Damerower Weg', 'Damerower Weg 25', 'Rostock', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10739.png'), 
      (10740, 'Sportanlage In der Ahe', 'In der Ahe', 'Rotenburg/Wümme', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/10740.png'), 
      (10741, 'SPA SFL Bremerhaven Platz 1', 'Mecklenburger Weg 178', 'Bremerhaven', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10741.png'), 
      (10742, 'MerKur Kunstrasenplatz', 'Rüttersweg 175', 'Bornheim', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10742.png'), 
      (10744, 'Walter-Reinhard-Stadion', 'Jahnstr. 2', 'Sandhausen', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/10744.png'), 
      (11994, 'Volksbank Arena II - Kunstrasenplatz', 'Im Trog 52', 'Schermbeck', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11994.png'), 
      (12490, 'Kunstrasen SV Schlebusch', 'Im Bühl', 'Leverkusen', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12490.png'), 
      (10746, 'Sportpark Neu-Isenburg', 'Kurt-Schumacher-Straße', 'Neu-Isenburg', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/10746.png'), 
      (10747, 'Getränke Hoffmann Stadion', 'Venhauser Straße', 'Spelle', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/10747.png'), 
      (10748, 'Speyer FC 09 Kunstrasen Platz 3', 'Raiffeisenstr. 11', 'Speyer', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10748.png'), 
      (10749, 'Sterkrade Nord Kunstrasenplatz', 'Lütticher Str. 70', 'Oberhausen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10749.png'), 
      (18701, 'Staffelberg Stadion', 'Stadionstrasse 5', 'Hauzenberg', 'Germany', 7500, 'grass', 'https://media.api-sports.io/football/venues/18701.png'), 
      (10752, 'Sportanlage Kiesbarg', 'Kiesbarg 53', 'Hamburg', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10752.png'), 
      (12491, 'Sportgelände Dr.-Walter-Kolb-Straße', 'Dr.-Walter-Kolb-Straße, Ober-Roden', 'Rödermark', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/12491.png'), 
      (12618, 'Sportplatz Königsdorf', 'Pfeilstr. 12', 'Frechen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12618.png'), 
      (18655, 'Rasenplatz Sportanlage am Volkspark', 'Franzstr. 58', 'Kamp-Lintfort', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18655.png'), 
      (12492, 'Marienborn Kunstrasenplatz', 'An der Kirschhecke 25', 'Mainz', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12492.png'), 
      (12494, 'Kunstrasenplatz Unter-Flockenbach', 'Am Wetzelsberg', 'Gorxheimertal', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12494.png'), 
      (10753, 'HWG-Stadion am Zoo', 'Geschwister Scholl Str. 24', 'Saale', 'Germany', 8200, 'grass', 'https://media.api-sports.io/football/venues/10753.png'), 
      (11268, 'Sportplatz Dörenberg (Kunstrasen)', 'Leuwstr. 117', 'Rhineland', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/11268.png'), 
      (10754, 'Holzhofstadion', 'Holzhofstraße 22, Clarholz', 'Herzebrock', 'Germany', 2300, 'grass', 'https://media.api-sports.io/football/venues/10754.png'), 
      (10755, 'Bertram-Möthrath-Stadion', 'Hölderlinweg 9', 'Düren', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10755.png'), 
      (12495, 'Mondpalast Arena', 'Im Sportpark 20, Wanne Eickel', 'Herne', 'Germany', 13500, 'grass', 'https://media.api-sports.io/football/venues/12495.png'), 
      (10756, 'Sepp-Herberger-Stadion', 'Waidallee 2/1', 'Weinheim', 'Germany', 15000, 'grass', 'https://media.api-sports.io/football/venues/10756.png'), 
      (18702, 'Dönges-Eifgen-Stadion', 'Eifgen 1', 'Wermelskirchen', 'Germany', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/18702.png'), 
      (10757, 'Sparkassen-Stadion', 'Molkereiweg 14a', 'Wesel', 'Germany', 1700, 'grass', 'https://media.api-sports.io/football/venues/10757.png'), 
      (10758, 'Ulrike-Meyfarth-Stadion', 'Jahnstr.', 'Wesseling', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/10758.png'), 
      (10759, 'VIACTIV-ARENA im Papenloh', 'Am Sportplatz 20', 'Hamm', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/10759.png'), 
      (18873, 'Akademie-Arena Rasen 1', 'Häuselgrundweg 21', 'Zuzenhausen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18873.png'), 
      (11258, 'Sportplatz Steinrader Damm', 'Steinrader Damm 41', 'Lübeck', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/11258.png'), 
      (11259, 'Stadtwerke Arena', 'Bystedtredder 65', 'Eckernförde', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/11259.png'), 
      (11260, 'Sportanlage Waldeck', 'Steinredder', 'Eutin', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/11260.png'), 
      (11261, 'Niko Nissen Stadion', 'Stadionstraße', 'Risum-Lindholm', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/11261.png'), 
      (11262, 'Sportzentrum Suchsdorfer Weg Platz C4', 'Suchsdorfer Weg 68', 'Kronshagen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/11262.png'), 
      (11263, 'Hans-Peter-Storm-Stadion', 'Schauenburger Platz 1', 'Oldenburg in Holstein', 'Germany', 3500, 'grass', 'https://media.api-sports.io/football/venues/11263.png'), 
      (11264, 'Dr. Curd-Waßmund-Sportplatz', 'Techauer Weg 13, Pansdorf', 'Ratekau', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/11264.png'), 
      (11265, 'Rasenplatz Reinfeld', 'Bischofsteicher Weg 45a', 'Holstein', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/11265.png'), 
      (11266, 'Sportanlage Stettiner Straße', 'Stettiner Str. 29', 'Neumünster', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/11266.png'), 
      (11267, 'Stadion Mürwiker Straße', 'Arndtstr. 5', 'Flensburg', 'Germany', 12000, 'grass', 'https://media.api-sports.io/football/venues/11267.png'), 
      (18785, 'Professor-Reinmüller-Platz', 'Tornquiststr. 79, Eimsbüttel', 'Hamburg', 'Germany', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/18785.png'), 
      (18786, 'Paul-Hauenschild-Plätze 6', 'Ulzburger Str. 94', 'Norderstedt', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18786.png'), 
      (18787, 'Hammer Park Stadion', 'Hammer Steindamm 131', 'Hamburg', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18787.png'), 
      (11996, 'Wilhelm-Lindemann-Sportanlage', 'Binnenfeldredder 9, Lohbrügge', 'Hamburg', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/11996.png'), 
      (11997, 'Werner-Bornholdt-Sportzentrum', 'Ellerbeker Str. 25', 'Bönningstedt', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/11997.png'), 
      (12703, 'Sportplatz Parkweg', 'Saseler Parkweg 14', 'Hamburg', 'Germany', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12703.png'), 
      (18788, 'Großer Moorweg Platz 1', 'Großer Moorweg 30', 'Tornesch', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18788.png'), 
      (18789, 'Sportanlage Bekkamp', 'Bekkamp 25-27, Jenfeld', 'Hamburg', 'Germany', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/18789.png'), 
      (11269, 'Rasenplatz Halfenstadion', 'Halfenstr. 30', 'Aachen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/11269.png'), 
      (11270, 'Sportplatz Breinig (Kunstrasen)', 'Schützheide 50d', 'Rhld.', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11270.png'), 
      (11998, 'Hamalandstadion', 'Ottensteiner Str. 64', 'Vreden', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/11998.png'), 
      (11271, 'Wahrendorff-Arena', 'Akazienweg 10, Ramlingen', 'Burgdorf', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/11271.png'), 
      (12499, 'Nordseestadion', 'Am Stadion 10', 'Bremerhaven', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/12499.png'), 
      (11999, 'Rollsportstadion', 'Jürgensdeich 1', 'Bremen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/11999.png'), 
      (11273, 'Sportplatz am Weiher', 'Im Weiher', 'Flieden', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/11273.png'), 
      (11274, 'Rasenplatz Limburg-Dietkirchen', 'Koberner Str.', 'Limburg', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/11274.png'), 
      (11275, 'Rasenplatz Hünfeld', 'Landerneauallee', 'Hünfeld', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/11275.png'), 
      (18874, 'Sportverein Neuhof', 'Jahnstr.', 'Neuhof', 'Germany', 4500, 'grass', 'https://media.api-sports.io/football/venues/18874.png'), 
      (11277, 'Kunstrasenplatz Mörfelden-Walldorf (RW)', 'An den Sportplätzen', 'Mörfelden-Walldorf', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11277.png'), 
      (18783, 'Rasenplatz 2 Burghaun-Steinbach', 'Mittelstr.', 'Burghaun', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18783.png'), 
      (11279, 'Kunstrasenplatz F-Zeilsheim', 'Lenzenbergstr. 24', 'Frankfurt am Main', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11279.png'), 
      (12000, 'VolksBank-Arena an der Welbershöhe', 'Bresserbergstr. 49', 'Kleve', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/12000.png'), 
      (12001, 'Glück Auf Sportplatz', 'Burgaltendorfer Str.', 'Hattingen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12001.png'), 
      (12291, 'Jahn-Sport-Anlage', 'Gelderner Straße 69', 'Tönisvorst', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12291.png'), 
      (12002, 'Eisbachtalstadion Kunstrasen', 'Eppenroder Str.', 'Nentershausen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12002.png'), 
      (18791, 'Elversberg Kunstrasen', 'Lindenstr.', 'Spiesen-Elversberg', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18791.png'), 
      (18792, 'Alois-Omlor-Sportpark', 'Zum Sportplatz, Jägersburg', 'Homburg', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/18792.png'), 
      (12292, 'Sportstätten auf dem Quintinsberg', 'Sportplatz an der L213', 'Karbach', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12292.png'), 
      (18704, 'Etzwiesenstadion', 'Etzwiesen / Theodor-Körner-Str.', 'Backnang', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/18704.png'), 
      (18705, 'Stadion am Bruchwald', 'Waldstr. 6', 'Bietigheim-Bissingen', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/18705.png'), 
      (12003, 'Dietenbach-Sportpark', 'Robert-Ruh-Weg 1', 'Freiburg im Breisgau', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12003.png'), 
      (12004, 'Lörrach-Grütt-Kunstrasen', 'Grüttweg 15', 'Lörrach', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12004.png'), 
      (12005, 'Sportplatz Sömmeringstraße', 'Sömmeringstraße 15', 'Berlin', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/12005.png'), 
      (12006, 'Volksstadion Greifswald', 'Karl-Liebknecht-Ring 2', 'Greifswald', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/12006.png'), 
      (12007, 'Volksstadion', 'Trotzenburger Weg 14', 'Rostock', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/12007.png'), 
      (12008, 'Sportpark Staaken', 'Eichholzbahn 116', 'Berlin', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12008.png'), 
      (12009, 'Sportplatz Schildhornstraße', 'Kreuznacher Str. 29', 'Berlin', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12009.png'), 
      (12010, 'Sparkassenarena Stadt Seelow', 'Am Stadion 3A', 'Seelow', 'Germany', 3700, 'grass', 'https://media.api-sports.io/football/venues/12010.png'), 
      (11280, 'Stadion Dachwig', 'Am Stadion', 'Dachwig', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/11280.png'), 
      (11281, 'Sportplatz Zorbau', 'Am Sportplatz', 'Zorbau', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/11281.png'), 
      (11282, 'Husarensportpark Grimma Hauptplatz', 'Lausicker Str. 8a', 'Grimma', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/11282.png'), 
      (12011, 'Sportplatz am Hohen Kreuz', 'Büchelbergstr. 82', 'Haibach', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/12011.png'), 
      (12502, 'Rudolf Dychehoff Sportanlage', 'Rudolf Dyckerhoff Str.', 'Wiesbaden', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/12502.png'), 
      (12621, 'Kunstrasenplat BSA Überruhr unten', 'Überruhrstr. 298', 'Essen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12621.png'), 
      (12077, 'Rudi-Ziegler-Sportanlage Hauptspielfeld', 'Wildensorger Hauptstr. 80, Wildensorg', 'Bamberg', 'Germany', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/12077.png'), 
      (12503, 'AM-Stadion', 'Boker Straße 31', 'Delbrück', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/12503.png'), 
      (12078, 'Sportzentrum Donaustauf - Platz 1', 'Regensburger Str. 30', 'Donaustauf', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12078.png'), 
      (18875, 'Stadion im Sportforum Kohlgarten', 'Kohlgartenstr. 67B', 'Wernigerode', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/18875.png'), 
      (12506, 'Rasenplatz Grabensprung NR1', 'Grabensprung 56', 'Berlin', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12506.png'), 
      (12016, 'Fichte-Sportplatz', 'Karl-Marx-Straße 146', 'Brieselang', 'Germany', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12016.png'), 
      (12018, 'Jako-Arena', 'Am Sportplatz', 'Mulfingen', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/12018.png'), 
      (12020, 'Erftstadion', 'Weimarstraße 74, Kapellen', 'Grevenbroich', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/12020.png'), 
      (12079, 'TSV-Platz in der Au', 'Zum Sportgelände 12, Karlburg', 'Karlstadt', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12079.png'), 
      (12510, 'Kampfbahn Schwansbell Rasen', 'Schwansbeller Weg 7a', 'Lünen', 'Germany', 10000, 'grass', 'https://media.api-sports.io/football/venues/12510.png'), 
      (12105, 'Volksparkstadion', 'Alt Ruppiner Allee 56', 'Neuruppin', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/12105.png'), 
      (18876, 'Sportplatz Quierschied', 'Holzer Str.', 'Quierschied', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18876.png'), 
      (12030, 'Waldsportpark', 'Winkelschneise 9, Heimstättensiedlung', 'Darmstadt', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/12030.png'), 
      (12033, 'Sportanlage der Sportfreunde Seligenstadt', 'Aschaffenburger Straße', 'Seligenstadt', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12033.png'), 
      (12514, 'Kirchberg Kunstrasen', 'Dickenschieder Str. 15', 'Hunsrück', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12514.png'), 
      (12625, 'Stadion Am Steg', 'Elsterdamm 41', 'Gera', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/12625.png'), 
      (12038, 'Stadion Entenpark', 'Am Wingertsberg', 'Eder', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/12038.png'), 
      (12518, 'Wackerplatz', 'Wackerweg 26, Reinickendorf', 'Berlin', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/12518.png'), 
      (12055, 'Jacob-Thode-Platz', 'Lütten Hall 1a', 'Halstenbek', 'Germany', 1200, 'grass', 'https://media.api-sports.io/football/venues/12055.png'), 
      (12056, 'Stadion Biener Busch', 'Im Lägermarsch, Biene', 'Lingen', 'Germany', 1800, 'grass', 'https://media.api-sports.io/football/venues/12056.png'), 
      (12058, 'Bechtle Stadion', 'Karlsruher Str. 28, Spielberg', 'Karlsbad', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/12058.png'), 
      (12295, 'Stadion am Brentanobad', 'Rödelheimer Parkweg 39', 'Frankfurt am Main', 'Germany', 5200, 'grass', 'https://media.api-sports.io/football/venues/12295.png'), 
      (12296, 'Friedrich-Ludwig-Jahn-Sportplatz', 'Babickstr. 9', 'Schöneiche', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/12296.png'), 
      (12297, 'Stadion an der Gisselberger Straße', 'Gisselberger Str. 37', 'Marburg', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/12297.png'), 
      (12627, 'Sportplatz Menzenberger Straße', 'Menzenberger Straße', 'Bad Honnef', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/12627.png'), 
      (12523, 'Sportplatz DSC 99 Hauptplatz Kunstrasen', 'Windscheidstr. 18', 'Düsseldorf', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12523.png'), 
      (12524, 'Sportplatz Heiderhofweg', 'Heider-Hof-Weg', 'Aachen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12524.png'), 
      (12525, 'Sportanlage Frankfurter Straße', 'Außerhalb-Ober-Roden 15, Ober-Roden', 'Rödermark', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/12525.png'), 
      (12526, 'Kunstrasenplatz F-Schwanheim', 'Schwanheimer Bahnstr. 98', 'Frankfurt am Main', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12526.png'), 
      (12628, 'Homburg-Nümbrecht Kunstrasen', 'Mateh-Yehuda-Str. 9', 'Nümbrecht', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12628.png'), 
      (12527, 'Stadion Hordeler Heide', 'Hordeler Heide 189, Horde', 'Bochum', 'Germany', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/12527.png'), 
      (12629, 'Stadion Oststraße', 'Oststr.', 'Herzogenrath', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12629.png'), 
      (12528, 'Kunstrasenplatz Niedernhausen', 'Idsteiner Str. 90', 'Niedernhausen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12528.png'), 
      (12529, 'Kunstrasenplatz Neu-Isenburg-Zeppelinheim', 'Heideweg', 'Neu-Isenburg', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12529.png'), 
      (12531, 'Sportanlage Stubenrauchstraße', 'Neuköllner Straße 277, Neukölln', 'Berlin', 'Germany', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/12531.png'), 
      (12532, 'Kunstrasenplatz F-Bornheim', 'Seckbacher Landstr. 76', 'Frankfurt am Main', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12532.png'), 
      (12533, 'Rasenplatz 1 Fulda-Johannesberg', 'Agricolastraße 8', 'Fulda', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12533.png'), 
      (12535, 'Sportanlagen VfB Speldorf', 'Saarner Str 326', 'Mülheim an der Ruhr', 'Germany', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/12535.png'), 
      (12536, 'Rasenplatz Tönisberg', 'Schaephuysener Str. 6', 'Kempen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12536.png'), 
      (12537, 'Kunstrasenplatz Erin-Kampfbahn', 'Karlstr. 44', 'Castrop-Rauxel', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12537.png'), 
      (12630, 'Walter Lück Sportanlage', 'Friedhofstraße 13', 'Wiehl', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12630.png'), 
      (12539, 'Hoppecketalstadion', 'Hoppecketalstr.', 'Willingen', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/12539.png'), 
      (12540, 'Sportanlage Volkspark Platz 1', 'Straße am Schoelerpark 39', 'Berlin', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12540.png'), 
      (12635, 'SpA Hainsberg Rasenplatz', 'Kirchstr. 1', 'Freital', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12635.png'), 
      (18877, 'Seppl-Herberger-Stadion', 'Alsenweg, Waldhof', 'Mannheim', 'Germany', 15200, 'grass', 'https://media.api-sports.io/football/venues/18877.png'), 
      (18660, 'Sportpark Paulshöhe', 'Schleifmühlenweg 19', 'Schwerin', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/18660.png'), 
      (12734, 'Sportplatz Holzkirchen', 'Haidstr.', 'Holzkirchen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/12734.png'), 
      (12736, 'BZA Wulsdorf', null, null, 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/12736.png'), 
      (18708, 'Stadion an der Linde', 'Brander Str. 6', 'Aachen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18708.png'), 
      (18878, 'Stadion am Roten Steg', 'Untere Au 3', 'Bad Kötzting', 'Germany', 6000, 'grass', 'https://media.api-sports.io/football/venues/18878.png'), 
      (18710, 'Sportzentrum am Mittelberg', 'Klotzbergstrasse 47', 'Bühlertal', 'Germany', 4000, 'grass', 'https://media.api-sports.io/football/venues/18710.png'), 
      (18711, 'Jakob Schaumaier Sportpark', 'Helmut-Schreiner-Weg 1', 'Traunstein', 'Germany', 570, 'grass', 'https://media.api-sports.io/football/venues/18711.png'), 
      (18881, 'Gießerei-Arena Kunstrasen', 'Blumenthaler Str.', 'Torgelow', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18881.png'), 
      (18713, 'Waldstadion Erlbach', 'Petzenthal 31', 'Erlbach', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/18713.png'), 
      (18714, 'Max-Graser-Stadion', 'Esslinger Str. 120', 'Fellbach', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/18714.png'), 
      (18885, 'Projekt 29 Arena', 'Isarstr. 85', 'Regensburg', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18885.png'), 
      (18886, 'Kohlenberg-Arena Fuchsstadt', 'Am Kohlenberg', 'Fuchsstadt', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18886.png'), 
      (18715, 'Sportgelände Gebenbach', 'Urspringerweg 20', 'Gebenbach', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/18715.png'), 
      (18716, 'Metallbau Herold Sportstätte', 'Federwasen 2', 'Wiesentheid', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18716.png'), 
      (18717, 'Abenstein Arena', 'Sportallee 12', 'Gersthofen', 'Germany', 4476, 'grass', 'https://media.api-sports.io/football/venues/18717.png'), 
      (18718, 'A-Platz TSV Godshorn', 'Spielplatzweg 20', 'Langenhagen', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18718.png'), 
      (18720, 'Schwabenstadion', 'Stadionstraße 1', 'Gundelfingen', 'Germany', 8000, 'grass', 'https://media.api-sports.io/football/venues/18720.png'), 
      (18721, 'Kunstrasenplatz Bezirkssportanlage Emst', 'Haßleyer Str. 55', 'Hagen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18721.png'), 
      (18722, 'Sportpark Hallbergmoos', 'Am Söldnermoos 61', 'Hallbergmoos', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/18722.png'), 
      (18889, 'Rasenplatz Sportpark Goldäcker', 'Leinfelder Str. 101', 'Leinfelden-Echterdingen', 'Germany', 2000, 'grass', 'https://media.api-sports.io/football/venues/18889.png'), 
      (18729, 'B-Platz FL Melos-Platz', 'Friedrich-Ludwig-Jahn-Str.', 'Melle', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18729.png'), 
      (18730, 'Sportpark Niederkassel-Süd Platz 1', 'Südstr. 99', 'Niederkassel', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18730.png'), 
      (18731, 'ATSV Mutschelbach Piston`s EDEKA-Arena', 'Waldenserstr. 1', 'Karlsbad', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18731.png'), 
      (18732, 'Jahnstadion', 'Justinus-Kerner-Str.', 'Schwäbisch Gmünd', 'Germany', 3000, 'grass', 'https://media.api-sports.io/football/venues/18732.png'), 
      (18893, 'Sportplatz Scharbeutzer Straße 2', 'Scharbeutzer Straße 23', 'Hamburg', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18893.png'), 
      (18736, 'Rülzheim Rasenplatz 1', 'Am Stadion', 'Rülzheim', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18736.png'), 
      (18737, 'Stadion Dammenmühle', 'Unterer Dammen 25', 'Lahr', 'Germany', 1600, 'grass', 'https://media.api-sports.io/football/venues/18737.png'), 
      (18738, 'Reddy Küchen Arena', 'Zwetschenweg 29', 'Marburg an der Lahn', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18738.png'), 
      (18894, 'Optima Sportpark', 'Spitalmühlenstr. 28', 'Schwäbisch Hall', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/18894.png'), 
      (18895, 'TSG Gelände Kunstrasenplatz', 'Freibad 3', 'Tübingen', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18895.png'), 
      (18740, 'BIEKRA-Sportpark', 'Gaudigstraße 29, Theesen', 'Bielefeld', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18740.png'), 
      (18741, 'Sportpark Uelzener Straße', 'Uelzener Straße 90', 'Lüneburg', 'Germany', 5000, 'grass', 'https://media.api-sports.io/football/venues/18741.png'), 
      (18742, 'Drömlingstadion', 'Am Drömlingstadion', 'Wolfsburg', 'Germany', 2500, 'grass', 'https://media.api-sports.io/football/venues/18742.png'), 
      (18899, 'DOTLUX Fußballpark Weißenburg Platz 1', 'Gunzenhausener Str. 45', 'Weißenburg in Bayern', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18899.png'), 
      (18743, 'Sportplatz Westerhausen I', 'Wolfsberg', 'Thale', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18743.png'), 
      (18781, 'Hohkeppel Kunstrasen', 'Schönenborn 33, Köttingen', 'Lindlar', 'Germany', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/18781.png'), 
      (18790, 'Sportanlage Landesgrenze', 'Georg-Wilhelm-Str. 6', 'Hamburg', 'Germany', 1500, 'grass', 'https://media.api-sports.io/football/venues/18790.png'), 
      (18794, 'Sportplatz Am Auetal', 'Büntweg 5', 'Ahlerstedt', 'Germany', 1000, 'grass', 'https://media.api-sports.io/football/venues/18794.png');