INSERT INTO venues (id, name, address, city, country, capacity, surface, image) 
VALUES (1578, 'Vodafone Park', 'Dolmabahçe Gazhane Caddesi, Beşiktaş', 'İstanbul', 'Turkey', 43500, 'grass', 'https://media.api-sports.io/football/venues/1578.png'), 
      (1584, 'Başakşehir Fatih Terim Stadyumu', 'Yunus Emre Caddesi, Başakşehir', 'İstanbul', 'Turkey', 17319, 'grass', 'https://media.api-sports.io/football/venues/1584.png'), 
      (1587, 'Konya Büyükşehir Belediye Stadyumu', 'Sille Parsana Mh., Kaletaş Caddesi, Selçuklu', 'Konya', 'Turkey', 42276, 'grass', 'https://media.api-sports.io/football/venues/1587.png'), 
      (1581, 'Ülker Stadyumu Fenerbahçe Şükrü Saracoğlu Spor Kompleksi', 'Recep Peker Caddesi, Kadıköy', 'İstanbul', 'Turkey', 53586, 'grass', 'https://media.api-sports.io/football/venues/1581.png'), 
      (12598, 'NEF Stadyumu', 'İstanbul Çevre Yolu, Aslantepe', 'İstanbul', 'Turkey', 52695, 'grass', 'https://media.api-sports.io/football/venues/12598.png'), 
      (1968, 'Atatürk Olimpiyat Stadı', 'Atatürk Olimpiyat Stadı Otoparkı, İkitelli', 'İstanbul', 'Turkey', 76092, 'grass', 'https://media.api-sports.io/football/venues/1968.png'), 
      (9942, 'Eryaman Stadyumu', 'Devlet Mah., 232. Sk. No:7, Tunahan Mahallesi, Etimesgut', 'Ankara', 'Turkey', 20560, 'grass', 'https://media.api-sports.io/football/venues/9942.png'), 
      (1583, 'Göztepe Gürsel Aksel Stadı', 'Mehmet Ali Akman, 20/3. Sk. No:28, Konak', 'İzmir', 'Turkey', 30035, 'artificial turf', 'https://media.api-sports.io/football/venues/1583.png'), 
      (1574, 'Spor Toto Akhisar Belediye Stadı', '167. Sokak', 'Akhisar', 'Turkey', 12139, 'grass', 'https://media.api-sports.io/football/venues/1574.png'), 
      (1575, 'Bahçeşehir Okulları Stadyumu', 'Sarıkadıoğlu Caddesi, Oba, Obaköy', 'Alanya', 'Turkey', 15000, 'grass', 'https://media.api-sports.io/football/venues/1575.png'), 
      (2378, 'Eryaman Stadyumu', 'Devlet Mah., 232. Sk. No:7, Tunahan Mahallesi, Etimesgut', 'Ankara', 'Turkey', 20560, 'grass', 'https://media.api-sports.io/football/venues/2378.png'), 
      (1590, 'Medical Park Stadyumu', 'Trabzon Giresun Yolu, Akyaz', 'Trabzon', 'Turkey', 41513, 'grass', 'https://media.api-sports.io/football/venues/1590.png'), 
      (1588, 'Yeni Malatya Stadyumu', 'Bulgurlu Mahallesi', 'Malatya', 'Turkey', 27044, 'grass', 'https://media.api-sports.io/football/venues/1588.png'), 
      (2366, 'Dr. Necmettin Şeyhoğlu Stadı', 'Fatih Caddesi, Yenişehir', 'Karabük', 'Turkey', 14000, 'grass', 'https://media.api-sports.io/football/venues/2366.png'), 
      (1586, 'Kadir Has Şehir Stadı', 'İle Fırat Caddesi', 'Kayseri', 'Turkey', 40458, 'grass', 'https://media.api-sports.io/football/venues/1586.png'), 
      (1589, 'Yeni Sivas 4 Eylül Stadyumu', 'Muhsin Yazıcıoğlu Bulvarı', 'Sivas', 'Turkey', 27532, 'grass', 'https://media.api-sports.io/football/venues/1589.png'), 
      (12278, 'Bitci Timsah Park', 'Dikkaldırım Mah. Hayran Cad., Osmangazi', 'Bursa', 'Turkey', 45000, 'grass', 'https://media.api-sports.io/football/venues/12278.png'), 
      (1585, 'Recep Tayyip Erdoğan Stadyumu', 'Tepebaşı Caddesi, Kasımpaşa, Beyoğlu', 'İstanbul', 'Turkey', 14234, 'grass', 'https://media.api-sports.io/football/venues/1585.png'), 
      (1577, 'Antalya Stadyumu', '100. Yıl Bulvarı', 'Antalya', 'Turkey', 33032, 'grass', 'https://media.api-sports.io/football/venues/1577.png'), 
      (1580, 'Çaykur Didi Stadyumu', 'Karadeniz Sahli Yolu Yanyolu', 'Rize', 'Turkey', 15558, 'grass', 'https://media.api-sports.io/football/venues/1580.png'), 
      (2375, 'Gaziantep Stadyumu', 'Yukarıbeylerbeyi Mah. 15 Nolu Sok., Şehitkamil', 'Gaziantep', 'Turkey', 35558, 'grass', 'https://media.api-sports.io/football/venues/2375.png'), 
      (1741, 'Kazım Karabekir Stadyumu', 'Erzincan-Erzerum Yolu, Yakutiye', 'Erzurum', 'Turkey', 23700, 'grass', 'https://media.api-sports.io/football/venues/1741.png'), 
      (11924, 'Yeni Adana Stadyumu', 'Çarkıpare, Sarıçam', 'Adana', 'Turkey', 33543, 'grass', 'https://media.api-sports.io/football/venues/11924.png'), 
      (2368, 'Zafer Stadı', 'Afyon Uşak Yolu, Selçuklu Mah.', 'Afyonkarahisar', 'Turkey', 15500, 'grass', 'https://media.api-sports.io/football/venues/2368.png'), 
      (12684, 'Alsancak Mustafa Denizli Stadı', 'Şehitleri Caddesi No:10', 'İzmir', 'Turkey', 15000, 'grass', 'https://media.api-sports.io/football/venues/12684.png'), 
      (12279, 'Bornova Aziz Kocaoğlu Stadyumu', '1412 Sokak No:3, Bornova, Doğanlar Mah', 'İzmir', 'Turkey', 12500, 'artificial turf', 'https://media.api-sports.io/football/venues/12279.png'), 
      (2370, 'Balıkesir Atatürk Stadyumu', 'Stadyumu Caddesi', 'Balıkesir', 'Turkey', 15800, 'grass', 'https://media.api-sports.io/football/venues/2370.png'), 
      (2371, 'Bolu Atatürk Stadyumu', 'Stadyumu Caddesi', 'Bolu', 'Turkey', 8881, 'grass', 'https://media.api-sports.io/football/venues/2371.png'), 
      (2372, 'Denizli Atatürk Stadyumu', 'Lise Caddesi', 'Denizli', 'Turkey', 15427, 'grass', 'https://media.api-sports.io/football/venues/2372.png'), 
      (2373, 'Elaziğ Atatürk Stadyumu', 'Malatya Yolu, 10 km', 'Elaziğ', 'Turkey', 13923, 'grass', 'https://media.api-sports.io/football/venues/2373.png'), 
      (2374, 'Yeni Eskişehir Stadyumu', 'Ulusal Egemenlik Bulvarı', 'Eskişehir', 'Turkey', 34930, 'grass', 'https://media.api-sports.io/football/venues/2374.png'), 
      (12089, 'Çotanak Stadyumu', 'Aksu', 'Giresun', 'Turkey', 22028, 'grass', 'https://media.api-sports.io/football/venues/12089.png'), 
      (12280, 'Yeni Hatay Stadyumu', 'Haraparası, Süreyya Halefoğlu Cd. No:64', 'Hatay', 'Turkey', 25000, 'grass', 'https://media.api-sports.io/football/venues/12280.png'), 
      (2379, 'Ümraniye Hekimbaşı Şehir Stadyumu', 'Küçüksu Caddesi, Ümraniye', 'İstanbul', 'Turkey', 2500, 'grass', 'https://media.api-sports.io/football/venues/2379.png'), 
      (12281, 'Necmi Kadıoğlu Stadyumu', 'İncirtepe Mah., Esenyurt', 'İstanbul', 'Turkey', 7500, 'grass', 'https://media.api-sports.io/football/venues/12281.png'), 
      (2381, 'Seyrantepe Spor Kompleksi Stadyumu 1', 'Kanal Caddesi', 'Diyarbakır', 'Turkey', 2500, 'grass', 'https://media.api-sports.io/football/venues/2381.png'), 
      (2382, 'Konya Atatürk Spor Kompleksi', 'Stad Sokak', 'Konya', 'Turkey', 22459, 'grass', 'https://media.api-sports.io/football/venues/2382.png'), 
      (2384, 'Ostim Stadı', 'Cevat Dündar Caddesi, Yenimahalle', 'Ankara', 'Turkey', 4271, 'grass', 'https://media.api-sports.io/football/venues/2384.png'), 
      (2385, 'Bodrum İlçe Stadı', 'Marsmabedi Caddesi', 'Bodrum', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/2385.png'), 
      (2386, 'Bandırma 17 Eylül Stadı', '600 Evler Mahallesi', 'Bandırma', 'Turkey', 5400, 'grass', 'https://media.api-sports.io/football/venues/2386.png'), 
      (2387, 'İBB Bayrampaşa Stadı', 'Şehit Kamil Balkan Caddesi No:111, Yıldırım Mah., Bayrampaşa', 'İstanbul', 'Turkey', 1300, 'grass', 'https://media.api-sports.io/football/venues/2387.png'), 
      (2388, 'Darıca 15 Temmuz Stadyumu', 'Özbay Sokak', 'Darıca', 'Turkey', 6500, 'grass', 'https://media.api-sports.io/football/venues/2388.png'), 
      (2389, 'Etimesgut Belediyesi Kemal Atatürk Stadyumu', '30 Ağustos Mahallesi', 'Etimesgut', 'Turkey', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/2389.png'), 
      (2390, 'Eyüp Stadı', 'Hz. Halid Bulvarı', 'İstanbul', 'Turkey', 2367, 'grass', 'https://media.api-sports.io/football/venues/2390.png'), 
      (2392, 'Fethiye İlçe Stadyumu', 'Muzaffer Dontlu Caddesi', 'Fethiye', 'Turkey', 8372, 'grass', 'https://media.api-sports.io/football/venues/2392.png'), 
      (2393, 'Gümüşhane Şehir Stadı', 'Canca Mah.', 'Gümüşhane', 'Turkey', 4700, 'grass', 'https://media.api-sports.io/football/venues/2393.png'), 
      (2394, 'Cebeci İnönü Stadı', 'Dumlupınar Caddesi', 'Ankara', 'Turkey', 35550, 'grass', 'https://media.api-sports.io/football/venues/2394.png'), 
      (2395, '12 Şubat Stadyumu', 'Şazibey Mahallesi', 'Kahramanmaraş', 'Turkey', 15050, 'grass', 'https://media.api-sports.io/football/venues/2395.png'), 
      (2396, 'Kastamonu Gazi Stadyumu', 'Stadyum Caddesi No:6, Saraçlar Mah.', 'Kastamonu', 'Turkey', 4033, 'grass', 'https://media.api-sports.io/football/venues/2396.png'), 
      (2397, 'Aktepe Stadı', '2. Caddesi 1040. Sokak', 'Ankara', 'Turkey', 4883, 'artificial turf', 'https://media.api-sports.io/football/venues/2397.png'), 
      (2398, 'Kırklareli Atatürk Stadyumu', null, 'Kırklareli', 'Turkey', 8000, 'grass', 'https://media.api-sports.io/football/venues/2398.png'), 
      (2399, 'Mümin Özkasap Spor Tesisleri', '167. Sokak', 'Manisa', 'Turkey', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/2399.png'), 
      (2400, 'Manisa 19 Mayıs Stadyumu', 'Akhisar Caddesi, Şehitler', 'Manisa', 'Turkey', 16597, 'grass', 'https://media.api-sports.io/football/venues/2400.png'), 
      (2401, 'Menemen Şehir Stadı', 'Şht. Ali İhsan Kalmaz Cd.', 'Menemen', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/2401.png'), 
      (2402, 'Niğde 5 Şubat Stadı', null, 'Niğde', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/2402.png'), 
      (9944, 'Pendik Stadyumu', 'Stadyum Sokak 18, Pendik', 'İstanbul', 'Turkey', 4000, 'grass', 'https://media.api-sports.io/football/venues/9944.png'), 
      (2404, 'Yeni Sakarya Atatürk Stadyumu', 'Yağcılar Mah. Karasu Yolu, Yağcılar, Sakarya', 'Adapazarı', 'Turkey', 28710, 'grass', 'https://media.api-sports.io/football/venues/2404.png'), 
      (11925, 'Samsun Yeni 19 Mayıs Stadyumu', 'Sanayi Mahallesi, Tekkeköy', 'Samsun', 'Turkey', 34658, 'grass', 'https://media.api-sports.io/football/venues/11925.png'), 
      (9950, 'Muhsin Yazıcıoğlu Stadyumu', 'Erzican-Erzurum Çevre Yolu', 'Sivas', 'Turkey', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/9950.png'), 
      (2409, 'Burhanettin Kocamaz Stadı', 'Kırklarsırtı Mah. 2624, Sokak No. 4', 'Tarsus', 'Turkey', 4201, 'grass', 'https://media.api-sports.io/football/venues/2409.png'), 
      (2410, 'Gaziosmanpaşa Stadyumu', 'G.O.P. Bulvarı', 'Tokat', 'Turkey', 5762, 'grass', 'https://media.api-sports.io/football/venues/2410.png'), 
      (2391, 'Vefa Stadı', 'Fevzi Paşa Caddesi, Karagümrük, Çukurbostan', 'İstanbul', 'Turkey', 11722, 'grass', 'https://media.api-sports.io/football/venues/2391.png'), 
      (2412, 'Uşak 1 Eylül Stadı', 'Zübeyde Hanım Caddesi No:20, Kurtuluş Mah.', 'Uşak', 'Turkey', 6094, 'grass', 'https://media.api-sports.io/football/venues/2412.png'), 
      (2413, 'Karaelmas Kemal Köksal Stadyumu', 'Yayla Mah. 21 Haziran Kurtuluş Alanı No:4', 'Zonguldak', 'Turkey', 13795, 'grass', 'https://media.api-sports.io/football/venues/2413.png'), 
      (2414, 'İnegöl İlçe Stadyumu', 'Edirne Caddesi', 'İnegöl', 'Turkey', 4975, 'grass', 'https://media.api-sports.io/football/venues/2414.png'), 
      (2415, 'Şanlıurfa GAP Stadyumu', 'Mevlana Caddesi', 'Şanlıurfa', 'Turkey', 28965, 'grass', 'https://media.api-sports.io/football/venues/2415.png'), 
      (4685, 'Bayburt Genç Osman Stadyumu', null, 'Bayburt', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/4685.png'), 
      (4686, 'Mustafa Kemal Atatürk Stadyumu', 'Mustafa Kemal Caddesi No:4', 'Velimeşe', 'Turkey', 1100, 'grass', 'https://media.api-sports.io/football/venues/4686.png'), 
      (9951, 'Yavuz Selim Stadı', 'İnönü Mh.', 'Trabzon', 'Turkey', 1820, 'grass', 'https://media.api-sports.io/football/venues/9951.png'), 
      (4688, 'Ahi Evran Stadı', null, 'Kırşehir', 'Turkey', 7500, 'grass', 'https://media.api-sports.io/football/venues/4688.png'), 
      (4689, 'Atatürk Şehir Stadyumu', 'Ipek Yolu Caddesi', 'Van', 'Turkey', 11500, 'grass', 'https://media.api-sports.io/football/venues/4689.png'), 
      (4690, 'Dr. Turhan Kılıçcıoğlu Stadyumu', 'Hamit Kaplan Caddesi', 'Çorum', 'Turkey', 11263, 'grass', 'https://media.api-sports.io/football/venues/4690.png'), 
      (4774, 'Çankırı Atatürk Stadyumu', 'Refik Saydam Caddesi, Abdulhalik Renda Mah.', 'Çankırı', 'Turkey', 5109, 'grass', 'https://media.api-sports.io/football/venues/4774.png'), 
      (4775, 'Bingöl Şehir Stadyumu', '75. Yıl Cumhuriyet Caddesi', 'Bingöl', 'Turkey', 3500, 'grass', 'https://media.api-sports.io/football/venues/4775.png'), 
      (4776, 'Kelkit İlçe Stadı', 'Stad Sokak, Atatürk Mah.', 'Kelkit', 'Turkey', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/4776.png'), 
      (4777, 'Dağılgan Stadyumu', null, 'Aksaray', 'Turkey', 15000, 'grass', 'https://media.api-sports.io/football/venues/4777.png'), 
      (4778, 'Akşehir Nasreddin Hoca Stadı', 'Stadyum Caddesi, Yeni Mah.', 'Akşehir', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/4778.png'), 
      (4779, 'Vali Lütfü Yiğenoğlu Stadyumu', 'Hanibaba Bulvarı', 'Ağrı', 'Turkey', 10000, 'grass', 'https://media.api-sports.io/football/venues/4779.png'), 
      (4780, 'Bartın Atatürk Stadyumu', 'Gölbucağı', 'Bartın', 'Turkey', 8000, 'grass', 'https://media.api-sports.io/football/venues/4780.png'), 
      (7145, 'Derince Belediyespor Doğal Çim Stadyumu', 'Yenikent Mah.', 'Derince', 'Turkey', 1650, 'grass', 'https://media.api-sports.io/football/venues/7145.png'), 
      (4781, 'Biga İlyas Bayram Stadyumu', 'Kıbrıs şehitler Caddesi No:93, Sakarya Mah.', 'Biga', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/4781.png'), 
      (4782, 'Bozüyük Şehir Stadı', 'Şenkal Caddesi', 'Bozüyük', 'Turkey', 4100, 'grass', 'https://media.api-sports.io/football/venues/4782.png'), 
      (4783, 'Bucak İlçe Stadı', null, 'Bucak', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/4783.png'), 
      (4784, 'Tunceli Atatürk Stadyumu', 'Atatürk Mah.', 'Tunceli', 'Turkey', 1200, 'grass', 'https://media.api-sports.io/football/venues/4784.png'), 
      (4785, '25 Kasım Stadyumu', null, 'Edirne', 'Turkey', 3500, 'grass', 'https://media.api-sports.io/football/venues/4785.png'), 
      (4786, 'Görele 13 Şubat Stadyumu', 'Çanakçı Yolu No:15, Yeşiltepe Mah.', 'Görele', 'Turkey', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/4786.png'), 
      (4787, 'Isparta Atatürk Şehir Stadyumu', '116. Caddesi, Altı', 'Isparta', 'Turkey', 10000, 'grass', 'https://media.api-sports.io/football/venues/4787.png'), 
      (4788, 'Iğdır Atatürk Mahallesi Futbol Sahası', 'Yunus Emre Caddesi No:8, Atatürk Mah.', 'Iğdır', 'Turkey', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/4788.png'), 
      (4789, 'Kemal Kaynaş Stadı', 'Atatürk Cd. No:10, Kazım Karabekir Paşa Mahallesi', 'Karaman', 'Turkey', 2250, 'grass', 'https://media.api-sports.io/football/venues/4789.png'), 
      (4790, 'Kafkas Üniversitesi Abamüslüm Güven Stadyumu', 'Kafkas Ünv., Şehitler Mahallesi', 'Kars', 'Turkey', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/4790.png'), 
      (4791, 'Kuzeykent Hasan Doğan Spor Tesisleri 1', 'Karadut Sokak No:10, Kuzeykent Mah.', 'Kastamonu', 'Turkey', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/4791.png'), 
      (4792, 'Hasan Doğan Stadyumu', 'Seyhan Caddesi', 'Antalya', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/4792.png'), 
      (4793, 'Kilis 7 Aralık Stadyumu', 'Saraç Mehmet Çavuş Mah.', 'Kilis', 'Turkey', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/4793.png'), 
      (4794, 'Fikret Karabudak Stadyumu', null, 'Kırıkkale', 'Turkey', 5402, 'grass', 'https://media.api-sports.io/football/venues/4794.png'), 
      (4796, 'Alemdağ Stadyumu', '126. Sokak No:17, Alemdağ Mah., Çekmeköy', 'İstanbul', 'Turkey', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/4796.png'), 
      (4797, 'Siirt Atatürk Stadyumu', 'Hükümet Caddesi', 'Siirt', 'Turkey', 5650, 'grass', 'https://media.api-sports.io/football/venues/4797.png'), 
      (4798, 'Soma Atatürk Stadyumu', 'Kurtuluş Mah.', 'Soma', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/4798.png'), 
      (4799, 'Tavşanlı Şehir Stadı', 'Tavşanlı Simav Yolu', 'Tavşanlı', 'Turkey', 4400, 'grass', 'https://media.api-sports.io/football/venues/4799.png'), 
      (4800, 'Yalova Atatürk Stadyumu', 'Yaşar Okuyan Caddesi, Bahçelievler Mah.', 'Yalova', 'Turkey', 8980, 'grass', 'https://media.api-sports.io/football/venues/4800.png'), 
      (4801, 'Malatya Yeşiltepe 3 Nolu Sahası', 'Seyran Mah.', 'Malatya', 'Turkey', 1500, 'grass', 'https://media.api-sports.io/football/venues/4801.png'), 
      (4802, 'Yüksekova İlçe Stadyumu', null, 'Yüksekova', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/4802.png'), 
      (4803, 'Yeşilırmak Stadyumu', 'Stadyum Caddesi, Orta Mah.', 'Çarşamba', 'Turkey', 6000, 'grass', 'https://media.api-sports.io/football/venues/4803.png'), 
      (8392, 'Mersin Stadyumu', null, 'Mersin', 'Turkey', 25534, 'grass', 'https://media.api-sports.io/football/venues/8392.png'), 
      (5378, '13 Şubat Şehir Stadyumu', 'Ali Kemal Caddesi, Atatürk Mah.', 'Erzincan', 'Turkey', 5100, 'grass', 'https://media.api-sports.io/football/venues/5378.png'), 
      (5379, 'Altındağ Stadyumu', 'Oruç Reis Caddesi No:13, Örnek Mah., Altındağ', 'Ankara', 'Turkey', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/5379.png'), 
      (5380, 'Hopa İlçe Stadı', '40. Sokak, Sundura Mah.', 'Hopa', 'Turkey', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/5380.png'), 
      (5381, '16 Mayıs Şehir Stadyumu', '3405. Sokok', 'Batman', 'Turkey', 4900, 'grass', 'https://media.api-sports.io/football/venues/5381.png'), 
      (5382, 'Buca Arena', 'Yavuz Sultan Selim Caddesi, Cumhuriyet Mah., Buca', 'İzmir', 'Turkey', 8810, 'grass', 'https://media.api-sports.io/football/venues/5382.png'), 
      (5383, 'Cizre İlçe Stadı', null, 'Cizre', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/5383.png'), 
      (5384, 'Diyarbakır Atatürk Stadyumu', 'İnaloğlu Caddesi 52, Yenişehir', 'Diyarbakır', 'Turkey', 12963, 'grass', 'https://media.api-sports.io/football/venues/5384.png'), 
      (5385, '18 Temmuz Stadyumu', 'Akar Stadyum Sk. No:7', 'Düzce', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/5385.png'), 
      (5386, 'Erbaa İlçe Stadyumu', 'Gazi Bulvarı', 'Erbaa', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/5386.png'), 
      (12125, 'Esenler Erokspor Stadyumu', '949/1 Çıkmazı No:4, Kemer Mah., Esenler', 'İstanbul', 'Turkey', 16500, 'grass', 'https://media.api-sports.io/football/venues/12125.png'), 
      (5388, 'Şehit Muhammet Oğuz Kılınç Stadı', 'Hürriyet Mah. Stadyum Caddesi', 'Erzin', 'Turkey', 2500, 'grass', 'https://media.api-sports.io/football/venues/5388.png'), 
      (5389, 'Fatsa İlçe Stadyumu', 'Evkaf Mah., Barış Sokak. No:9', 'Fatsa', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/5389.png'), 
      (5390, 'Gölcük İhsaniye Stadı', 'İhsaniye Merkez', 'Gölcük', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/5390.png'), 
      (5391, 'Yıldıztabya Stadyumu', 'Yıldıztabya Mah. Taş Ocağı Dikyol Sok. No:77, Gaziosmanpaşa', 'İstanbul', 'Turkey', 6500, 'grass', 'https://media.api-sports.io/football/venues/5391.png'), 
      (5392, 'Mustafa Fehmi Gerçeker Stadyumu', 'Bursa Caddesi, Canbalı Mah.', 'Karacabey', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/5392.png'), 
      (5393, 'Faruk Çelik Spor Kompleksi', 'Atakent Mah., Karaköprü', 'Şanlıurfa', 'Turkey', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/5393.png'), 
      (2369, 'İzmir Atatürk Stadyumu', 'Şehitler Caddesi, Mersinli Mah.', 'İzmir', 'Turkey', 51295, 'grass', 'https://media.api-sports.io/football/venues/2369.png'), 
      (5394, 'Dr. Fehmi Öncel Stadı', null, 'Tekirova', 'Turkey', 4000, 'grass', 'https://media.api-sports.io/football/venues/5394.png'), 
      (12284, 'Kocaeli Stadyumu', 'Turnaoğlu Caddesi', 'Kocaeli', 'Turkey', 34712, 'grass', 'https://media.api-sports.io/football/venues/12284.png'), 
      (5396, 'İsmet Atlı Stadyumu', 'Andıl Caddesi', 'Kozan', 'Turkey', 2500, 'grass', 'https://media.api-sports.io/football/venues/5396.png'), 
      (5397, 'Kızılcabölük Semt Stadyumu', null, 'Kızılcabölük', 'Turkey', 1557, 'artificial turf', 'https://media.api-sports.io/football/venues/5397.png'), 
      (5398, 'Muğla Atatürk Stadyumu', 'Emirbeyazıt Mah.', 'Muğla', 'Turkey', 6250, 'grass', 'https://media.api-sports.io/football/venues/5398.png'), 
      (5399, 'Nazıllı İlçe Stadyumu', null, 'Nazilli', 'Turkey', 5600, 'grass', 'https://media.api-sports.io/football/venues/5399.png'), 
      (5400, 'Nevşehir Gazi Stadyumu', 'Mustafa Parmaksız Caddesi, Bahçelievler Mah.', 'Nevşehir', 'Turkey', 7503, 'grass', 'https://media.api-sports.io/football/venues/5400.png'), 
      (5401, 'Of İlçe Stadyumu', 'Sanayi Cd. No:71, Sulaklı Mahallesi', 'Of', 'Turkey', 3024, 'grass', 'https://media.api-sports.io/football/venues/5401.png'), 
      (5402, 'Osmaniye 7 Ocak Stadyumu', '14050 Sokak', 'Osmaniye', 'Turkey', 6635, 'grass', 'https://media.api-sports.io/football/venues/5402.png'), 
      (5403, '15 Temmuz Şehitler Stadı', 'Fatih Terim Cd., Payas', 'Hatay', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/5403.png'), 
      (5404, 'Pazar İlçe Stadyumu', null, 'Pazar', 'Turkey', 2442, 'grass', 'https://media.api-sports.io/football/venues/5404.png'), 
      (5405, 'İsmail Ogan Stadyumu', '4177 Sokak, Akçaalan', 'Serik', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/5405.png'), 
      (5408, 'Ziya Altınoğlu Stadyumu', 'Ferhatpaşa Mah. Şehitler Cad., Çatalca', 'İstanbul', 'Turkey', 6150, 'grass', 'https://media.api-sports.io/football/venues/5408.png'), 
      (5409, 'Turgutlu 7 Eylül Stadyumu', 'Yedi Eylül Mahallesi / Eski Manisa Yolu', 'Turgutlu', 'Turkey', 4100, 'grass', 'https://media.api-sports.io/football/venues/5409.png'), 
      (5410, 'Yomra İlçe Stadyumu', null, 'Yomra', 'Turkey', 850, 'grass', 'https://media.api-sports.io/football/venues/5410.png'), 
      (18663, 'Şile Stadı', 'Güloğlu Sitesi No:34, Çavuş Mahallesi', 'Şile', 'Turkey', 4000, 'grass', 'https://media.api-sports.io/football/venues/18663.png'), 
      (5701, 'Florya Metin Oktay Tesisleri', 'Florya', 'İstanbul', 'Turkey', 1000, 'grass', 'https://media.api-sports.io/football/venues/5701.png'), 
      (7406, 'Gebze Alaettin Kurt Stadyumu', 'Yeni Bağdad Caddesi, Güzeller Mah.', 'Gebze', 'Turkey', 8000, 'grass', 'https://media.api-sports.io/football/venues/7406.png'), 
      (7407, 'Alparslan Türkeş Stadyumu', 'Sahil Caddesi', 'Körfez', 'Turkey', 3026, 'grass', 'https://media.api-sports.io/football/venues/7407.png'), 
      (7408, 'Bergama 14 Eylül Stadı', null, 'Bergama', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/7408.png'), 
      (7409, 'Orhangazi Stadı', 'Eski Gemlik Caddesi', 'Orhangazi', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/7409.png'), 
      (7410, 'Çanakkale 18 Mart Stadyumu', 'Atatürk Caddesi', 'Çanakkale', 'Turkey', 12691, 'grass', 'https://media.api-sports.io/football/venues/7410.png'), 
      (7411, 'Beylerbeyi 75. Yıl Stadı', 'Beybostani Sok. No:15, Üsküdar', 'İstanbul', 'Turkey', 5500, 'grass', 'https://media.api-sports.io/football/venues/7411.png'), 
      (7412, 'Radyo Seymen Kartal Stadı', 'Spor Caddesi, Spor Sokak No: 13, Kartal', 'İstanbul', 'Turkey', 7109, 'grass', 'https://media.api-sports.io/football/venues/7412.png'), 
      (7413, 'Kütahya Dumlupınar Stadyumu', 'Fatih Sultan Mehmet Blv.', 'Kütahya', 'Turkey', 11495, 'grass', 'https://media.api-sports.io/football/venues/7413.png'), 
      (7414, 'Evrenseki Stadı', null, 'Evrenseki', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/7414.png'), 
      (7415, 'Namık Kemal Stadyumu', null, 'Tekirdağ', 'Turkey', 5300, 'grass', 'https://media.api-sports.io/football/venues/7415.png'), 
      (7416, 'Adıyaman Atatürk Stadyumu', 'Urfa-Samsat Yolu', 'Adıyaman', 'Turkey', 8596, 'grass', 'https://media.api-sports.io/football/venues/7416.png'), 
      (7417, 'Alibeyköy Stadyumu', 'Namık Kemal Caddesi, Alibeyköy Mah., Eyüp', 'İstanbul', 'Turkey', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/7417.png'), 
      (7418, 'Ahmet Suat Özyazıcı Stadı', 'Üniversite Mh., Ahmet Suat Özyazıcı Caddesi', 'Trabzon', 'Turkey', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/7418.png'), 
      (4795, 'Maltepe Hasan Polat Stadı', 'Istasyon Caddesi / Yalı Mah. Şehit Nedim Özpolat Sokak, Maltepe', 'İstanbul', 'Turkey', 4600, 'grass', 'https://media.api-sports.io/football/venues/4795.png'), 
      (7419, 'Kayseri Atatürk Spor Kompleksi Yan Açık Saha', 'Ahmet Gazi Ayhan', 'Kayseri', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/7419.png'), 
      (7420, 'Kırıkhan İlçe Stadyumu', null, 'Kırıkhan', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/7420.png'), 
      (7421, 'Minareli Çavuş Spor Tesisleri', 'Minareliçavuş Mah. Selvi Caddesi, Nilüfer', 'Bursa', 'Turkey', 2500, 'grass', 'https://media.api-sports.io/football/venues/7421.png'), 
      (7422, 'Doğan Seyfi Atlı Stadyumu', 'Bahçelievler Caddesi No: 88', 'Denizli', 'Turkey', 1600, 'grass', 'https://media.api-sports.io/football/venues/7422.png'), 
      (4687, 'Yavuz Selim Stadı', 'İnönü Mh.', 'Trabzon', 'Turkey', 1820, 'grass', 'https://media.api-sports.io/football/venues/4687.png'), 
      (7423, 'Ordu 19 Eylül Stadyumu', 'Dr. Mürüvvet Sıtkı Caddesi', 'Ordu', 'Turkey', 13658, 'grass', 'https://media.api-sports.io/football/venues/7423.png'), 
      (7424, 'Arsin İlçe Stadı', '206. Sokak', 'Arsin', 'Turkey', 1300, 'grass', 'https://media.api-sports.io/football/venues/7424.png'), 
      (7425, 'Adnan Menderes Stadı', 'Cumhuriyet Mah.', 'Aydın', 'Turkey', 10988, 'grass', 'https://media.api-sports.io/football/venues/7425.png'), 
      (8376, 'Batman 19 Mayıs 2 Nolu Sentetik Saha', 'İpekyolu Caddesi, Çay Mahallesi', 'Batman', 'Turkey', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8376.png'), 
      (8377, 'Altınova Hersekzade Ahmet Paşa Stadı', null, 'Altınova', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/8377.png'), 
      (8378, 'Seyrantepe Şilbe Sentetik Saha', 'Kanal Caddesi', 'Diyarbakır', 'Turkey', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8378.png'), 
      (8379, 'Gaziosmanpaşa Stadı', 'Bağlar Caddesi No:14, Gaziosmanpaşa', 'İstanbul', 'Turkey', 2850, 'grass', 'https://media.api-sports.io/football/venues/8379.png'), 
      (8380, 'Tavas Şehir Stadı', null, 'Tavas', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/8380.png'), 
      (8381, 'Beyçayırı Şehit Vefa Karakurdu', 'Murtaza', 'Karadeniz Ereğli', 'Turkey', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/8381.png'), 
      (8382, 'Karlıova İlçe Stadyumu', null, 'Karlıova', 'Turkey', 1000, null, 'https://media.api-sports.io/football/venues/8382.png'), 
      (8383, 'Mut İlçe Stadı', 'Kayseri Sk. 6a, Kültür Mahallesi', 'Mut', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/8383.png'), 
      (8384, '80. Yıl Cumhuriyet Şehir Stadyumu', 'Karagöl', 'Ardahan', 'Turkey', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/8384.png'), 
      (8385, 'Sinop Şehir Stadyumu', 'Stad Yolu', 'Sinop', 'Turkey', 2500, 'grass', 'https://media.api-sports.io/football/venues/8385.png'), 
      (8386, 'Amasya 12 Haziran Stadyumu', 'Hızırpaşa', 'Amasya', 'Turkey', 12000, 'grass', 'https://media.api-sports.io/football/venues/8386.png'), 
      (8387, 'Karaçayır 3 Nolu Sahası', 'Karaçayır Mah.', 'Bolu', 'Turkey', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8387.png'), 
      (8388, 'Çayırovaspor Stadı', 'Nazım Hikmet Caddesi, Akse Mah.', 'Çayırova', 'Turkey', 4000, 'grass', 'https://media.api-sports.io/football/venues/8388.png'), 
      (8389, 'Muhammed Hanefi Dilmaç Çavuşbaşı Spor Tesisleri', 'Yunus Emre Caddesi No:31, Çiftlik Mah., Beykoz', 'İstanbul', 'Turkey', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/8389.png'), 
      (8390, 'Çerkezköy Mustafa Uğraş Stadı', null, 'Çerkezköy', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/8390.png'), 
      (8391, 'Ödemiş Saraçoğlu Stadı', 'Atatürk Mah.', 'Ödemiş', 'Turkey', 7000, 'artificial turf', 'https://media.api-sports.io/football/venues/8391.png'), 
      (8393, 'Mimar Yahya Baş Stadı', 'Çinçindere Caddesi, Güngören', 'İstanbul', 'Turkey', 15242, 'grass', 'https://media.api-sports.io/football/venues/8393.png'), 
      (8394, 'İskenderun 5 Temmuz Stadı', 'Fatih Sultan Mehmen Caddesi', 'İskenderun', 'Turkey', 12390, 'grass', 'https://media.api-sports.io/football/venues/8394.png'), 
      (4671, 'Çankırı Atatürk Stadyumu', 'Refik Saydam Caddesi', 'Çankırı', 'Turkey', 5109, 'grass', 'https://media.api-sports.io/football/venues/4671.png'), 
      (8395, 'Bağlum Belediye Stadyumu', 'Bağlum Bulvarı, Pursaklar', 'Ankara', 'Turkey', 16000, 'grass', 'https://media.api-sports.io/football/venues/8395.png'), 
      (8397, '21 Kasım Şehir Stadyumu', 'Yeni Yol Caddesi', 'Mardin', 'Turkey', 6600, 'grass', 'https://media.api-sports.io/football/venues/8397.png'), 
      (8398, 'Muş Şehir Stadı', 'Zafer', 'Muş', 'Turkey', 2250, 'grass', 'https://media.api-sports.io/football/venues/8398.png'), 
      (8399, 'Tatvan İlçe Sahası', null, 'Tatvan', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/8399.png'), 
      (8400, 'Arakli Ilçe Stadi', null, null, 'Turkey', 1364, 'grass', 'https://media.api-sports.io/football/venues/8400.png'), 
      (8401, 'Ayancık Gazi Stadı', 'Cahit Övet Caddesi, Yalı Mah.', 'Ayancık', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/8401.png'), 
      (8402, 'Eğirdir İlçe Stadı', 'Isparta Konya Kolu, Bağlar Mah.', 'Eğirdir', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/8402.png'), 
      (8403, 'Merzan Şehir Stadı', 'Pehlivan', 'Hakkâri', 'Turkey', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/8403.png'), 
      (8404, 'Kurtalan İlçe Stadı', 'Tekel Mah.', 'Kurtalan', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/8404.png'), 
      (8405, 'Sarayönü Stadı', 'Şube Caddesi', 'Sarayönü', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/8405.png'), 
      (8406, 'Cebeci Spor Kompleksi', 'Sultangazi, Uğur Mumcu Mah., Gaziosmanpaşa', 'İstanbul', 'Turkey', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/8406.png'), 
      (8407, 'Arhavi İlçe Stadı', null, 'Arhavi', 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/8407.png'), 
      (8408, 'Hüsnü Uğural Stadyumu', null, 'Ayvalık', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/8408.png'), 
      (8409, 'Sandıklı ilçe Stadyumu', null, 'Sandıklı', 'Turkey', 1400, 'grass', 'https://media.api-sports.io/football/venues/8409.png'), 
      (8410, 'Korgeneral Ahmet Başyurt Stadyumu', 'Ahmet Başyurt Mah. Stad Caddesi', 'Zara', 'Turkey', 500, 'grass', 'https://media.api-sports.io/football/venues/8410.png'), 
      (8411, 'Çine Yüksel Yalova Stadyumu', 'Yeni Adnan Menderes Bulvarı', 'Çine', 'Turkey', 5000, 'grass', 'https://media.api-sports.io/football/venues/8411.png'), 
      (8412, 'Ulucak Stadı', 'Turgut Özal Blv, Ulucak İstiklal Mh.', 'Ulucak Cumhuriye', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/8412.png'), 
      (8413, 'Beyköy Stadı', 'Değirmenbaşı', 'Beyköy', 'Turkey', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/8413.png'), 
      (8414, 'Kars Sehir Stadyumu', null, null, 'Turkey', 4500, 'grass', 'https://media.api-sports.io/football/venues/8414.png'), 
      (8415, 'Sorgun İlçe Stadı', null, 'Sorgun', 'Turkey', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/8415.png'), 
      (8416, 'Fatih Stadyumu', 'Akçaabat Caddesi', 'Akçaabat', 'Turkey', 6238, 'grass', 'https://media.api-sports.io/football/venues/8416.png'), 
      (8417, 'Bafra Şehir Stadyumu', null, 'Bafra', 'Turkey', 4000, 'grass', 'https://media.api-sports.io/football/venues/8417.png'), 
      (8418, 'Isparta Atatürk Stadyumu', null, null, 'Turkey', 10000, 'grass', 'https://media.api-sports.io/football/venues/8418.png'), 
      (8420, 'Ünye İlçe Stadyumu', 'Büyük Cami Caddesi, Ünye', 'Ordu', 'Turkey', 9909, 'grass', 'https://media.api-sports.io/football/venues/8420.png'), 
      (8428, 'Ayfon Atatürk Stadi', null, null, 'Turkey', 10000, 'grass', 'https://media.api-sports.io/football/venues/8428.png'), 
      (8423, 'Vakfikebir Ilçe Stadyumu', null, null, 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/8423.png'), 
      (8421, 'Bursa Merinos Stadyumu', null, null, 'Turkey', 3900, 'artificial turf', 'https://media.api-sports.io/football/venues/8421.png'), 
      (8422, 'Muhsin Yazıcıoğlu Spor Tesisleri', 'Erzican-Erzurum Çevre Yolu', 'Sivas', 'Turkey', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/8422.png'), 
      (4804, 'Yenimahalle Hasan Dogan Stadyumu', null, null, 'Turkey', 2000, 'grass', 'https://media.api-sports.io/football/venues/4804.png'), 
      (8424, 'Babaeski 100. Yıl Stadyumu', null, 'Babaeski', 'Turkey', 3000, 'grass', 'https://media.api-sports.io/football/venues/8424.png'), 
      (8425, 'Seyrantepe Spor Kompleksi Stadyumu 2', null, null, 'Turkey', 500, 'artificial turf', 'https://media.api-sports.io/football/venues/8425.png'), 
      (8426, 'Metin Oktay Stadyumu', null, null, 'Turkey', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/8426.png'), 
      (8427, 'Iskenderun 5 Temmuz Stadi', null, null, 'Turkey', 12390, 'grass', 'https://media.api-sports.io/football/venues/8427.png'), 
      (8429, 'Bozok Stadyumu', null, null, 'Turkey', 8260, 'grass', 'https://media.api-sports.io/football/venues/8429.png'), 
      (10798, 'Ceyhan İlçe Stadı', 'Altıocak Mahallesi', 'Ceyhan', 'Turkey', 3930, 'grass', 'https://media.api-sports.io/football/venues/10798.png'), 
      (11026, 'Bolluca Stadı', 'Betül Sk.', 'Arnavutköy', 'Turkey', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11026.png'), 
      (12124, 'Milli Egemenlik Stadyumu', 'Ahmet Tokuş Bulvarı', 'Alanya', 'Turkey', 3750, 'grass', 'https://media.api-sports.io/football/venues/12124.png'), 
      (12622, 'Makü İstiklal Stadı', 'Yakaköy', 'Burdur', 'Turkey', 10000, 'grass', 'https://media.api-sports.io/football/venues/12622.png'), 
      (18664, 'Kuşadası Belediyesi Özer Türk Stadyumu', 'Kadinlar Denizi Mahallesi', 'Kusadasi', 'Turkey', 8000, 'grass', 'https://media.api-sports.io/football/venues/18664.png'), 
      (18709, 'Beykoz Stadı', 'İbrahım Kelle Sokak No:38, Beykoz', 'İstanbul', 'Turkey', 3500, 'grass', 'https://media.api-sports.io/football/venues/18709.png');