INSERT INTO venues (id, name, address, city, country, capacity, surface, image) 
VALUES (910, 'Stadio Olimpico', 'Viale dei Gladiatori, 2 / Via del Foro Italico', 'Roma', 'Italy', 68530, 'grass', 'https://media.api-sports.io/football/venues/910.png'), 
      (935, 'MAPEI Stadium - Città del Tricolore', 'Piazza Azzuri d&apos;Italia, 1', 'Reggio nell&apos;Emilia', 'Italy', 23717, 'grass', 'https://media.api-sports.io/football/venues/935.png'), 
      (907, 'Stadio Giuseppe Meazza', 'Via Piccolomini 5', 'Milano', 'Italy', 80018, 'grass', 'https://media.api-sports.io/football/venues/907.png'), 
      (12275, 'Unipol Domus', 'Via Raimondo Carta Raspi', 'Cagliari', 'Italy', 16416, 'grass', 'https://media.api-sports.io/football/venues/12275.png'), 
      (890, 'Stadio Marc''Antonio Bentegodi', 'Piazzale Olimpia', 'Verona', 'Italy', 39211, 'grass', 'https://media.api-sports.io/football/venues/890.png'), 
      (11904, 'Stadio Diego Armando Maradona', 'Pizzale Vincenzo Tecchio', 'Napoli', 'Italy', 60240, 'grass', 'https://media.api-sports.io/football/venues/11904.png'), 
      (938, 'Stadio Paolo Mazza', 'Corso Piave, 28', 'Ferrara', 'Italy', 16134, 'grass', 'https://media.api-sports.io/football/venues/938.png'), 
      (928, 'Dacia Arena', 'Piazza le Repubblica Argentina, 3', 'Udine', 'Italy', 25952, 'grass', 'https://media.api-sports.io/football/venues/928.png'), 
      (905, 'Stadio Comunale Luigi Ferraris', 'Via Giovanni De Prà, 1', 'Genova', 'Italy', 36703, 'grass', 'https://media.api-sports.io/football/venues/905.png'), 
      (909, 'Allianz Stadium', 'Strada Comunale di Altessano 131', 'Torino', 'Italy', 45666, 'grass', 'https://media.api-sports.io/football/venues/909.png'), 
      (879, 'Gewiss Stadium', 'Viale Giulio Cesare 18', 'Bergamo', 'Italy', 21300, 'grass', 'https://media.api-sports.io/football/venues/879.png'), 
      (881, 'Stadio Renato Dall''Ara', 'Via Andrea Costa, 174', 'Bologna', 'Italy', 39279, 'grass', 'https://media.api-sports.io/football/venues/881.png'), 
      (895, 'Stadio Ezio Scida', 'Via Cutro', 'Crotone', 'Italy', 16108, 'grass', 'https://media.api-sports.io/football/venues/895.png'), 
      (902, 'Stadio Artemio Franchi', 'Viale Manfredo Fanti 14', 'Firenze', 'Italy', 43147, 'grass', 'https://media.api-sports.io/football/venues/902.png'), 
      (943, 'Stadio Olimpico Grande Torino', 'Corso Sebastopoli 123, Santa Rita', 'Torino', 'Italy', 27958, 'grass', 'https://media.api-sports.io/football/venues/943.png'), 
      (880, 'Stadio Ciro Vigorito', 'Piazzale degli Atleti', 'Benevento', 'Italy', 17554, 'grass', 'https://media.api-sports.io/football/venues/880.png'), 
      (876, 'Stadio Cino e Lillo Del Duca', 'Via delle Zeppelle, 1', 'Ascoli Piceno', 'Italy', 20853, 'grass', 'https://media.api-sports.io/football/venues/876.png'), 
      (2763, 'Stadio Comunale San Nicola', 'Strada Provinciale Modugno-Carbonara', 'Bari', 'Italy', 58270, 'grass', 'https://media.api-sports.io/football/venues/2763.png'), 
      (2758, 'Orogel Stadium-Dino Manuzzi', 'Via dello Stadio, 124', 'Cesena', 'Italy', 23860, 'artificial turf', 'https://media.api-sports.io/football/venues/2758.png'), 
      (891, 'Stadio Pier Cesare Tombolato', 'Viale dello Sport, 7', 'Cittadella', 'Italy', 7623, 'grass', 'https://media.api-sports.io/football/venues/891.png'), 
      (896, 'Stadio Carlo Castellani', 'Viale delle Olimpiadi', 'Empoli', 'Italy', 16284, 'grass', 'https://media.api-sports.io/football/venues/896.png'), 
      (904, 'Stadio Benito Stirpe', 'Viale Olimpia', 'Frosinone', 'Italy', 16310, 'grass', 'https://media.api-sports.io/football/venues/904.png'), 
      (917, 'Stadio Comunale Silvio Piola', 'Viale Kennedy, 8', 'Novara', 'Italy', 17875, 'artificial turf', 'https://media.api-sports.io/football/venues/917.png'), 
      (933, 'Stadio Arechi', 'Via Salvador Allende', 'Salerno', 'Italy', 37245, 'grass', 'https://media.api-sports.io/football/venues/933.png'), 
      (939, 'Stadio Alberto Picco', 'Via Nicolò Fieschi, 18', 'La Spezia', 'Italy', 11512, 'artificial turf', 'https://media.api-sports.io/football/venues/939.png'), 
      (942, 'Stadio Libero Liberati', 'Viale dello Stadio', 'Terni', 'Italy', 17460, 'grass', 'https://media.api-sports.io/football/venues/942.png'), 
      (948, 'Stadio Pierluigi Penzo', 'Isola di Sant&apos;Elena', 'Venezia', 'Italy', 11150, 'grass', 'https://media.api-sports.io/football/venues/948.png'), 
      (882, 'Stadio Mario Rigamonti', 'Via Giovanni Novagani, 8', 'Brescia', 'Italy', 27547, 'grass', 'https://media.api-sports.io/football/venues/882.png'), 
      (884, 'Stadio Sandro Cabassi', 'Via Carlo Marx, 26', 'Carpi', 'Italy', 5584, 'grass', 'https://media.api-sports.io/football/venues/884.png'), 
      (894, 'Stadio Giovanni Zini', 'Via Persico, 19', 'Cremona', 'Italy', 20034, 'grass', 'https://media.api-sports.io/football/venues/894.png'), 
      (903, 'Stadio Comunale Pino Zaccheria', 'Via Vincenzo Gioberti', 'Foggia', 'Italy', 25085, 'grass', 'https://media.api-sports.io/football/venues/903.png'), 
      (920, 'Stadio Renzo Barbera', 'Viale del Fante, 11', 'Palermo', 'Italy', 36349, 'grass', 'https://media.api-sports.io/football/venues/920.png'), 
      (921, 'Stadio Ennio Tardini', 'Via Partigiani d&apos;Italia, 1', 'Parma', 'Italy', 21473, 'grass', 'https://media.api-sports.io/football/venues/921.png'), 
      (922, 'Stadio Renato Curi', 'Via Pietro Conti', 'Perugia', 'Italy', 23625, 'grass', 'https://media.api-sports.io/football/venues/922.png'), 
      (923, 'Stadio Adriatico-Giovanni Cornacchia', 'Via Pepe', 'Pescara', 'Italy', 20476, 'grass', 'https://media.api-sports.io/football/venues/923.png'), 
      (930, 'Stadio Silvio Piola', 'Via Massaua, 5', 'Vercelli', 'Italy', 5500, 'artificial turf', 'https://media.api-sports.io/football/venues/930.png'), 
      (872, 'Stadio Comunale Chiavari', 'Via Aldo Gastaldi, 22', 'Chiavari', 'Italy', 6113, 'artificial turf', 'https://media.api-sports.io/football/venues/872.png'), 
      (2756, 'Stadio Partenio-Adriano Lombardi', 'Contrada Zoccolari, 1', 'Avellino', 'Italy', 26308, 'grass', 'https://media.api-sports.io/football/venues/2756.png'), 
      (925, 'Arena Garibaldi - Stadio Romeo Anconetani', 'Via di Gello, 25', 'Pisa', 'Italy', 17500, 'grass', 'https://media.api-sports.io/football/venues/925.png'), 
      (878, 'Stadio Polisportivo Provinciale', 'Via Giuseppe Cesarò, Casa Santa di Erice', 'Trapani', 'Italy', 7787, 'grass', 'https://media.api-sports.io/football/venues/878.png'), 
      (2768, 'Stadio Comunale Domenico Francioni', 'Piazzale Prampolini 4', 'Latina', 'Italy', 11200, 'grass', 'https://media.api-sports.io/football/venues/2768.png'), 
      (12087, 'Stadio Guido Teghil', 'Via della Vigna, 19', 'Lignano Sabbiadoro', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/12087.png'), 
      (908, 'Stadio Comunale Romeo Menti', 'Via G. Cosenza, 283', 'Castellammare di Stabia', 'Italy', 7642, 'artificial turf', 'https://media.api-sports.io/football/venues/908.png'), 
      (893, 'Stadio San Vito-Luigi Marulla', 'Via degli Stadio', 'Cosenza', 'Italy', 24209, 'grass', 'https://media.api-sports.io/football/venues/893.png'), 
      (873, 'Stadio Comunale', 'Via Milano 23', 'Gorgonzola', 'Italy', 3766, 'grass', 'https://media.api-sports.io/football/venues/873.png'), 
      (906, 'Stadio Pietro Barbetti', 'Via Parruccini', 'Gubbio', 'Italy', 4939, 'grass', 'https://media.api-sports.io/football/venues/906.png'), 
      (911, 'Stadio Comunale Via del Mare', 'Viale dello Stadio', 'Lecce', 'Italy', 33876, 'grass', 'https://media.api-sports.io/football/venues/911.png'), 
      (912, 'Stadio Armando Picchi', 'Piazzale Montello 14', 'Livorno', 'Italy', 19238, 'grass', 'https://media.api-sports.io/football/venues/912.png'), 
      (898, 'Stadio XXI Settembre-Franco Salerno', 'Via Guiseppe Saragat, 46', 'Matera', 'Italy', 7490, 'grass', 'https://media.api-sports.io/football/venues/898.png'), 
      (2764, 'Stadio Comunale Euganeo', 'Via Nereo Rocco, 60', 'Padova', 'Italy', 32420, 'grass', 'https://media.api-sports.io/football/venues/2764.png'), 
      (934, 'Stadio Riviera delle Palme', 'Viale Dello Sport 62', 'San Benedetto del Tronto', 'Italy', 22000, 'grass', 'https://media.api-sports.io/football/venues/934.png'), 
      (924, 'Stadio Leonardo Garilli', 'Via Egidio Gorra, 25', 'Piacenza', 'Italy', 21668, 'grass', 'https://media.api-sports.io/football/venues/924.png'), 
      (1856, 'Stadio Giovanni Paolo II', null, 'Francavilla Fontana', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/1856.png'), 
      (2761, 'Centro Sportivo Vittorio Bachelet', 'Via Vitellia, 50', 'Roma', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/2761.png'), 
      (871, 'Stadio Città di Meda', 'Via Privata Icmesa', 'Meda', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/871.png'), 
      (875, 'Stadio Città di Arezzo', 'Viale Antonio Gramsci', 'Arezzo', 'Italy', 13128, 'grass', 'https://media.api-sports.io/football/venues/875.png'), 
      (944, 'Stadio Nereo Rocco', 'Via dei Macelli, 5', 'Trieste', 'Italy', 32454, 'grass', 'https://media.api-sports.io/football/venues/944.png'), 
      (874, 'Stadio Giuseppe Moccagatta', 'Via Spalto Rovereto, 28', 'Alessandria', 'Italy', 7694, 'grass', 'https://media.api-sports.io/football/venues/874.png'), 
      (2757, 'Stadio Rino Mercante', 'Via Piave, 27', 'Bassano del Grappa', 'Italy', 2952, 'grass', 'https://media.api-sports.io/football/venues/2757.png'), 
      (2765, 'Stadio Marcello Martoni', 'Via Dello Sport', 'Monterosi', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/2765.png'), 
      (2766, 'Stadio Comunale', 'Viale Giuseppe Mazzini', 'Mazzano', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/2766.png'), 
      (900, 'Stadio Lino Turina', 'Via Enzo Ferrari 3, Località Due Pin', 'Salò', 'Italy', 2364, 'grass', 'https://media.api-sports.io/football/venues/900.png'), 
      (886, 'Stadio Comunale Alberto Pinto', 'Viale Medaglie d&apos;Oro', 'Caserta', 'Italy', 6017, 'grass', 'https://media.api-sports.io/football/venues/886.png'), 
      (1804, 'Stadio Comunale Marco Lorenzon', 'Via Fratelli Bandiera', 'Rende', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/1804.png'), 
      (2762, 'Stadio Franco Ossola', 'Via Bolchini, Masnago', 'Varese', 'Italy', 8146, 'grass', 'https://media.api-sports.io/football/venues/2762.png'), 
      (1805, 'Centro Sportivo Giovanni Paolo II', 'Via Guido Rossa', 'Matelica', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/1805.png'), 
      (913, 'Stadio Porta Elisa', 'Via dello Stadio', 'Lucca', 'Italy', 7386, 'grass', 'https://media.api-sports.io/football/venues/913.png'), 
      (919, 'Stadio Marcello Torre', 'Via Cesare Sportelli', 'Pagani', 'Italy', 5093, 'grass', 'https://media.api-sports.io/football/venues/919.png'), 
      (2759, 'Stadio degli Oliveti', 'Via dello Sport', 'Massa', 'Italy', 8900, 'grass', 'https://media.api-sports.io/football/venues/2759.png'), 
      (1803, 'Stadio Romeo Galli', 'via Romeo Galli 1', 'Imola', 'Italy', 3809, 'grass', 'https://media.api-sports.io/football/venues/1803.png'), 
      (937, 'Stadio Nicola de Simone', 'Piazza Luigi Leone Cuella, 1', 'Siracusa', 'Italy', 5946, 'grass', 'https://media.api-sports.io/football/venues/937.png'), 
      (892, 'Stadio Giuseppe Sinigaglia', 'Via Giuseppe Sinigaglia, 3', 'Como', 'Italy', 13602, 'grass', 'https://media.api-sports.io/football/venues/892.png'), 
      (2772, 'Stadio Ferrucio', 'Via Avogadro', 'Seregno', 'Italy', 3700, 'grass', 'https://media.api-sports.io/football/venues/2772.png'), 
      (2773, 'Stadio del Conero', 'Frazione Varano, Località Passo Varano', 'Ancona', 'Italy', 23983, 'grass', 'https://media.api-sports.io/football/venues/2773.png'), 
      (2770, 'Stadio Comunale Franco Scoglio', 'Via Comunale, San Filippo', 'Messina', 'Italy', 37895, 'grass', 'https://media.api-sports.io/football/venues/2770.png'), 
      (2771, 'Stadio Alberto Braglia', 'Viale Monte Kosica, 128/134', 'Modena', 'Italy', 21151, 'grass', 'https://media.api-sports.io/football/venues/2771.png'), 
      (2769, 'Stadio Helvia Recina', 'Via dei Velini, 50', 'Macerata', 'Italy', 9000, 'grass', 'https://media.api-sports.io/football/venues/2769.png'), 
      (940, 'Stadio Marco Druso', 'Viale Trieste / Trieststraße 29', 'Bozen', 'Italy', 5500, 'grass', 'https://media.api-sports.io/football/venues/940.png'), 
      (12086, 'U-Power Stadium', 'Via Franco Tognini', 'Monza', 'Italy', 18568, 'grass', 'https://media.api-sports.io/football/venues/12086.png'), 
      (887, 'Stadio Angelo Massimino', 'Piazza Vincenzo Spedini', 'Catania', 'Italy', 20104, 'grass', 'https://media.api-sports.io/football/venues/887.png'), 
      (885, 'Stadio dei Marmi', 'Piazza Vittorio Veneto, 8', 'Carrara', 'Italy', 4975, 'grass', 'https://media.api-sports.io/football/venues/885.png'), 
      (914, 'Stadio Vito Simone Veneziani', 'Via Palmiro Togliatti, 23', 'Monopoli', 'Italy', 6880, 'grass', 'https://media.api-sports.io/football/venues/914.png'), 
      (936, 'Stadio Comunale Artemio Franchi - Montepaschi Arena', 'Via Mille, 3', 'Siena', 'Italy', 15373, 'grass', 'https://media.api-sports.io/football/venues/936.png'), 
      (2767, 'Stadio Romeo Menti', 'Via Schio, 21', 'Vicenza', 'Italy', 20920, 'grass', 'https://media.api-sports.io/football/venues/2767.png'), 
      (1849, 'Stadio Enrico Rocchi', 'Via della Palazzina', 'Viterbo', 'Italy', 5526, 'grass', 'https://media.api-sports.io/football/venues/1849.png'), 
      (1855, 'Stadio Pio XII', 'Via Orti Pompei', 'Albano Laziale', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/1855.png'), 
      (1832, 'Stadio Comunale Alfredo Viviani', 'Viale Guglielmo Marconi', 'Potenza', 'Italy', 5500, 'grass', 'https://media.api-sports.io/football/venues/1832.png'), 
      (1914, 'Centro Sportivo Comunale Rezzato', 'Via Milano 14', 'Rezzato', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/1914.png'), 
      (926, 'Stadio Marcello Melani', 'Via dello Stadio 8', 'Pistoia', 'Italy', 13195, 'grass', 'https://media.api-sports.io/football/venues/926.png'), 
      (1892, 'Stadio Comunale Angelino Nobile', 'Via dello Stadio 37', 'Lentini', 'Italy', 3500, 'grass', 'https://media.api-sports.io/football/venues/1892.png'), 
      (945, 'Stadio Ettore Mannucci', 'Via Vittorio Veneto', 'Pontedera', 'Italy', 4014, 'grass', 'https://media.api-sports.io/football/venues/945.png'), 
      (1854, 'Centro Sportivo Il Gabbiano', 'Via Olmo, 16', 'Campodarsego', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/1854.png'), 
      (946, 'Stadio Comunale Luigi Cichero', 'Via Giuseppe Mazzini, 15', 'Sanremo', 'Italy', 4850, 'grass', 'https://media.api-sports.io/football/venues/946.png'), 
      (877, 'Stadio Piero de Paoli', 'Strada San Silvestro', 'Chieri', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/877.png'), 
      (6523, 'Campo Centrale Ado Nelli', 'Via Oglio, 13', 'Montemurlo', 'Italy', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6523.png'), 
      (949, 'Stadio Luigi Razza', 'Via Piazza d&apos;Armi', 'Vibo Valentia', 'Italy', 6000, 'grass', 'https://media.api-sports.io/football/venues/949.png'), 
      (897, 'Stadio Raffaele Mancini', 'Via Metauro', 'Fano', 'Italy', 8800, 'grass', 'https://media.api-sports.io/football/venues/897.png'), 
      (941, 'Stadio Gaetano Bonolis', 'Viale Amerigo Vespucci, Piano d&apos;Accio', 'Teramo', 'Italy', 8840, 'grass', 'https://media.api-sports.io/football/venues/941.png'), 
      (7328, 'Stadio Esseneto', 'Via Petrarca', 'Agrigento', 'Italy', 12000, 'grass', 'https://media.api-sports.io/football/venues/7328.png'), 
      (7322, 'Stadio Montefiore', 'Via dell’Arenatura 27', 'Rocca Priora', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/7322.png'), 
      (6589, 'Stadio Leporaia', 'Via N. Sauro, Ponte a Egola', 'San Miniato', 'Italy', 600, 'grass', 'https://media.api-sports.io/football/venues/6589.png'), 
      (888, 'Stadio Nicola Ceravolo', 'Via Francesco Paglia', 'Catanzaro', 'Italy', 14650, 'grass', 'https://media.api-sports.io/football/venues/888.png'), 
      (6575, 'Stadio Tullo Morgagni', 'Viale Roma 128/B', 'Forlì', 'Italy', 3466, 'grass', 'https://media.api-sports.io/football/venues/6575.png'), 
      (7324, 'Nuovo Stadio Comunale', 'Via Magante, 14', 'Lumezzane', 'Italy', 4004, 'grass', 'https://media.api-sports.io/football/venues/7324.png'), 
      (7327, 'Stadio Arturo Valerio', 'Contrada Sant&apos;Abbruzzese 12', 'Melfi', 'Italy', 4100, 'grass', 'https://media.api-sports.io/football/venues/7327.png'), 
      (7326, 'Stadio Domenico Purificato', 'Via Arnale Rosso', 'Fondi', 'Italy', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/7326.png'), 
      (2760, 'Stadio Oreste Granillo', 'Via Galileo Galilei', 'Reggio Calabria', 'Italy', 25314, 'grass', 'https://media.api-sports.io/football/venues/2760.png'), 
      (4185, 'Stadio Danilo Martelli', 'Viale Te, 7-9', 'Mantova', 'Italy', 14854, 'grass', 'https://media.api-sports.io/football/venues/4185.png'), 
      (7325, 'Stadio Valentino Mazzola', 'Via della Resistenza, 5', 'Santarcangelo di Romagna', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/7325.png'), 
      (6632, 'Stadio Degli Ulivi', 'Piazzale della Repubblica', 'Andria', 'Italy', 9141, 'grass', 'https://media.api-sports.io/football/venues/6632.png'), 
      (6635, 'Stadio Comunale Erasmo Iacovone', 'Via Lago di Como, Rione Salinella', 'Taranto', 'Italy', 26384, 'grass', 'https://media.api-sports.io/football/venues/6635.png'), 
      (918, 'Stadio Bruno Nespoli', 'Via Ungheria, 9', 'Olbia', 'Italy', 3200, 'grass', 'https://media.api-sports.io/football/venues/918.png'), 
      (7323, 'Stadio Casal del Marmo', 'Via Giuseppe Barellai', 'Roma', 'Italy', 2250, 'grass', 'https://media.api-sports.io/football/venues/7323.png'), 
      (6588, 'Stadio Romeo Malservisi', 'Via Rodolfo Morandi, 2', 'Bagno di Gavorrano', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6588.png'), 
      (870, 'Stadio Fratelli Paschiero', 'Corso Monviso 21', 'Cuneo', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/870.png'), 
      (901, 'Stadio Bruno Recchioni', 'Viale Trento, 13', 'Fermo', 'Italy', 11150, 'grass', 'https://media.api-sports.io/football/venues/901.png'), 
      (927, 'Stadio Biagio Pirina', 'Viale Paulo Delton', 'Arzachena', 'Italy', 3100, 'grass', 'https://media.api-sports.io/football/venues/927.png'), 
      (1766, 'Stadio Gustavo Ventura', 'Via Carrara Salsello, 30', 'Bisceglie', 'Italy', 8000, 'grass', 'https://media.api-sports.io/football/venues/1766.png'), 
      (6557, 'Stadio Francesco Baracca', 'Via Francesco Baracca, 19', 'Mestre', 'Italy', 8074, 'grass', 'https://media.api-sports.io/football/venues/6557.png'), 
      (931, 'Stadio Comunale Bruno Benelli', 'Via Punta Stilo, 29', 'Ravenna', 'Italy', 12020, 'grass', 'https://media.api-sports.io/football/venues/931.png'), 
      (929, 'Stadio Carlo Speroni', 'Via Cà Bianca, 42', 'Busto Arsizio', 'Italy', 4504, 'grass', 'https://media.api-sports.io/football/venues/929.png'), 
      (947, 'Stadio Comunale Gavagnin-Nocini', 'Via Montorio 112', 'Verona', 'Italy', 1421, 'grass', 'https://media.api-sports.io/football/venues/947.png'), 
      (950, 'Stadio Tonino Benelli', 'Via dei Campo Sportivo', 'Pesaro', 'Italy', 4898, 'grass', 'https://media.api-sports.io/football/venues/950.png'), 
      (932, 'Stadio Romeo Neri', 'Viale 9 Febbraio 1849', 'Rimini', 'Italy', 9798, 'grass', 'https://media.api-sports.io/football/venues/932.png'), 
      (899, 'Stadio Centro d''Italia - Manlio Scopigno', 'Piazza Veterani dello Sport', 'Rieti', 'Italy', 9980, 'grass', 'https://media.api-sports.io/football/venues/899.png'), 
      (889, 'Stadio Comunale Simonetta Lamberti', 'Corso Mazzini, 1', 'Cava de&apos; Tirreni', 'Italy', 15200, 'grass', 'https://media.api-sports.io/football/venues/889.png'), 
      (1740, 'Stadio Alfredo D''Albertas', 'Via Madonna Luzzara', 'Gozzano', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/1740.png'), 
      (4186, 'Stadio Luigi Bettinazzi', 'Via Bettinazzi 1', 'Adria', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/4186.png'), 
      (4187, 'Stadio Comunale Vito Curlo', null, 'Fasano', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/4187.png'), 
      (4188, 'Stadio Dossenina', 'Viale Pavia, 24', 'Lodi', 'Italy', 2184, 'grass', 'https://media.api-sports.io/football/venues/4188.png'), 
      (4189, 'Campo Comunale Lixius Lanusei', 'Via Circonvallazione Sud, Lixius', 'Lanusei', 'Italy', 600, 'grass', 'https://media.api-sports.io/football/venues/4189.png'), 
      (4190, 'Stadio Comunale', null, 'Ponsacco', 'Italy', 3220, 'grass', 'https://media.api-sports.io/football/venues/4190.png'), 
      (4191, 'Stadio Amerigo Liguori', 'Viale Ungheria, 54', 'Torre del Greco', 'Italy', 5300, 'grass', 'https://media.api-sports.io/football/venues/4191.png'), 
      (12420, 'Stadio Tommaso Dal Molin', 'Via Consolini', 'Arzignano', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/12420.png'), 
      (4705, 'Stadio Rigamonti Ceppi', 'Via Don Pozzi, 6', 'Lecco', 'Italy', 4997, 'grass', 'https://media.api-sports.io/football/venues/4705.png'), 
      (4706, 'Stadio Giuseppe Voltini', 'Viale Alcide de Gasperi, 67', 'Crema', 'Italy', 4095, 'grass', 'https://media.api-sports.io/football/venues/4706.png'), 
      (12423, 'Stadio Comunale', 'Via Fratelli Rosselli 1', 'Piancastagnaio', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12423.png'), 
      (5702, 'Campo Chisola', 'Via del Castello, 3', 'Vinovo', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/5702.png'), 
      (5703, 'Centro Sportivo Sant''Antimo', 'Via G. Marconi, 117', 'Sant&apos;Antimo', 'Italy', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/5703.png'), 
      (6524, 'Stadio Comunale', 'Via Marconi', 'Borgosesia', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/6524.png'), 
      (6525, 'Stadio Comunale Attilio Bravi', 'Via Madonna dei Fiori, 91', 'Bra', 'Italy', 1230, 'grass', 'https://media.api-sports.io/football/venues/6525.png'), 
      (6526, 'Campo Sportivo Comunale', 'Corso della Vittoria 698', 'Caronno Pertusella', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6526.png'), 
      (6527, 'Stadio Natale Palli', 'Via Bruno Buozzi', 'Casale Monferrato', 'Italy', 6035, 'grass', 'https://media.api-sports.io/football/venues/6527.png'), 
      (6528, 'Stadio Miro Luperi', 'Via Villefranche de Rouergue 1', 'Sarzana', 'Italy', 4500, 'grass', 'https://media.api-sports.io/football/venues/6528.png'), 
      (6529, 'Stadio Angelo Pochissimo', 'Corso Trento, 53', 'Fossano', 'Italy', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6529.png'), 
      (12421, 'Stadio delle Terme', 'Via Lima', 'Bagni di Lucca', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/12421.png'), 
      (6531, 'Stadio Edoardo Riboli', 'Via Edoardo Riboli', 'Lavagna', 'Italy', 800, 'artificial turf', 'https://media.api-sports.io/football/venues/6531.png'), 
      (6532, 'Campo Sportivo Ligorna', 'Via Solimano, Serino', 'Genova', 'Italy', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6532.png'), 
      (6533, 'Stadio Comunale Carlo Necchi', 'Via XX Settembre 91', 'Forte dei Marmi', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6533.png'), 
      (6534, 'Stadio Valerio Bacigalupo', 'Via Luigi Cadorna, 5', 'Savona', 'Italy', 3999, 'grass', 'https://media.api-sports.io/football/venues/6534.png'), 
      (6535, 'Stadio Comunale Buon Riposo', 'Via del Campo', 'Pozzi Seravezza', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6535.png'), 
      (6536, 'Stadio Ferruccio Chittolina', 'Via Diaz 33, Vallegia-Quiliano', 'Vadu Ligure', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6536.png'), 
      (6537, 'Stadio Carlo Pedroli', 'Via Arturo Farinelli, 10', 'Verbania', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6537.png'), 
      (6540, 'Centro Sportivo Comunale Roberto Battaglia', 'Via Benvenuto Cellini, 42', 'Busto Garolfo', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6540.png'), 
      (6539, 'Campo Sportivo Comunale Brusaporto', 'Via Belvedere', 'Brusaporto', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/6539.png'), 
      (6541, 'Stadio Comunale', 'Via Olimpia', 'Caravaggio', 'Italy', 2180, 'grass', 'https://media.api-sports.io/football/venues/6541.png'), 
      (12414, 'Stadio Comunale Giovanni Provasi', 'Via Generale Luigi Cadorna, 11', 'Castellanza', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/12414.png'), 
      (6543, 'Stadio Comunale Dro', 'Via Capitelli', 'Dro', 'Italy', 500, 'grass', 'https://media.api-sports.io/football/venues/6543.png'), 
      (6544, 'Stadio XXV Aprile', 'Via XXV Aprile, 13', 'Carate Brianza', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6544.png'), 
      (6545, 'Centro Sportivo Comunale', 'Via Lazzaretto 13', 'Inveruno', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6545.png'), 
      (6546, 'Stadio Comunale Giovanni Mari', 'Via Carlo Pisacane', 'Legnano', 'Italy', 6700, 'grass', 'https://media.api-sports.io/football/venues/6546.png'), 
      (6547, 'Stadio Comunale', 'Viale Lido', 'Levico Terme', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6547.png'), 
      (6548, 'Stadio Comunale Al Bersaglio', 'Loc.Bersaglio Via P. de Coubertin', 'Oggiono', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6548.png'), 
      (6549, 'Stadio Matteo Legler', 'Via Trento e Trieste, 12', 'Ponte San Pietro', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6549.png'), 
      (6550, 'Stadio Ernesto Breda', 'Via XX Settembre, 162', 'Sesto San Giovanni', 'Italy', 4475, 'grass', 'https://media.api-sports.io/football/venues/6550.png'), 
      (6551, 'Stadio Comunale Unione Sportiva Scanzorosciate', 'Via Polcarezzo 11', 'Scanzorosciate', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6551.png'), 
      (6552, 'Stadio Coni Castellina', 'Via Valeriana 33', 'Sondrio', 'Italy', 1300, 'grass', 'https://media.api-sports.io/football/venues/6552.png'), 
      (6553, 'Stadio Comunale La Rocca', 'Via Rocca, 19', 'Trezzo sull&apos;Adda', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6553.png'), 
      (6554, 'Campo Sportivo Comunale Villa D''Almè', 'Via Ronco Basso 15', 'Villa D&apos;Almè', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6554.png'), 
      (6555, 'Campo Calcio Righi', 'Via Luigi Cadorna, 25 (Cadornastrasse 25)', 'Bozen', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6555.png'), 
      (6556, 'Stadio Carlo Rossoni', 'Via Mazzini 13', 'Ciserano', 'Italy', 1000, null, 'https://media.api-sports.io/football/venues/6556.png'), 
      (6558, 'Stadio Montindon', 'Via Alessandro Volta', 'Sant&apos;ambrogio Di Valpolicella', 'Italy', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6558.png'), 
      (6559, 'Stadio Comunale Polisportivo', 'Piazzale Resistenza 27', 'Belluno', 'Italy', 2585, 'grass', 'https://media.api-sports.io/football/venues/6559.png'), 
      (6560, 'Stadio Comunale di Caldiero', 'Via Santi, 54', 'Caldiero', 'Italy', 3500, 'grass', 'https://media.api-sports.io/football/venues/6560.png'), 
      (6561, 'Stadio Fair Play di Cartigliano', 'Viale Lungo Brenta', 'Cartigliano', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6561.png'), 
      (6562, 'Stadio Comunale Francesco Tesolin', 'Via Garibaldi', 'Chions', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6562.png'), 
      (6563, 'Stadio Via Rizzolo', 'Via Rizzolo', 'Carlino', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6563.png'), 
      (6564, 'Stadio Aldo e Dino Ballarin', 'Via Stazione, 30', 'Chioggia', 'Italy', 3622, 'grass', 'https://media.api-sports.io/football/venues/6564.png'), 
      (6565, 'Stadio Comunale Umberto Cavallari', 'Via Tangenziale, 10', 'Porto Tolle', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6565.png'), 
      (6566, 'Nuovo Stadio Comunale', 'Via Monte Cero 81', 'Este', 'Italy', 1200, 'grass', 'https://media.api-sports.io/football/venues/6566.png'), 
      (6567, 'Stadio Mario Sandrini', 'Via Olimpia', 'Legnago', 'Italy', 2152, 'grass', 'https://media.api-sports.io/football/venues/6567.png'), 
      (6568, 'Stadio Comunale Gianni Casée', 'Via Leonardo da Vinci, 7', 'San Martino di Lupari', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6568.png'), 
      (6569, 'Stadio San Vigilio', 'Via Piave', 'Montebelluna', 'Italy', 1900, 'grass', 'https://media.api-sports.io/football/venues/6569.png'), 
      (6570, 'Stadio Comunale Via Felluga', 'Via Felluga Umberto, 58', 'Trieste', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6570.png'), 
      (6571, 'Stadio Comunale di Tamai', 'Via Giovanni XXIII 41', 'Tamai', 'Italy', 1140, 'grass', 'https://media.api-sports.io/football/venues/6571.png'), 
      (6572, 'Stadio Zugni Tauro', 'Via Bagnols Sur Cèzè, 1', 'Feltre', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6572.png'), 
      (6573, 'Stadio Comunale Umberto Capone', 'Via Alzeri', 'Vigasio', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6573.png'), 
      (6576, 'Stadio Comunale Brigata Cremona', 'Piazza Generale Clemente Primieri, 9', 'Alfonsine', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/6576.png'), 
      (6577, 'Campo Sportivo Comunale Tassara', 'Viale Italia', 'Breno', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6577.png'), 
      (6578, 'Stadio Comunal Mundial ‘82', 'Via Giovanni Verga', 'Carpenedolo', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/6578.png'), 
      (6579, 'Nuevo Stadio Comunale Walter Borelli', 'Via Fazzano 4', 'Correggio', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6579.png'), 
      (6580, 'Stadio Comunale', 'Via Campo Sportivo 1', 'Fiorenzuola d&apos;Arda', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/6580.png'), 
      (6581, 'Campo Sportivo Comunale Maselli', 'Via Tullio Dandolo, 57', 'Adro', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/6581.png'), 
      (6582, 'Stadio Comunale Valente Levantini', 'Via Bacchi Mellini, 22', 'Lentigione', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/6582.png'), 
      (6583, 'Stadio Pietro Zucchini', 'Piazzale della Gioventù', 'Budrio', 'Italy', 1300, 'grass', 'https://media.api-sports.io/football/venues/6583.png'), 
      (6584, 'Campo Da Calcio Macrelli', 'Via Monti 1', 'San Mauro Pascoli', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6584.png'), 
      (6585, 'Centro Sportivo Enrico Filippetti', 'Via Gesso, 26, Riale', 'Zola Predosa', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6585.png'), 
      (6586, 'Stadio Giuseppe Capanni', 'Via della Resistenza', 'Savignano sul Rubicone', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/6586.png'), 
      (6587, 'Stadio Carpaneto Piacentino', 'Via S. Lazzaro 1', 'Carpaneto Piacentino', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6587.png'), 
      (6590, 'Stadio Comunale Germano Bellucci', 'Via Giovannella, 1', 'Agliana', 'Italy', 2582, 'grass', 'https://media.api-sports.io/football/venues/6590.png'), 
      (6591, 'Stadio Comunale', 'Piazza Bakunin 1', 'Bastia Umbra', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/6591.png'), 
      (6592, 'Stadio Comunale Spoletini', 'Via Assisi', 'Cannara', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6592.png'), 
      (6593, 'Stadio Enzo Blasone', 'Via Monte Cucco, Santo Pietro', 'Foligno', 'Italy', 5650, 'grass', 'https://media.api-sports.io/football/venues/6593.png'), 
      (6594, 'Stadio Turiddu Madami', 'Via Enrico Minio', 'Civita Castellana', 'Italy', 1300, 'grass', 'https://media.api-sports.io/football/venues/6594.png'), 
      (6595, 'Stadio di Grassina', 'Via Abebe Bikila, Grassina', 'Bagno a Ripoli', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/6595.png'), 
      (4707, 'Stadio Olimpico Carlo Zecchini', 'Via Veterani dello Sport, 6', 'Grosseto', 'Italy', 9779, 'grass', 'https://media.api-sports.io/football/venues/4707.png'), 
      (6597, 'Stadio Comunale', 'Via Giuseppe Saragat', 'Pomezia', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/6597.png'), 
      (12424, 'Stadio Comunale Pianigiani', 'via Cassia 25', 'Tavarnelle Val di Pesa', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/12424.png'), 
      (6599, 'Stadio Virgilio Fedini', 'Via Bruno Buozzi', 'San Giovanni Valdarno', 'Italy', 3400, 'grass', 'https://media.api-sports.io/football/venues/6599.png'), 
      (6600, 'Stadio Turri', 'Via Rialdoli', 'Firenze', 'Italy', 1800, 'grass', 'https://media.api-sports.io/football/venues/6600.png'), 
      (12425, 'Stadio Lorenzo Casini', 'Via G. Bretagna 3 / Via Raffaello Lambruschini', 'Trestina', 'Italy', 666, 'grass', 'https://media.api-sports.io/football/venues/12425.png'), 
      (12430, 'Stadio Comunale', 'Viale dello Sport', 'Fiuggi', 'Italy', 3500, 'grass', 'https://media.api-sports.io/football/venues/12430.png'), 
      (6603, 'Stadio dei Marsi', 'Via Ferrara', 'Avezzano', 'Italy', 3692, 'grass', 'https://media.api-sports.io/football/venues/6603.png'), 
      (6604, 'Stadio Giorgio Calbi', 'Via del Partigiano 4', 'Cattolica', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6604.png'), 
      (6605, 'Stadio Guido Angelini', 'Viale Abruzzo, Chieti Scalo', 'Chieti', 'Italy', 12750, 'grass', 'https://media.api-sports.io/football/venues/6605.png'), 
      (6606, 'Stadio Nuovo Romagnoli', 'Contrada Fontana Vecchia', 'Campobasso', 'Italy', 21800, 'grass', 'https://media.api-sports.io/football/venues/6606.png'), 
      (6607, 'Stadio Comunale P. Carotti', 'Viale Cavallotti', 'Jesi', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6607.png'), 
      (6608, 'Stadio Comunale Pianarelle Tamburrini', 'Contrada Pianarelle', 'Montegiorgio', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6608.png'), 
      (6609, 'Stadio Comunale Civitelle', 'Viale Castelnuovo', 'Agnone', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6609.png'), 
      (6610, 'Stadio Comunale Mimmo Pavone', 'Strada Provinciale Pineto-Atri', 'Pineto', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6610.png'), 
      (6611, 'Stadio Ferranti', 'Via Della Liberazione', 'Porto Sant&apos;elpidio', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6611.png'), 
      (6612, 'Stadio Rubens Fadini', 'Via Migliori, 13', 'Giulianova', 'Italy', 5625, 'grass', 'https://media.api-sports.io/football/venues/6612.png'), 
      (6613, 'Stadio Nicola Tubaldi', 'Via Aldo Moro', 'Recanati', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6613.png'), 
      (6614, 'Stadio Comunale Vincenzo Savini', 'Via Fosse Ardeatine', 'Notaresco', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6614.png'), 
      (6615, 'Stadio Comunale Villa San Filippo', 'Via Magellano Monte, Villa San Filippo', 'Monte San Giusto', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6615.png'), 
      (6616, 'Campo Sportivo della Vittoria Tolentino', 'Via Arnaldo Lucentini, 3', 'Tolentino', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/6616.png'), 
      (6617, 'Stadio Comunale Aragona', 'Via San Michele, 52', 'Vasto', 'Italy', 5374, 'grass', 'https://media.api-sports.io/football/venues/6617.png'), 
      (12431, 'Stadio Comunale Vastogirardi', 'Viale Raffaello Sanzio', 'Vastogirardi', 'Italy', 1200, 'grass', 'https://media.api-sports.io/football/venues/12431.png'), 
      (6619, 'Stadio Quinto Ricci', 'Via Donato Bardi, 6', 'Aprilia', 'Italy', 2504, 'grass', 'https://media.api-sports.io/football/venues/6619.png'), 
      (6620, 'Stadio Comunale San Teodoro', 'Via Donat Cattin', 'San Teodoro', 'Italy', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6620.png'), 
      (6621, 'Stadio Comunale Gino Salvetti', 'Via Appia Nuova', 'Cassino', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6621.png'), 
      (6622, 'Campo Sportivo Caslini Andrea', 'Via Francesco Berni', 'Colleferro', 'Italy', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6622.png'), 
      (6623, 'Stadio Angelo Sale', 'Via Lazzari, Loc. Campi Vaccina', 'Ladispoli', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/6623.png'), 
      (6624, 'Stadio Comunale Latte Dolce', 'Via Leoncavallo 6', 'Sassari', 'Italy', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6624.png'), 
      (6625, 'Campo Sportivo di Muravera', 'Via Roma', 'Muravera', 'Italy', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6625.png'), 
      (6626, 'Stadio Anco Marzio', 'Via Giovanni Amenduni, 15', 'Lido di Ostia', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6626.png'), 
      (6627, 'Stadio San Ciro', 'Via Farina', 'Portici', 'Italy', 7000, 'grass', 'https://media.api-sports.io/football/venues/6627.png'), 
      (6628, 'Stadio Giorgio Castelli', 'Via Felice De Andreis, 29/31', 'Roma', 'Italy', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6628.png'), 
      (6629, 'Stadio Marco Mazzucchi', 'Via Rieti', 'Ardea', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/6629.png'), 
      (6630, 'Stadio Vanni Sanna', 'Via Coradduzza, 2', 'Sassari', 'Italy', 7480, 'grass', 'https://media.api-sports.io/football/venues/6630.png'), 
      (6631, 'Stadio Comunale (Sintex)', 'Via Guglielmo Marconi 52', 'Artena', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6631.png'), 
      (6633, 'Stadio Comunale Giovanni Paolo II', 'Via Rubichi 4', 'Nardò', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6633.png'), 
      (6634, 'Stadio Italia', 'Via Aniello Califano, 7', 'Sorrento', 'Italy', 3600, 'grass', 'https://media.api-sports.io/football/venues/6634.png'), 
      (6636, 'Stadio Raffaele Guariglia', 'Via San Pio X', 'Agropoli', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6636.png'), 
      (6637, 'Campo Comunale Domenico Monterisi', 'Via Napoli', 'Cerignola', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6637.png'), 
      (6638, 'Campo Sportivo Comunale Città degli Ulivi', null, 'Bitonto', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/6638.png'), 
      (6639, 'Stadio Franco Fanuzzi', 'Via Santa Maria del Casale', 'Brindisi', 'Italy', 7600, 'grass', 'https://media.api-sports.io/football/venues/6639.png'), 
      (6640, 'Stadio Giuseppe Capozza', 'Via Matino', 'Casarano', 'Italy', 6200, 'grass', 'https://media.api-sports.io/football/venues/6640.png'), 
      (6641, 'Stadio Nunzio Fittipaldi', 'Via Luigi Ciminelli, 128', 'Francavilla in Sinni', 'Italy', 1200, 'grass', 'https://media.api-sports.io/football/venues/6641.png'), 
      (6642, 'Stadio Giovanni Morra', 'Via Torrusio', 'Vallo della Lucania', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/6642.png'), 
      (6643, 'Stadio Mario Piccirillo', 'Via Martiri del Dissenso', 'Santa Maria Capua Vetere', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/6643.png'), 
      (6644, 'Stadio Comunale Stefano Vicino', 'Via Fazzatoia, 9', 'Gravina in Puglia', 'Italy', 6000, 'artificial turf', 'https://media.api-sports.io/football/venues/6644.png'), 
      (6645, 'Stadio Comunale Villa D''Agri C11', 'Via Grumentina', 'Marsicovetere', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6645.png'), 
      (6646, 'Stadio San Francesco', 'Viale San Francesco', 'Nocera Inferiore', 'Italy', 9998, 'grass', 'https://media.api-sports.io/football/venues/6646.png'), 
      (6647, 'Stadio Comunale Tonino D''Angelo', 'Via Mura Megalitiche, 61', 'Altamura', 'Italy', 8000, 'grass', 'https://media.api-sports.io/football/venues/6647.png'), 
      (6648, 'Stadio Tupparello', 'Via dello Stadio', 'Acireale', 'Italy', 12000, 'grass', 'https://media.api-sports.io/football/venues/6648.png'), 
      (6649, 'Stadio Orazio Raiti', 'Via Giacomo Matteotti, 74', 'Biancavilla', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6649.png'), 
      (6650, 'Stadio Comunale Castrovillari Mimmo Rende', 'Via Veterani dello Sport', 'Castrovillari', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/6650.png'), 
      (6651, 'Stadio Comunale Cittanova', 'Viale A. Moro, Loc. S. Maria', 'Cittanova', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6651.png'), 
      (6652, 'Stadio Comunale di Corigliano', 'Strada Provinciale 196', 'Corigliano Calabro', 'Italy', 3500, 'grass', 'https://media.api-sports.io/football/venues/6652.png'), 
      (12435, 'Stadio Comunale Alberto De Cristofaro', 'Via Epitaffio', 'Giugliano in Campania', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12435.png'), 
      (6655, 'Stadio Dino Liotta', 'Corso Argentina', 'Licata', 'Italy', 11000, 'grass', 'https://media.api-sports.io/football/venues/6655.png'), 
      (6656, 'Stadio Aldo Campo', 'Via Avvocato Giovanni Alberto Cartia, Contrada Selvaggio', 'Ragusa', 'Italy', 3500, 'grass', 'https://media.api-sports.io/football/venues/6656.png'), 
      (6657, 'Stadio Antonio Lombardo Angotta', 'Via Olimpia', 'Marsala', 'Italy', 13500, 'grass', 'https://media.api-sports.io/football/venues/6657.png'), 
      (6658, 'Stadio Sporting Club', 'Via Seminario', 'Nola', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/6658.png'), 
      (6659, 'Stadio Giuseppe Lopresti', 'Via del Tracciolino', 'Palmi', 'Italy', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6659.png'), 
      (6660, 'Stadio Comunale Ninetto Muscolo', 'Viale degli Ulivi', 'Roccella Ionica', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/6660.png'), 
      (6661, 'Stadio Alfredo Giraud', 'Piazzale Gargiulo, 2', 'Torre Annunziata', 'Italy', 10750, 'grass', 'https://media.api-sports.io/football/venues/6661.png'), 
      (12444, 'Stadio Comunale Gagliano Castelferrato', 'Via Regione Siciliana, Zona Stadio 17', 'Gagliano Castelferrato', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12444.png'), 
      (18540, 'Stadio Comunale Progresso', 'Via Lirone, 44', 'Castel Maggiore', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/18540.png'), 
      (12034, 'Stadio Daniele Mariotti', 'Via di Maratona, 16', 'Montecatini Terme', 'Italy', 3500, 'grass', 'https://media.api-sports.io/football/venues/12034.png'), 
      (12053, 'Campo Sportivo Comunale Libico', 'Via Don Pietro Belotti, 53', 'Grumello del Monte', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/12053.png'), 
      (12059, 'Stadio Briamasco', 'Via R. da Sanseverino 41', 'Trento', 'Italy', 4227, 'grass', 'https://media.api-sports.io/football/venues/12059.png'), 
      (12415, 'Stadio Comunale', 'Via dell&apos;Industria 33', 'Olginate', 'Italy', 1050, 'grass', 'https://media.api-sports.io/football/venues/12415.png'), 
      (12530, 'Stadio Domenico Conte', 'Prima Traversa Via Virgilio', 'Pozzuoli', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/12530.png'), 
      (12534, 'Stadio Buitoni', 'Via del Campo Sportivo 1', 'Sansepolcro', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/12534.png'), 
      (12416, 'Campo Sportivo Comunale n.2', 'Via Alessandro Volta', 'Casatenovo', 'Italy', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12416.png'), 
      (12408, 'Stadio Vincenzo Cesin Bosia', 'Via Ugo Foscolo 19', 'Asti', 'Italy', 6000, 'grass', 'https://media.api-sports.io/football/venues/12408.png'), 
      (12409, 'Stadio Fausto Coppi', 'Viale della Libertá', 'Tortona', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/12409.png'), 
      (12410, 'Stadio Nino Ciccione', 'Strada Vivinale Costamagna', 'Imperia', 'Italy', 3900, 'grass', 'https://media.api-sports.io/football/venues/12410.png'), 
      (12411, 'Stadio Crestella', 'Via Crestellaz', 'Donnas', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/12411.png'), 
      (12640, 'Campo Sportivo Romentino', 'Via del Tintoretto, 9', 'Romentino', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/12640.png'), 
      (12412, 'Stadio Amedeo Damiano', 'Via della Croce', 'Saluzzo', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12412.png'), 
      (12413, 'Stadio Giuseppe Sivori', 'Via per Santa Vittoria, 5', 'Sestri Levante', 'Italy', 1800, 'grass', 'https://media.api-sports.io/football/venues/12413.png'), 
      (12417, 'Stadio Tre Stelle', 'Via Giotto, 104', 'Desenzano del Garda', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/12417.png'), 
      (12631, 'Campo Sportivo Comunale 1', 'Via Risorgimento, 22', 'San Giuliano Milanese', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/12631.png'), 
      (12418, 'Stadio Comunale Sona', 'Via Casella, 22', 'Sona', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/12418.png'), 
      (12419, 'Centro sportivo comunale Stefano Borgonovo', 'Largo Donatori di Sangue, 3', 'Giussano', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/12419.png'), 
      (12641, 'Campo San Martino Buon Albergo', null, 'San Martino Buon Albergo', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/12641.png'), 
      (12642, 'Stadio Comunale Salvador Allende', 'Viale Sanremo, 63', 'Spinea', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/12642.png'), 
      (12643, 'Campo Sportivo Alcione 1', 'Via Alessio Olivieri, 13', 'Milano', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12643.png'), 
      (12639, 'Comunale Dorando Pietri', 'Via Nuova Ponente 24/C', 'Carpi', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/12639.png'), 
      (12422, 'Stadio Fratelli Campari', 'Via Olimpia 4', 'Bagnolo in Piano', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12422.png'), 
      (12644, 'Stadio Dario Ballotta', 'Via Palmiro Togliatti', 'Fidenza', 'Italy', 2400, 'grass', 'https://media.api-sports.io/football/venues/12644.png'), 
      (12645, 'Stadio Redini', 'Piazza Ferrari, 5', 'Cascina', 'Italy', 2000, 'grass', 'https://media.api-sports.io/football/venues/12645.png'), 
      (12426, 'Stadio Mauro Nannotti', 'Via Palmiro Togliatti 2, Badesse', 'Monteriggioni', 'Italy', 1500, 'grass', 'https://media.api-sports.io/football/venues/12426.png'), 
      (12427, 'Campo Sportivo Montespaccato', 'Via Stefano Vaj, 41', 'Roma', 'Italy', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/12427.png'), 
      (12428, 'Stadio Stefano Lotti', 'Viale Marconi, 105', 'Poggibonsi', 'Italy', 3621, 'grass', 'https://media.api-sports.io/football/venues/12428.png'), 
      (12429, 'Stadio Banditella', 'Via Sommati Pier Donato, 2', 'Livorno', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12429.png'), 
      (6601, 'Stadio Comunale C. Bernicchi', 'Viale Europa 5', 'Citta di Castello', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/6601.png'), 
      (12646, 'Stadio Franco Maniscalco', 'Piazzale Aldo Moro', 'Pomezia', 'Italy', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12646.png'), 
      (12647, 'Campo Sportivo di Capriati a Volturno', null, 'Capriati a Volturno', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12647.png'), 
      (12432, 'Nuovo Stadio Comunale G.Mancini', 'Via dello Sport', 'Castelfidardo', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12432.png'), 
      (12433, 'Campo Comunale', 'Via Napoli', 'Castelnuovo Vomano', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12433.png'), 
      (12434, 'Stadio Comunale P. Ferrante', 'Via Limate, 11', 'Piedimonte Matese', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12434.png'), 
      (12648, 'Stadio Comunale di Nereto', 'Via Vibrata', 'Nereto', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/12648.png'), 
      (12649, 'Campo Ciarrocchi', 'Via Martiri di Marzabotto', 'San Benedetto del Tronto', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12649.png'), 
      (12436, 'Stadio Caduti di Brema', 'Via delle Repubbliche Marinare, 223, Barra', 'Napoli', 'Italy', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/12436.png'), 
      (12650, 'Campo Comunale Uri', 'Via L. Tolstoj, 40', 'Uri', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12650.png'), 
      (12437, 'Stadio Carlo Zoboli', 'Via della Stazione, 19', 'Carbonia', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/12437.png'), 
      (12438, 'Stadio Comunale', 'Via Sicilia 27', 'Genzano di Roma', 'Italy', 6500, 'grass', 'https://media.api-sports.io/football/venues/12438.png'), 
      (12439, 'Stadio Comunale di Formia', 'Via della Fontana', 'Formia', 'Italy', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/12439.png'), 
      (12651, 'Stadio Ottavio Pierangeli', null, 'Monterotondo', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12651.png'), 
      (12441, 'Stadio Franco Pisicchio', null, 'Lavello', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12441.png'), 
      (12652, 'Stadio Comunale di Marigliano', 'Via Europa, 18', 'Marigliano', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12652.png'), 
      (12442, 'Stadio Comunale Paolo Poli', 'Via Don Pietro Pappagallo', 'Molfetta', 'Italy', 5000, 'grass', 'https://media.api-sports.io/football/venues/12442.png'), 
      (12443, 'Campo sportivo Nicola Vulcano', 'Forcelle', 'Castelluccio Inferiore', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12443.png'), 
      (12653, 'Stadio Comunale Rafaele Paudice', 'Via Sandriana', 'San Giorgio a Cremano', 'Italy', 800, 'artificial turf', 'https://media.api-sports.io/football/venues/12653.png'), 
      (12654, 'Stadio Comunale Via Del Mare', 'Via Olimpia, 36', 'Matino', 'Italy', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12654.png'), 
      (12445, 'Stadio Proto-Morreale', 'Via Fausto Coppi', 'Melicucco', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/12445.png'), 
      (12446, 'Campo da Calcio di Sant''Agata di Militello', null, 'Sant&apos;Agata di Militello', 'Italy', 1000, 'grass', 'https://media.api-sports.io/football/venues/12446.png'), 
      (12655, 'Stadio Regionale Giarre', 'Via Olimpia', 'Giarre', 'Italy', 3000, 'grass', 'https://media.api-sports.io/football/venues/12655.png'), 
      (12632, 'Stadio Guido D''Ippolito', 'Via Guglielmo Marconi', 'Lamezia Terme', 'Italy', 3878, 'grass', 'https://media.api-sports.io/football/venues/12632.png'), 
      (12447, 'Stadio Falcone-Borsellino', 'Via dello Stadio', 'Paternò', 'Italy', 4000, 'grass', 'https://media.api-sports.io/football/venues/12447.png'), 
      (12448, 'Stadio Augusto Bisceglia', 'Via Enrico Caruso, San Lorenzo', 'Aversa', 'Italy', 2565, 'grass', 'https://media.api-sports.io/football/venues/12448.png'), 
      (12449, 'Stadio San Luca', null, 'Vorea', 'Italy', 2500, 'grass', 'https://media.api-sports.io/football/venues/12449.png'), 
      (12450, 'Stadio Valentino Mazzola', 'Via Trieste', 'San Cataldo', 'Italy', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12450.png'), 
      (12451, 'Campo Sportivo Antonio Carrano', 'Strada Statale 267', 'Santa Maria di Castellabate', 'Italy', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12451.png'), 
      (12637, 'Campo Comunale', 'Via Monte Nero', 'Venegono Superiore', 'Italy', 1200, 'grass', 'https://media.api-sports.io/football/venues/12637.png'), 
      (18733, 'Stadio Romeo Menti', 'Via Schio, 21', 'Vicenza', 'Italy', 20920, 'grass', 'https://media.api-sports.io/football/venues/18733.png');