INSERT INTO venues (id, name, address, city, country, capacity, surface, image) 
VALUES (1456, 'Estadio Santiago Bernabéu', 'Avenida de Concha Espina 1, Chamartín', 'Madrid', 'Spain', 85454, 'grass', 'https://media.api-sports.io/football/venues/1456.png'), 
      (18630, 'Spotify Camp Nou', 'Carrer d&apos;Arístides Maillol', 'Barcelona', 'Spain', 99787, 'grass', 'https://media.api-sports.io/football/venues/18630.png'), 
      (1461, 'Estadio Wanda Metropolitano', 'Rosas', 'Madrid', 'Spain', 68032, 'grass', 'https://media.api-sports.io/football/venues/1461.png'), 
      (1460, 'San Mamés Barria', 'Rafael Moreno Pitxitxi Kalea', 'Bilbao', 'Spain', 53289, 'grass', 'https://media.api-sports.io/football/venues/1460.png'), 
      (1497, 'Estadio de Mestalla', 'Avenida de Suecia', 'Valencia', 'Spain', 55000, 'grass', 'https://media.api-sports.io/football/venues/1497.png'), 
      (1498, 'Estadio de la Cerámica', 'Plaza Labrador', 'Villarreal', 'Spain', 24500, 'grass', 'https://media.api-sports.io/football/venues/1498.png'), 
      (1481, 'Estadio de Gran Canaria', 'Avenida Pío XII 29', 'Las Palmas de Gran Canaria', 'Spain', 31250, 'grass', 'https://media.api-sports.io/football/venues/1481.png'), 
      (1483, 'Estadio La Rosaleda', 'Avenida de la Palmilla / Paseo de Martiricos', 'Málaga', 'Spain', 30389, 'grass', 'https://media.api-sports.io/football/venues/1483.png'), 
      (1494, 'Estadio Ramón Sánchez Pizjuán', 'Avenida de Eduardo Dato', 'Sevilla', 'Spain', 48649, 'grass', 'https://media.api-sports.io/football/venues/1494.png'), 
      (1464, 'Estadio Municipal de Butarque', 'Calle Arquitectura', 'Leganés', 'Spain', 12450, 'grass', 'https://media.api-sports.io/football/venues/1464.png'), 
      (1467, 'Abanca-Balaídos', 'Avenida de Balaídos', 'Vigo', 'Spain', 31800, 'grass', 'https://media.api-sports.io/football/venues/1467.png'), 
      (1482, 'Estadio Ciudad de Valencia', 'Calle San Vicente de Paúl 44', 'Valencia', 'Spain', 25534, 'grass', 'https://media.api-sports.io/football/venues/1482.png'), 
      (1474, 'RCDE Stadium', 'Avenida Baix Llobregat 100', 'Cornella de Llobregat', 'Spain', 40423, 'grass', 'https://media.api-sports.io/football/venues/1474.png'), 
      (1470, 'Estadio de Mendizorroza', 'Paseo de Cervantes', 'Vitoria-Gasteiz', 'Spain', 19840, 'grass', 'https://media.api-sports.io/football/venues/1470.png'), 
      (1489, 'Estadio Benito Villamarín', 'Avenida de Heliópolis', 'Sevilla', 'Spain', 60721, 'grass', 'https://media.api-sports.io/football/venues/1489.png'), 
      (1471, 'Estadio Abanca-Riazor', 'Calle Manuel Murguía', 'La Coruña', 'Spain', 34611, 'grass', 'https://media.api-sports.io/football/venues/1471.png'), 
      (1472, 'Estadio Municipal de Ipurúa', 'Calle de Ipurúa', 'Eibar', 'Spain', 8050, 'grass', 'https://media.api-sports.io/football/venues/1472.png'), 
      (1476, 'Coliseum Alfonso Pérez', 'Avenida de Teresa de Calcuta', 'Getafe', 'Spain', 17393, 'grass', 'https://media.api-sports.io/football/venues/1476.png'), 
      (1478, 'Estadi Municipal de Montilivi', 'Avenida Montlivi 141', 'Girona', 'Spain', 14500, 'grass', 'https://media.api-sports.io/football/venues/1478.png'), 
      (1491, 'Reale Arena', 'Paseo de Anoeta 1', 'Donostia-San Sebastián', 'Spain', 39500, 'grass', 'https://media.api-sports.io/football/venues/1491.png'), 
      (1466, 'Camp Municipal de Futbol Nou Sardenya', 'Carrer de Sardenya (Cerdeña), Gràcia', 'Barcelona', 'Spain', 7000, 'artificial turf', 'https://media.api-sports.io/football/venues/1466.png'), 
      (1457, 'Estadio Santo Domingo', 'Avenida de Pablo Iglesias', 'Alcorcón', 'Spain', 7000, 'grass', 'https://media.api-sports.io/football/venues/1457.png'), 
      (2917, 'Estadi Johan Cruyff', 'B-23', 'Sant Joan Despí', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/2917.png'), 
      (1469, 'Estadio Nuevo Arcángel', 'Avenida del Arcángel', 'Córdoba', 'Spain', 21822, 'grass', 'https://media.api-sports.io/football/venues/1469.png'), 
      (1477, 'Nou Estadi de Tarragona', 'Camí del Llorito', 'Tarragona', 'Spain', 16600, 'grass', 'https://media.api-sports.io/football/venues/1477.png'), 
      (1479, 'Estadio Nuevo Los Cármenes', 'Calle Pintor Manuel Maldonado', 'Granada', 'Spain', 23156, 'grass', 'https://media.api-sports.io/football/venues/1479.png'), 
      (1465, 'Estadio Anxo Carro', 'Avenida de los deportes', 'Lugo', 'Spain', 7840, 'grass', 'https://media.api-sports.io/football/venues/1465.png'), 
      (1485, 'Nuevo Estadio Los Pajaritos', 'Avenida Mariano Vicen 16', 'Soria', 'Spain', 9025, 'grass', 'https://media.api-sports.io/football/venues/1485.png'), 
      (1490, 'Estadio Nuevo Carlos Tartiere', 'Calle de Ricardo Vázquez Prada, Barrio de la Ería', 'Oviedo', 'Spain', 29862, 'grass', 'https://media.api-sports.io/football/venues/1490.png'), 
      (1496, 'Estadio Heliodoro Rodríguez Lopéz', 'Avenida de San Sebastián', 'Tenerife', 'Spain', 23660, 'grass', 'https://media.api-sports.io/football/venues/1496.png'), 
      (1492, 'Estadio Municipal José Zorrilla', 'Avenida del Mundial 82', 'Valladolid', 'Spain', 26512, 'grass', 'https://media.api-sports.io/football/venues/1492.png'), 
      (2918, 'Estadio Francisco Artés Carrasco', 'Carratera de Granada', 'Lorca', 'Spain', 8120, 'grass', 'https://media.api-sports.io/football/venues/2918.png'), 
      (1458, 'Estadio Carlos Belmonte', 'Avenida de España', 'Albacete', 'Spain', 17524, 'grass', 'https://media.api-sports.io/football/venues/1458.png'), 
      (1459, 'Estadio de los Juegos Mediterráneos', 'Calle de Belladona', 'Almería', 'Spain', 21350, 'grass', 'https://media.api-sports.io/football/venues/1459.png'), 
      (11915, 'Estadio Nuevo Mirandilla', 'Plaza de Madrid', 'Cádiz', 'Spain', 22000, 'grass', 'https://media.api-sports.io/football/venues/11915.png'), 
      (2916, 'Estadio Municipal Reino de León', 'Paseo Sáenz de Miera', 'León', 'Spain', 13451, 'grass', 'https://media.api-sports.io/football/venues/2916.png'), 
      (1480, 'Estadio El Alcoraz', 'Camino del Alto Cocorón', 'Huesca', 'Spain', 7638, 'grass', 'https://media.api-sports.io/football/venues/1480.png'), 
      (1486, 'Estadio El Sadar', 'Carretera El Sadar', 'Iruñea', 'Spain', 23576, 'grass', 'https://media.api-sports.io/football/venues/1486.png'), 
      (1488, 'Estadio de Vallecas', 'Calle Payaso Fofó', 'Madrid', 'Spain', 15500, 'grass', 'https://media.api-sports.io/football/venues/1488.png'), 
      (1468, 'Estadio Camp Nou Municipal', 'Calle Recasens i Mercadé 8', 'Reus', 'Spain', 4847, 'grass', 'https://media.api-sports.io/football/venues/1468.png'), 
      (2919, 'Estadio Jesús Navas', 'Carretera de Utrera', 'Sevilla', 'Spain', 7000, 'grass', 'https://media.api-sports.io/football/venues/2919.png'), 
      (1495, 'Estadio Municipal El Molinón', 'Parque de Isabel la Católica', 'Gijón', 'Spain', 29538, 'grass', 'https://media.api-sports.io/football/venues/1495.png'), 
      (1493, 'Estadio de la Romareda', 'Calle de Eduardo Ibarra 6', 'Zaragoza', 'Spain', 34596, 'grass', 'https://media.api-sports.io/football/venues/1493.png'), 
      (1473, 'Estadio Manuel Martínez Valero', 'Avenida Manuel Martínez Valero 3', 'Elche', 'Spain', 36017, 'grass', 'https://media.api-sports.io/football/venues/1473.png'), 
      (12597, 'Visit Mallorca Estadi', 'Camí dels Reis', 'Palma de Mallorca', 'Spain', 23142, 'grass', 'https://media.api-sports.io/football/venues/12597.png'), 
      (2920, 'Estadio Municipal de Anduva', 'Camino de Anduva', 'Miranda de Ebro', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/2920.png'), 
      (2921, 'Estadio de La Condomina', 'Ronda de Garay 14', 'Murcia', 'Spain', 13500, 'grass', 'https://media.api-sports.io/football/venues/2921.png'), 
      (1475, 'Estadio Francisco de la Hera', 'Calle de Badajoz', 'Almendralejo', 'Spain', 11580, 'grass', 'https://media.api-sports.io/football/venues/1475.png'), 
      (1487, 'Miniestadio Cerro del Espino', 'Avenida del Principe de Asturias', 'Majadahonda', 'Spain', 3865, 'grass', 'https://media.api-sports.io/football/venues/1487.png'), 
      (3516, 'Campos de Sport de El Sardinero', 'Calle del Real Racing Club', 'Santander', 'Spain', 22271, 'grass', 'https://media.api-sports.io/football/venues/3516.png'), 
      (3517, 'Estadio José Rico Pérez', 'Carrer Camí de Ronda', 'Alicante', 'Spain', 29584, 'grass', 'https://media.api-sports.io/football/venues/3517.png'), 
      (3701, 'Estadio Municipal, Santa Eulària', null, null, 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/3701.png'), 
      (3707, 'Estadio Fernando Torres', 'Camino San Marcos', 'Fuenlabrada', 'Spain', 7500, 'grass', 'https://media.api-sports.io/football/venues/3707.png'), 
      (3708, 'Estadio El Toralín', 'Avenida de Asturias', 'Ponferrada', 'Spain', 8800, 'grass', 'https://media.api-sports.io/football/venues/3708.png'), 
      (3964, 'Estadi Municipal de Badalona', 'Avenida dels Vents 7, Barrio de Montigalà', 'Badalona', 'Spain', 4384, 'artificial turf', 'https://media.api-sports.io/football/venues/3964.png'), 
      (3965, 'Estadio Nuevo Lasesarre', 'Paseo El Ferrocarril', 'Barakaldo', 'Spain', 7960, 'grass', 'https://media.api-sports.io/football/venues/3965.png'), 
      (3966, 'Estadio La Planilla', 'Avenida de Numancia', 'Calahorra', 'Spain', 5600, null, 'https://media.api-sports.io/football/venues/3966.png'), 
      (3967, 'Estadio El Prado', null, 'Talavera de la Reina', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/3967.png'), 
      (3968, 'Nou Estadi Castalia', 'Calle de Huesca', 'Castellón de la Plana', 'Spain', 14485, 'grass', 'https://media.api-sports.io/football/venues/3968.png'), 
      (3969, 'Estadio Municipal Alfonso Murube', 'Avenida de Otero', 'Ceuta', 'Spain', 6500, 'artificial turf', 'https://media.api-sports.io/football/venues/3969.png'), 
      (3970, 'Estadio Multiusos de San Lázaro', 'Avenida de Fernando de Casas Nova, San Lázaro', 'Santiago de Compostela', 'Spain', 14000, 'grass', 'https://media.api-sports.io/football/venues/3970.png'), 
      (3971, 'Estadio Municipal La Fuensanta', 'Avenida de los Alfares', 'Cuenca', 'Spain', 6700, 'grass', 'https://media.api-sports.io/football/venues/3971.png'), 
      (3972, 'Campo Nuevo Municipal de Cornella', 'Carrer del Sorral del Riu', 'Cornella de Llobregat', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/3972.png'), 
      (3973, 'Estadio Vicente Sanz', 'Avenida Alonso Martín', 'Don Benito', 'Spain', 7000, 'grass', 'https://media.api-sports.io/football/venues/3973.png'), 
      (3974, 'Estadio Tabira', 'Calle de Tabira', 'Durango', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/3974.png'), 
      (3975, 'Estadio El Carmen', 'Avenida Almozara, Barrio de la Almozara', 'Zaragoza', 'Spain', 1200, 'artificial turf', 'https://media.api-sports.io/football/venues/3975.png'), 
      (3976, 'Estadio Municipal Cartagonova', 'Avenida Dr. Luis Calandre', 'Cartagena', 'Spain', 15105, 'grass', 'https://media.api-sports.io/football/venues/3976.png'), 
      (3977, 'Estadio Urbieta', null, 'Gernika-Lumo', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/3977.png'), 
      (3978, 'Estadio El Malecón', 'Avenida de la Constitución', 'Torrelavega', 'Spain', 6007, 'grass', 'https://media.api-sports.io/football/venues/3978.png'), 
      (3979, 'Estadio Nuevo Ganzábal', 'Calle Dolores Ibárruri', 'La Felguera, Langreo', 'Spain', 4024, 'artificial turf', 'https://media.api-sports.io/football/venues/3979.png'), 
      (3980, 'Camp d''Esports de Lleida', 'Avinguda del Dr. Fleming', 'Lleida', 'Spain', 13031, 'grass', 'https://media.api-sports.io/football/venues/3980.png'), 
      (3981, 'Estadio Municipal Antonio Lorenzo Cuevas', 'Travesía Huerta de los Cristales', 'Marbella', 'Spain', 7300, 'grass', 'https://media.api-sports.io/football/venues/3981.png'), 
      (3982, 'Estadio Álvarez Claro', 'Explanada de Camellos', 'Melilla', 'Spain', 12000, 'grass', 'https://media.api-sports.io/football/venues/3982.png'), 
      (3983, 'Estadio Silvestre Carrillo', 'Avenida del Puente', 'La Palma', 'Spain', 6000, 'artificial turf', 'https://media.api-sports.io/football/venues/3983.png'), 
      (3984, 'Estadio Municipal Valle de Aranguren', 'Avenida del Soto', 'Mutilva Baja', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/3984.png'), 
      (3985, 'Campo de San Francisco', 'C. Daniel Pérez Samitier', 'Reinosa', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/3985.png'), 
      (3986, 'Estadio Municipal El Clariano', 'Avenida del Textil 18', 'Ontinyent', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/3986.png'), 
      (3987, 'Estadio Municipal de Sa Pobla', null, 'Sa Pobla (Mallorca', 'Spain', 8000, 'grass', 'https://media.api-sports.io/football/venues/3987.png'), 
      (3988, 'Nuevo Estadio La Victoria', 'Carretera de Granada', 'Jaén', 'Spain', 12569, 'grass', 'https://media.api-sports.io/football/venues/3988.png'), 
      (3989, 'Estadio Enrique Roca de Murcia', 'Ronda de Garay 14', 'Murcia', 'Spain', 31179, 'grass', 'https://media.api-sports.io/football/venues/3989.png'), 
      (3990, 'Estadio Baltasar Pujales', 'Bouzas', 'Vigo', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/3990.png'), 
      (3991, 'Camp Municipal Narcís Sala', 'Carrer Santa Coloma 39, San Andrés de Palomar', 'Barcelona', 'Spain', 6563, 'artificial turf', 'https://media.api-sports.io/football/venues/3991.png'), 
      (3992, 'Estadio La Pinila', 'Marcos Peña Royo', 'Teruel', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/3992.png'), 
      (3993, 'Estadio Municipal Ciudad de Tudela', 'Avenida de las Merindades', 'Tudela', 'Spain', 11000, 'grass', 'https://media.api-sports.io/football/venues/3993.png'), 
      (3994, 'Estadio Nuevo Municipal Las Gaunas', 'Avenida de la Sierra', 'Logroño', 'Spain', 16000, 'grass', 'https://media.api-sports.io/football/venues/3994.png'), 
      (3995, 'Pistas del Helmántico', 'Carretera de Zamora', 'Salamanca', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/3995.png'), 
      (3996, 'Estadio Municipal Villanovense', 'Avenida de los Deportes', 'Villanueva de la Serena', 'Spain', 7145, 'grass', 'https://media.api-sports.io/football/venues/3996.png'), 
      (3997, 'Estadio Municipal La Constitución', 'Calle de la Cruz Piedra 148', 'Yecla', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/3997.png'), 
      (4884, 'Estadio Las Delicias', 'Calle Yegros', 'Mora', 'Spain', 1550, 'grass', 'https://media.api-sports.io/football/venues/4884.png'), 
      (5459, 'Estadio Municipal', 'Calle Bucaro / Calle de Salvador Allende', 'Lebrija', 'Spain', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/5459.png'), 
      (5460, 'Estadio Municipal San Benito', 'Calle Aviador Modesto Aguilera 117', 'Porcuna', 'Spain', 1200, 'artificial turf', 'https://media.api-sports.io/football/venues/5460.png'), 
      (5461, 'Estadio La Espiguera', 'Calle Alfonso X', 'Melilla', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/5461.png'), 
      (12462, 'Camp Municipal Sa Plana', null, 'Andratx', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/12462.png'), 
      (5775, 'Estadio El Castañar', null, 'San Vicente de la Barquera', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/5775.png'), 
      (5776, 'Estadio Mariano Haro', 'Paseo Polideportivo', 'Becerril de Campos', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/5776.png'), 
      (5777, 'Estadio Mundial 82', 'Calle Laguardia, km 1', 'Logroño', 'Spain', 1275, 'grass', 'https://media.api-sports.io/football/venues/5777.png'), 
      (5778, 'Polideportivo Municipal El Palmar', 'Calle Polideportivo', 'El Palmar', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/5778.png'), 
      (5779, 'Estadio Facundo Rivas', 'Calle del Arce, 102', 'El Álamo', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/5779.png'), 
      (5780, 'Estadio de La Estacada', 'Calle del Río Cinca 10', 'Fraga', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/5780.png'), 
      (5781, 'Estadio Municipal De Gran Tarajal', 'Calle Hierro, 59', 'Gran Tarajal', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/5781.png'), 
      (5782, 'Poliesportiu Sant Joan d''Alacant', 'Carrer Sant Antoni', 'San Juan de Alicante', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/5782.png'), 
      (10982, 'Estadio Municipal de Lobón', null, 'Lobón', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/10982.png'), 
      (5783, 'Estadio Municipal de Las Pedroñeras', 'Avenida de Juan Carlos I', 'Las Pedroñeras', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/5783.png'), 
      (5784, 'Estadio Miguel Sola', 'Calle Variante', 'Azagra', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/5784.png'), 
      (5785, 'Campo de fútbol de San Campio', 'Autoestrada do Atlántico', 'O Porrinno', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/5785.png'), 
      (5786, 'Estadio de Berazubi', 'Kalea Berazubi, 1', 'Tolosa', 'Spain', 3000, null, 'https://media.api-sports.io/football/venues/5786.png'), 
      (5787, 'Campo de La Corredoria', 'La Riera de Bricia', 'Posada de Llanes', 'Spain', 1700, 'artificial turf', 'https://media.api-sports.io/football/venues/5787.png'), 
      (6482, 'Campo Municipal de Urritxe', 'Barrio de Urritxe', 'Amorebieta-Echano', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6482.png'), 
      (6483, 'Estadio Balear', 'Carrer de Sant Ignasi, 70', 'Palma de Mallorca, Illes Balears', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/6483.png'), 
      (6484, 'Estadio Municipal Nuevo Vivero', 'Avenida de la Granadilla', 'Badajoz', 'Spain', 15198, 'grass', 'https://media.api-sports.io/football/venues/6484.png'), 
      (6485, 'Estadio As Eiroas', 'Calle Gran Vía 143', 'Carballo', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6485.png'), 
      (6486, 'Estadio Príncipe Felipe', 'Carretera Rute de La Plata', 'Cáceres', 'Spain', 14000, 'grass', 'https://media.api-sports.io/football/venues/6486.png'), 
      (6487, 'Campo do Vao', 'Estrada do Vao, Fontenias', 'Vigo', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6487.png'), 
      (6488, 'Estadio Eusebio Arce', 'Barrio Arenas, 37, Barrio de Escobedo Arenas', 'Escobedo de Camargo', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6488.png'), 
      (6489, 'Estadio Municipal de La Albuera', 'Ciudad Deportiva de La Albuera', 'Segovia', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6489.png'), 
      (12287, 'Estadio Municipal Luis Ramos', 'Calle Reina Sofía 3', 'Guijuelo', 'Spain', 1700, 'artificial turf', 'https://media.api-sports.io/football/venues/12287.png'), 
      (6491, 'Estadio Municipal El Mazo', 'C. Severo Ochoa', 'Haro', 'Spain', 4300, 'artificial turf', 'https://media.api-sports.io/football/venues/6491.png'), 
      (12463, 'Estadio Can Misses – Power Electronic', 'Calle Campanitx, 27', 'Ibiza', 'Spain', 6500, 'artificial turf', 'https://media.api-sports.io/football/venues/12463.png'), 
      (6493, 'Estadio Papa Luna', null, 'Illueca', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6493.png'), 
      (6494, 'Estadio Municipal de Hospitalet de Llobregat', 'Carrer de la Feixa Llarga', 'L&apos;Hospitalet de Llobregat', 'Spain', 6294, 'grass', 'https://media.api-sports.io/football/venues/6494.png'), 
      (12723, 'Estadi Olímpic Camilo Cano', 'Apartado de Correos 11, Partida Muixara', 'La Nucia', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/12723.png'), 
      (6496, 'Campo San Lorenzo', null, 'Laredo', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6496.png'), 
      (6497, 'Estadio Navalcarbón', 'Avenida Nuestra Sra. Retamar 16', 'Las Rozas de Madrid', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6497.png'), 
      (6498, 'Estadio Las Callejas', 'Calle Las Callejas', 'Villaviciosa', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6498.png'), 
      (6499, 'Estadio Sarriena', 'Sarriena Auzoa 49, Barrio de Sarriena', 'Leioa', 'Spain', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/6499.png'), 
      (6500, 'Estadio Municipal de Linarejos', 'Avenida 1º de Mayo', 'Linares', 'Spain', 10000, 'grass', 'https://media.api-sports.io/football/venues/6500.png'), 
      (6501, 'Estadio Municipal de Llagostera', 'Avinguda de l&apos;Esport', 'Llagostera', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6501.png'), 
      (6502, 'Estadi Municipal de Miramar', 'Plaza Miramar', 'Luanco', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6502.png'), 
      (1844, 'Estadio Olímpico Carlos Iturralde Rivero', 'Colonias, Calle 14', 'Mérida', 'Spain', 21050, 'grass', 'https://media.api-sports.io/football/venues/1844.png'), 
      (12309, 'Camp de Futbol Municipal Pla de Baix', 'Carrer de França, 32', 'Olot', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12309.png'), 
      (6505, 'Estadio Municipal Los Arcos', 'Camino Viejo de Molins', 'Orihuela', 'Spain', 7000, 'grass', 'https://media.api-sports.io/football/venues/6505.png'), 
      (6506, 'Campo Municipal del Santa Eulalia del Río', 'Lugar Barri Sa Rota Den Pere Cardona', 'Ibiza', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6506.png'), 
      (6507, 'Campo San Francisco', 'Avenida de Tuleda', 'Tafalla', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6507.png'), 
      (6508, 'Estadio Municipal de Pasarón', 'Calle de Luis Otero', 'Pontevedra', 'Spain', 16500, 'grass', 'https://media.api-sports.io/football/venues/6508.png'), 
      (6509, 'Estadio La Florida', 'Guipuzcoa 2', 'Portugalete', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6509.png'), 
      (6510, 'Estadio Municipal de A Malata', 'Calle de la Malata', 'Ferrol', 'Spain', 12043, 'grass', 'https://media.api-sports.io/football/venues/6510.png'), 
      (6511, 'Estadio Nuevo Colombino', 'Avenida del Decano del Fútbol Espanol', 'Huelva', 'Spain', 19860, 'grass', 'https://media.api-sports.io/football/venues/6511.png'), 
      (6512, 'Estadio Municipal Nuevo Matapiñonera', 'Avenida Matapiñonera', 'San Sebastián de los Reyes', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6512.png'), 
      (6513, 'Estadio Las Llanas', 'Alameda de Las Llanas', 'Sestao', 'Spain', 8905, 'grass', 'https://media.api-sports.io/football/venues/6513.png'), 
      (6514, 'Estadio Paquito Jiménez', null, 'Socuéllamos', 'Spain', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/6514.png'), 
      (6515, 'Campo de Fútbol Juan Guedes', 'Calle Alfonso de Armas Ayala', 'Las Palmas de Gran Canaria', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6515.png'), 
      (6516, 'Estadio Municipal de Tarazona', 'Avenida La Paz', 'Tarazona', 'Spain', 2200, 'grass', 'https://media.api-sports.io/football/venues/6516.png'), 
      (6517, 'Campo Nuevo Municipal', 'Camino de Herencia', 'Villarrubia de los Ojos', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6517.png'), 
      (6518, 'Estadio Ruta de la Plata', 'Carretera de Salamanca', 'Zamora', 'Spain', 7818, 'grass', 'https://media.api-sports.io/football/venues/6518.png'), 
      (6574, 'Estadio Municipal de Villafranca de los Barros', null, 'Villafranca de los Barros', 'Spain', 5500, 'grass', 'https://media.api-sports.io/football/venues/6574.png'), 
      (6665, 'Campo de Fútbol Municipal de Barreiro', 'Avenida de Ramón Nieto 326, Barreiro', 'Vigo', 'Spain', 4500, 'grass', 'https://media.api-sports.io/football/venues/6665.png'), 
      (6666, 'Ciudad Deportiva de Getafe - Campo 2 (main)', 'Calle Teresa de Calcuta', 'Getafe', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6666.png'), 
      (6667, 'Campo de Fútbol Municipal de Boadilla del Monte', 'Carretera Boadilla a Pozuelo, Km 1,4', 'Boadilla del Monte', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6667.png'), 
      (6668, 'Anexo Gran Canaria', 'Calle de los Fondos de Segura', 'Las Palmas de Gran Canaria', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6668.png'), 
      (6669, 'Estadio Alfredo Di Stéfano', 'Ciudad Deportiva del Real Madrid, Valdebebas', 'Madrid', 'Spain', 6500, 'grass', 'https://media.api-sports.io/football/venues/6669.png'), 
      (6670, 'Estadio El Requexón', null, 'Oviedo', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6670.png'), 
      (6671, 'Escuela de Fútbol de Mareo', 'Escuela de Fútbol de Mareo, Leorio', 'Gijón', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6671.png'), 
      (6672, 'Estadio Municipal de Gobela', 'Luis Lopez Oses Kalea, 1', 'Getxo', 'Spain', 1221, 'artificial turf', 'https://media.api-sports.io/football/venues/6672.png'), 
      (12288, 'Instalaciones de Lezama Campo 2', 'Calle Garaioltza Auzoa 147', 'Lezama', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/12288.png'), 
      (6674, 'Estadio Municipal de El Plantío', 'Calle del Dos de Mayo', 'Burgos', 'Spain', 12200, 'grass', 'https://media.api-sports.io/football/venues/6674.png'), 
      (6675, 'Ciudad Deportiva José Luis Compañón', 'Carretera N-I', 'Vitoria-Gasteiz', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6675.png'), 
      (6676, 'Estadio Merkatondoa', 'Calle de Merkatondoa', 'Lizarra', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/6676.png'), 
      (6677, 'Instalaciones Deportivas de Tajonar', 'Paraje Beroa', 'Tajonar', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/6677.png'), 
      (6678, 'Estadio Zubieta XXI', 'Paseo del Hipodromo', 'Lasarte-Oria', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6678.png'), 
      (6679, 'Estadio Gal', 'Calle Patricio Arabolaza 2', 'Irún', 'Spain', 6344, 'grass', 'https://media.api-sports.io/football/venues/6679.png'), 
      (6680, 'Campo 1 Anexos del José Zorrilla hierba natural', 'Avenida del Mundial 82', 'Valladolid', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6680.png'), 
      (6681, 'Estadio El Helmántico', 'Carratera De Zamora, Villares de la Reina', 'Salamanca', 'Spain', 17341, 'grass', 'https://media.api-sports.io/football/venues/6681.png'), 
      (6682, 'Estadio de Luchán', 'Calle Prolongacion Bomberos, 2', 'Ejea de los Caballeros', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6682.png'), 
      (6683, 'Ciutat Esportiva Dani Jarque', 'Carretera de Mataró', 'San Adrián de Besós', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/6683.png'), 
      (6684, 'Ciudad Deportiva de Buñol - Campo 1', 'Avenida de Vicente Blasco Ibáñez', 'Buñol', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6684.png'), 
      (6685, 'Estadio Municipal Sagnier', 'Carrer de Roure', 'El Prat de Llobregat', 'Spain', 500, 'artificial turf', 'https://media.api-sports.io/football/venues/6685.png'), 
      (6686, 'Estadi de la Nova Creu Alta', 'Plaça Olímpia 1', 'Sabadell', 'Spain', 14950, 'grass', 'https://media.api-sports.io/football/venues/6686.png'), 
      (12312, 'Estadio Antonio Puchades (Ciudad Deportiva Valencia)', 'Carretera Mas Camarena', 'Paterna', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/12312.png'), 
      (6688, 'Ciudad Deportiva del Villarreal', 'Ronda Sudoeste de Vila-Real', 'Villarreal', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6688.png'), 
      (6689, 'Estadio Municipal de La Línea de la Concepción', 'Avenida de Principe Asturias', 'La Línea de la Concepción', 'Spain', 18500, 'artificial turf', 'https://media.api-sports.io/football/venues/6689.png'), 
      (6690, 'Estadio Nuevo Mirador', 'Poligono de la Menacha', 'Algeciras', 'Spain', 8209, 'grass', 'https://media.api-sports.io/football/venues/6690.png'), 
      (6691, 'Campo Ramón Blanco Rodríguez', 'Barriada Meadero de la Reina', 'Puerto Real', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6691.png'), 
      (6692, 'Ciudad Deportiva del Granada CF', 'Crta. de Alfacar', 'Granada', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6692.png'), 
      (6693, 'Estadio Iberoamericano 2010', 'Calle de los Carpinteros', 'San Fernando', 'Spain', 12000, 'grass', 'https://media.api-sports.io/football/venues/6693.png'), 
      (6694, 'Estadio El Palmar', 'Carretera del Puerto', 'Sanlúcar de Barrameda', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6694.png'), 
      (6695, 'Estadio Nuestra Señora de la Caridad', 'Calle de la Senda Molinera', 'Villarrobledo', 'Spain', 5500, 'grass', 'https://media.api-sports.io/football/venues/6695.png'), 
      (6696, 'Campo do Morrazo', 'Avenida de Lugo', 'Cangas', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/6696.png'), 
      (6697, 'Estadio de Espiñedo', 'Rúa Forno Vello', 'O Carballiño', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6697.png'), 
      (6698, 'Estadio A Lomba', 'Avenida Matonsinhos', 'Vilagarcía de Arousa', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6698.png'), 
      (6699, 'Estadio Do Viso', 'Rúa do Viso, 53', 'Arzúa', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6699.png'), 
      (6700, 'Estadio O Poboado', 'Calle de Pardo Bazan', 'Puentes de García Rodríguez', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/6700.png'), 
      (6701, 'Campo de Fútbol Municipal de Calabagueiros', 'Río Mariñán, s/n', 'O Barco de Valdeorras', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6701.png'), 
      (6702, 'Campo Municipal de Santa Mariña', 'Rúa Campo de Fútbol', 'Redondela', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6702.png'), 
      (6703, 'Ciudad Deportiva de Abegondo', 'Agra de Marces, San Tirso de Mabegondo, Abegondo', 'La Coruña', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6703.png'), 
      (6704, 'Campo Municipal do Concello da Estrada', null, 'A Estrada', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6704.png'), 
      (6705, 'Estadio O Couto', 'Calle Estadio de Fútbol', 'Ourense', 'Spain', 5625, 'grass', 'https://media.api-sports.io/football/venues/6705.png'), 
      (6706, 'Campo Porta Santa', 'Carretera Soandres, 16', 'A Laracha', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6706.png'), 
      (6707, 'Estadio do Polvorín', 'Rúa Alcalde Xosé Novo Freire, 8', 'Lugo', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6707.png'), 
      (6708, 'Campo Municipal de Fútbol Rodrigo García Vizoso', 'Rúa de Galileo Galilei', 'La Coruña', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6708.png'), 
      (6709, 'Estadio Alcalde Manuel Candocia', null, 'As Somozas', 'Spain', 800, 'grass', 'https://media.api-sports.io/football/venues/6709.png'), 
      (6710, 'Estadio Municipal A Magdalena', 'Carretera de Playa Fluvial', 'Villalba', 'Spain', 2000, null, 'https://media.api-sports.io/football/venues/6710.png'), 
      (6711, 'Estadio Municipal Hermanos Antuña', 'Calle Villaviciosa', 'Mieres del Camino', 'Spain', 7500, 'artificial turf', 'https://media.api-sports.io/football/venues/6711.png'), 
      (6712, 'Estadio La Cruz', 'Parque de Los Pericones', 'Gijón', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6712.png'), 
      (6713, 'Estadio Santianes', null, 'Colunga', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6713.png'), 
      (6714, 'Estadio Alejandro Ortea', 'Calle Los Riegos', 'Noreña', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6714.png'), 
      (6715, 'Estadio Juan Antonio Alvarez Rabanal', 'Lugar Ponton de Vaqueros, 201', 'Oviedo', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6715.png'), 
      (6716, 'Estadio Santa Cruz', 'Avenida Eduardo Castro', 'Gijón', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6716.png'), 
      (6717, 'Estadio Nuevo Nalón', null, 'El Entrego', 'Spain', 1200, 'artificial turf', 'https://media.api-sports.io/football/venues/6717.png'), 
      (12698, 'Estadio ALTOSDEMONTECERRAO.COM - El Sotón', 'Caserio los Campos, 3', 'Pola de Lena', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12698.png'), 
      (6719, 'Campo Municipal de Fútbol Pepe Quimarán', 'Avenida Prudencio González, 81', 'Llanera', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6719.png'), 
      (6720, 'Estadio San José', 'Avenida de San José', 'Llanes', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6720.png'), 
      (6721, 'Estadio Marqués de La Vega de Anzo', 'Avda. de los Deportes S/N', 'Grado, Asturias', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/6721.png'), 
      (6722, 'Estadio Tabiella', 'Calle Navarro y Raíces, Tabiella', 'Avilés', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6722.png'), 
      (6723, 'Estadio Santa Catalina', 'Barrio Santa Catalina', 'Pravia', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6723.png'), 
      (6724, 'Estadio Román Suárez Puerta', 'Calle de Juan Ochoa', 'Avilés', 'Spain', 5200, 'grass', 'https://media.api-sports.io/football/venues/6724.png'), 
      (6725, 'Estadio El Florán', 'Avenida del Florán', 'San Martín del Rey Aurelio', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6725.png'), 
      (6726, 'Estadio El Bayu', 'calle Ildefonso Sánchez del Río 13', 'Pola de Siero', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6726.png'), 
      (6727, 'Estadio El Candín', null, 'Tuilla', 'Spain', 2800, 'artificial turf', 'https://media.api-sports.io/football/venues/6727.png'), 
      (6728, 'Estadio Vallobín', 'Dr. Solís Cajigal, Vallobín', 'Oviedo', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6728.png'), 
      (6729, 'Estadio Juan Hormaechea', 'La Albericia y el Bezana', 'Santander', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6729.png'), 
      (6730, 'Estadio Solvay', 'Avenida Solvay, Barreda', 'Torrelavega', 'Spain', 5100, 'grass', 'https://media.api-sports.io/football/venues/6730.png'), 
      (6731, 'Estadio Municipal', 'Plaza de Cantabria 2', 'Santa Cruz de Bezana', 'Spain', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/6731.png'), 
      (6732, 'Campo de Fútbol El Ansar', 'Calle Camino Real, 79B', 'Cartes', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6732.png'), 
      (4158, 'Warner Park Football Stadium', 'Victoria Road', 'Basseterre', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/4158.png'), 
      (6733, 'Estadio El Pilar', 'Calle Paco Gento', 'Guarnizo', 'Spain', 5625, 'grass', 'https://media.api-sports.io/football/venues/6733.png'), 
      (6734, 'Estadio La Albericia', 'Avenida del Deporte', 'Santander', 'Spain', 1100, 'grass', 'https://media.api-sports.io/football/venues/6734.png'), 
      (6735, 'Estadio Baceñuela', 'Barrio Baceña', 'Galizano, Ribamontán al Mar', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6735.png'), 
      (6736, 'Estadio El Castañal', 'Bo. el Castañal', 'Selaya', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6736.png'), 
      (6737, 'Campo San Pedro', 'Barrio de Castillo Siete Villas', 'Castillo Siete Villas', 'Spain', 500, 'artificial turf', 'https://media.api-sports.io/football/venues/6737.png'), 
      (6738, 'Campo Municipal La Estación', 'La Estación, Solares', 'Medio Cudeyo', 'Spain', 1900, 'artificial turf', 'https://media.api-sports.io/football/venues/6738.png'), 
      (6739, 'Estadio Vallegon', 'P.l. Vallegón 1', 'Cantabria', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6739.png'), 
      (6740, 'Estadio Juan María Parés', null, 'Cabezón de La Sal', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6740.png'), 
      (6741, 'Estadio Municipal Bárcena de Pie de Concha', 'CA-716, 6', 'Bárcena de Pie de Concha', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6741.png'), 
      (6742, 'Campo Municipal Santa Ana', 'Avenida del Estadio, Tanos', 'Torrelavega', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6742.png'), 
      (6743, 'Estadio La Vidriera', 'Barrio de la Fábrica', 'Vioño de Piélagos', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6743.png'), 
      (11004, 'Campo Ellakuri', 'Goienuri Kalea', 'Laudio', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/11004.png'), 
      (6745, 'Estadio Ariznabarra', 'Etxezarra kalea/Calle Etxezarra', 'Vitoria-Gasteiz', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6745.png'), 
      (6746, 'Campo de Fútbol La Baluga', null, 'Balmaseda', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6746.png'), 
      (6747, 'Estadio Pedro López Cortázar', 'Calle de Basozelai, Barrio de Basozelai', 'Basauri', 'Spain', 8500, 'grass', 'https://media.api-sports.io/football/venues/6747.png'), 
      (6748, 'Estado Municipal de Loinaz', 'Calle de Igartza-Oleta', 'Beasain', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/6748.png'), 
      (6749, 'Campo de Fútbol de Etxezuri', null, 'Bilbao', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6749.png'), 
      (6750, 'Estadio El Malecón Muskiz', 'Calle del Crucero', 'Muskiz', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6750.png'), 
      (6751, 'Estadio Garmendipe', null, 'Azpeitia', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6751.png'), 
      (6752, 'Estadio Don Bosco', 'Carretera de San Marcos', 'Pasajes-Pasaia', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6752.png'), 
      (6754, 'Campo de Fútbol de Adurtzabal', 'Iturritxu Kalea, 8', 'Vitoria-Gasteiz', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6754.png'), 
      (6755, 'Estadio San Jorge', 'Calle de Pajares', 'Santurtzi', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6755.png'), 
      (6756, 'Estadio Mallona', 'Calle Calzadas de Mallona', 'Bilbao', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6756.png'), 
      (6757, 'Campo Lorenzo Hurtado de Saratxo', 'Calle Padura', 'Sodupe', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6757.png'), 
      (6758, 'Estadio Iparralde', 'Iparralde, 2', 'Urduliz', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6758.png'), 
      (6759, 'Camp Nou de Banyoles', 'Passeig Darder', 'Banyoles', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6759.png'), 
      (6760, 'Estadio Els Canyars', 'Calle de la Església 121', 'Castelldefels', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6760.png'), 
      (12464, 'Estadi Municipal La Bòbila-Pinetons', 'Carrer Galicia', 'Cerdanyola del Vallès', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12464.png'), 
      (6762, 'Estadio Municipal de Vilatenim', 'Barrio de Vilatenim', 'Figueras', 'Spain', 9472, 'artificial turf', 'https://media.api-sports.io/football/venues/6762.png'), 
      (6763, 'Campo Municipal Carrer Girona', 'Carrer de Girona 54', 'Granollers', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6763.png'), 
      (6764, 'Estade Feliu i Codina', 'Carrer del Canigó, Horta', 'Barcelona', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6764.png'), 
      (6765, 'Estadi Cem Les Comes', 'Carrer de Carles Riba, 65', 'Igualada', 'Spain', 4500, 'artificial turf', 'https://media.api-sports.io/football/venues/6765.png'), 
      (6766, 'Estadio El Congost', 'Carrer del Dos de Maig, 138', 'Manresa', 'Spain', 3660, 'artificial turf', 'https://media.api-sports.io/football/venues/6766.png'), 
      (6767, 'Estadio Municipal de Peralada', 'Passeig Catalunya', 'Peralada', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6767.png'), 
      (6768, 'Estadio Municipal de La Pobla de Mafumet', null, 'La Pobla de Mafumet', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6768.png'), 
      (6769, 'Camp de Futbol Municipal Ca n''Anglada', 'Av. del Vallès, 552', 'Tarrasa', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6769.png'), 
      (6770, 'Nou Estadi Municipal de Les Grases', 'Carretera Sansón / Carrer Mataro, Sant Feliu de Llobregat', 'Barcelona', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6770.png'), 
      (6771, 'Camp de Futbol Energia', 'Carrer de l&apos;Energia, 35', 'Barcelona', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6771.png'), 
      (6772, 'Estadi Olímpic de Terrassa', 'Carrer des Jocs Olímpics', 'Terrassa', 'Spain', 11500, 'grass', 'https://media.api-sports.io/football/venues/6772.png'), 
      (6773, 'Camp Municipal d''Esports', 'Carrer Bodegues Torres, 2640', 'Vilafranca del Penedès', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6773.png'), 
      (6774, 'Estadio Municipal Xevi Ramon', 'vinguda Arquitecte Eduard Ferres 155', 'Vilassar de Mar', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6774.png'), 
      (6775, 'Ciudad Deportiva Pamesa Cerámica', 'Camí Segon Sedeny s/n', 'Villarreal', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6775.png'), 
      (6776, 'Estadio El Fornás', 'Avenida Camp de Morvedre, 38 Puerto Sagunto', 'El Port de Sagunt', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6776.png'), 
      (6777, 'Campo Municipal El Collao', 'Calle Oliver', 'Alcoy', 'Spain', 4850, 'grass', 'https://media.api-sports.io/football/venues/6777.png'), 
      (6778, 'Estadio Luis Suñer Picó', 'Avenida de los Desportes', 'Alzira', 'Spain', 8000, 'grass', 'https://media.api-sports.io/football/venues/6778.png'), 
      (6779, 'Campo De Futbol El Regit', 'Vall d&apos;Albaida', 'Atzeneta d&apos;Albaida', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6779.png'), 
      (6780, 'Campo Municipal Emilio Cuquerella', 'Calle Maestro Don José Moscardo S/N', 'Benigànim', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6780.png'), 
      (6781, 'Estadio Enrique Miralles', null, 'Crevillent', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/6781.png'), 
      (6782, 'Estadio José Díez Iborra (Ciudad Deportiva de Elche)', 'Calle Confrides 2', 'Elche', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6782.png'), 
      (6783, 'Estadio Municipal Nuevo Pepico Amat', 'Calle Heidelberg / Avenida de Ronda', 'Elda', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6783.png'), 
      (12313, 'Polideportivo Juan Antonio Samaranch', 'C. Paraguay, 6', 'Alacant', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12313.png'), 
      (6785, 'Ciudad Deportiva de San Vicente del Raspeig', 'Avenida Dénia 2', 'San Vicente del Raspeig', 'Spain', 3800, 'artificial turf', 'https://media.api-sports.io/football/venues/6785.png'), 
      (6786, 'Estadio La Magdalena', 'Avenida del Médico Enrique Sala', 'Novelda', 'Spain', 6500, 'grass', 'https://media.api-sports.io/football/venues/6786.png'), 
      (6787, 'Estadio La Murta', 'Avinguda de la Murta', 'Xàtiva', 'Spain', 9000, 'artificial turf', 'https://media.api-sports.io/football/venues/6787.png'), 
      (6788, 'Estadio Municipal Gerardo Salvador', 'Calle Manises 23', 'Paterna', 'Spain', 8000, 'grass', 'https://media.api-sports.io/football/venues/6788.png'), 
      (12314, 'Estadio Polideportivo Municipal de Sedaví', 'Carrer Fernando Baixauli Chornet, s/n', 'Sedaví', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12314.png'), 
      (6790, 'Estadio Nou Camp de Morvedre', 'Calle Petres 1200', 'Sagunt', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6790.png'), 
      (6791, 'Complejo Deportivo Municipal Vicent Morera', 'Av. de Gandía, 22', 'Silla', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6791.png'), 
      (6792, 'Estadio Hermanos Albiol', 'Avenida del Polideportivo', 'Ribarroja del Turia', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/6792.png'), 
      (6793, 'Polideportivo Santa Ana', 'Calle de Afueras a Valverde, Barrio Fuencarral', 'Madrid', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6793.png'), 
      (12699, 'Estadio Municipal de Los Prados', 'Avenida Juan Carlos I', 'Parla', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/12699.png'), 
      (11016, 'Campo De Fútbol Paracuellos de Jarama', 'Av. de los Deportes', 'Paracuellos de Jarama', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/11016.png'), 
      (6796, 'Campo 2 Alcorcón', 'Avenida de Pablo Iglesias', 'Alcorcón', 'Spain', 1200, 'artificial turf', 'https://media.api-sports.io/football/venues/6796.png'), 
      (6797, 'Estadio Amelia del Castillo', 'Calle Doña Manolita', 'Pinto', 'Spain', 1600, 'artificial turf', 'https://media.api-sports.io/football/venues/6797.png'), 
      (6798, 'Estadio La Mina de Carabanchel', 'Calle Monseñor Oscar Romero 39, Carabanchel', 'Madrid', 'Spain', 6000, 'artificial turf', 'https://media.api-sports.io/football/venues/6798.png'), 
      (6799, 'Campo de Fútbol Castroserna', 'Calle de Castroserna', 'Madrid', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6799.png'), 
      (6800, 'Estadio Anexo Butarque', 'Calle Arquitectura', 'Leganés', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6800.png'), 
      (6801, 'Estadio Municipal de El Soto', 'Avenida de los Deportes', 'Móstoles', 'Spain', 14000, 'grass', 'https://media.api-sports.io/football/venues/6801.png'), 
      (6802, 'Estadio Valle de las Cañas', 'Camino de Alcorcón a Pozuelo', 'Pozuelo de Alarcón', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6802.png'), 
      (6803, 'Estadio Municipal Virgen del Val', 'Avenida de Virgen de Val', 'Alcalá de Henares', 'Spain', 8000, 'grass', 'https://media.api-sports.io/football/venues/6803.png'), 
      (6804, 'Ciudad Deportiva Rayo Vallecano Campo 5 (Stadium)', 'Calle del Rayo Vallecano de Madrid 1-37', 'Madrid', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6804.png'), 
      (6805, 'Estadio Municipal Santiago del Pino', 'Plaza San Fernando', 'San Fernando de Henares', 'Spain', 3300, 'artificial turf', 'https://media.api-sports.io/football/venues/6805.png'), 
      (6806, 'Estadio Las Veredillas', 'Calle Turin 12', 'Torrejón de Ardoz', 'Spain', 1300, 'artificial turf', 'https://media.api-sports.io/football/venues/6806.png'), 
      (6807, 'Estadio La Canaleja', 'Avenida de los Castillos', 'Alcorcón', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6807.png'), 
      (6808, 'Campo García de la Mata', 'Calle Ramírez de Arellano', 'Madrid', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6808.png'), 
      (6809, 'Estadio Boetticher', 'Paseo Talleres 1', 'Madrid', 'Spain', 500, 'artificial turf', 'https://media.api-sports.io/football/venues/6809.png'), 
      (6810, 'Estadio Municipal de la Arboleda', 'Paseo de la Arboleda', 'Almazán', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6810.png'), 
      (6811, 'Estadio El Montecillo', null, 'Aranda de Duero', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/6811.png'), 
      (6812, 'Estadio La Eragudina', 'Paseo La Eragudina', 'Astorga', 'Spain', 2332, 'grass', 'https://media.api-sports.io/football/venues/6812.png'), 
      (6813, 'Estadio Las Salinas', 'Carretera Madrid - Coruña, km 182', 'Tordesillas', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/6813.png'), 
      (6814, 'Estadio La Devesa', 'Paraje La Devesa', 'Bembibre', 'Spain', 2750, 'grass', 'https://media.api-sports.io/football/venues/6814.png'), 
      (6815, 'Nuevo Campo San Amaro', 'C/ José Mª Villacián Rebollo', 'Burgos', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6815.png'), 
      (6816, 'Ciudad Deportiva de Castañares', 'Calle Obidus, Castañares', 'Burgos', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6816.png'), 
      (6817, 'Estadio La Nueva Balastera', 'Avenida de Cataluña 12', 'Palencia', 'Spain', 12500, 'grass', 'https://media.api-sports.io/football/venues/6817.png'), 
      (6818, 'Área Deportiva Municipal Puente Castro', 'Autovía León-Astorga', 'León', 'Spain', 10000, 'grass', 'https://media.api-sports.io/football/venues/6818.png'), 
      (6819, 'Estadio La Llanera', 'Calle La Llanera', 'La Bañeza', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6819.png'), 
      (6820, 'Campo de Fútbol El Hospital', 'Ctra de Torrecaballeros', 'San Ildefonso', 'Spain', 1200, 'grass', 'https://media.api-sports.io/football/venues/6820.png'), 
      (6821, 'Campo Los Dominicos', null, 'La Virgen Del Camino', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6821.png'), 
      (6823, 'Ciudad Deportiva Francisco Rubio Garcés', 'Calle de Burgos Km. 351', 'Soria', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6823.png'), 
      (6824, 'Estadio Municipal Adolfo Suárez', 'Carratera de Sonsoles', 'Ávila', 'Spain', 5500, 'grass', 'https://media.api-sports.io/football/venues/6824.png'), 
      (6825, 'Estadio Municipal Alfonso San Casto', 'Avenida Prof. Enrique  Tierno Galván', 'Santa Marta de Tormes', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6825.png'), 
      (6826, 'Estadio Vivar Téllez', null, 'Vélez-Málaga', 'Spain', 2100, 'artificial turf', 'https://media.api-sports.io/football/venues/6826.png'), 
      (6827, 'Estadio Municipal Los Manantiales', 'Avenida Los Manantiales', 'Alhaurín de la Torre', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6827.png'), 
      (6828, 'Estadio El Maulí', 'Calle Escultor Diego Marquez', 'Antequera', 'Spain', 7000, 'grass', 'https://media.api-sports.io/football/venues/6828.png'), 
      (6829, 'Estadio Matías Prats', 'Calle Fuente de Marmol', 'Torredonjimeno', 'Spain', 4500, 'grass', 'https://media.api-sports.io/football/venues/6829.png'), 
      (6830, 'Estadio de Municipal Santo Domingo', 'Calle Ángel Maeso, Santo Domingo', 'El Ejido', 'Spain', 7885, 'grass', 'https://media.api-sports.io/football/venues/6830.png'), 
      (6831, 'Estadio San Ignacio', 'Carretera de Almería, El Palo', 'Málaga', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6831.png'), 
      (6832, 'Estadio Municipal Miguel Moranto', 'Carretera de la Estacion', 'Huétor Tájar', 'Spain', 520, 'artificial turf', 'https://media.api-sports.io/football/venues/6832.png'), 
      (6833, 'Estadio Las Viñas', 'Av. Gustavo Adolfo Bécquer, 65', 'Huétor Vega', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6833.png'), 
      (6834, 'Estadio Municipal Medina Lauxa', 'Avenida de la Estación 2', 'Loja', 'Spain', 2250, 'artificial turf', 'https://media.api-sports.io/football/venues/6834.png'), 
      (6835, 'Estadio Polideportivo La Juventud', 'Calle de San Marcos', 'Mancha Real', 'Spain', 3700, 'artificial turf', 'https://media.api-sports.io/football/venues/6835.png'), 
      (6836, 'Ciudad Deportiva Maracena', 'Avenida José Comino', 'Maracena', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6836.png'), 
      (6837, 'Estadio Escribano Castilla', 'Calle San Marcos', 'Motril', 'Spain', 5400, 'grass', 'https://media.api-sports.io/football/venues/6837.png'), 
      (12325, 'Ciudad Deportiva de El Viso', 'Avenida de Jenofonte', 'Málaga', 'Spain', 1300, 'grass', 'https://media.api-sports.io/football/venues/12325.png'), 
      (6839, 'Estadio de la Juventud Emilio Campra', 'Calle Estadio', 'Almería', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6839.png'), 
      (6840, 'Polideportivo Municipal Abdon Martínez Fariñas', 'Calle Víctor Pradera, 35', 'Torreperogil', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6840.png'), 
      (6841, 'Estadio Antonio Barbadillo', 'Carretera de Arcos El Bosque', 'Arcos de la Frontera', 'Spain', 2900, 'grass', 'https://media.api-sports.io/football/venues/6841.png'), 
      (6842, 'Estadio Ciudad de Lucena', 'Polígono industrial Los Polvillares', 'Lucena', 'Spain', 5076, 'artificial turf', 'https://media.api-sports.io/football/venues/6842.png'), 
      (6843, 'Estadio Municipal Jose António Pérez Ureba', 'Carretra de los Militares', 'Conil de la Frontera', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6843.png'), 
      (6844, 'Estadio Guadalquivir', null, 'Coria del Río', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6844.png'), 
      (6845, 'Estadio José Juan Romero', 'Calle Santa Fe 5', 'Gerena', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6845.png'), 
      (6846, 'Estadio San Rafael', 'Avenida Dña. Rosa García López-Cespero', 'Los Barrios', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6846.png'), 
      (12610, 'Estadio Municipal Pozoblanco', 'Calle del Pintor Goya', 'Pozoblanco', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/12610.png'), 
      (6848, 'Estadio Municipal Manuel Polinario', 'Calle Montalbán, 17, Parque Príncipe de Asturias', 'Puente Genil', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6848.png'), 
      (6849, 'Ciudad Deportiva Luis de Sol', 'Avenida de Italia', 'Sevilla', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6849.png'), 
      (6850, 'Estadio Municipal Alcalde Navarro Flores', 'Avenida de la Diputación 164', 'Rota', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6850.png'), 
      (6851, 'Estadio Municipal Ciudad de Lepe', 'Avenida de Andalucía', 'Lepe', 'Spain', 3512, 'grass', 'https://media.api-sports.io/football/venues/6851.png'), 
      (6852, 'Estadio San Juan Bosco', 'Paseo de Consolación, s/n. Utrera', 'Sevilla', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6852.png'), 
      (6853, 'Estadio de La Juventud', 'Avenida de Blas Infante', 'Jerez de la Frontera', 'Spain', 8000, 'grass', 'https://media.api-sports.io/football/venues/6853.png'), 
      (6854, 'Estadio Municipal de Chapín', 'Avenida del Polo', 'Jerez de la Frontera', 'Spain', 20742, 'grass', 'https://media.api-sports.io/football/venues/6854.png'), 
      (6855, 'Estadio Municipal San Pablo', 'Calle de Cesteria', 'Écija', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/6855.png'), 
      (6856, 'Estadi Municipal Els Arcs', 'Via de Corneli Àtic', 'Mallorca', 'Spain', 1750, 'artificial turf', 'https://media.api-sports.io/football/venues/6856.png'), 
      (6857, 'Estadio Miquel Pons', 'Carrer del Rector Rafael Sabater', 'Mallorca', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6857.png'), 
      (6858, 'Estadio Municipal Coll d’en Rebassa', 'Ca&apos;n Caimari 11, Coll d’en Rebassa', 'Mallorca', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6858.png'), 
      (6859, 'Nou Camp de Inca', 'Carretera de Sineu', 'Inca', 'Spain', 10000, 'grass', 'https://media.api-sports.io/football/venues/6859.png'), 
      (6860, 'Son Quint Estadio', 'Calle sin Nombre 5, 3', 'Esporles', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6860.png'), 
      (6861, 'Estadio Es Torrentó', 'Ctra. Porto Colom', 'Mallorca', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6861.png'), 
      (6862, 'Estadio Municipal de Son Ferriol', null, 'Mallorca', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6862.png'), 
      (6863, 'Estadio Municipal', null, 'Sant Francesc de Formentera', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6863.png'), 
      (6864, 'Camp Municipal Es Puig', null, 'Mallorca', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6864.png'), 
      (6865, 'Estadi Son Bibiloni (Antonio Asensio)', 'Ma-11', 'Palma de Mallorca', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6865.png'), 
      (12330, 'Na Capellera', 'Ronda de l&apos;Institut, 52', 'Mallorca', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12330.png'), 
      (6867, 'Polideportivo Municipal de Magalluf', 'Avenida Palmere 23, Magaluf', 'Mallorca', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/6867.png'), 
      (6868, 'Estadio Sant Antoni', null, 'Sant Antoni de Portmany', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6868.png'), 
      (6869, 'Estadio Municipal de Sant Rafel', null, 'Ibiza', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6869.png'), 
      (6870, 'Camp Municipal de Futbol Son Flor', 'Calle Josep Escala 15', 'Palma', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6870.png'), 
      (6871, 'Estadio Municipal de Santanyí', 'Carrer Bernat Vidal i Tomàs', 'Santanyí (Mallorca', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6871.png'), 
      (12331, 'Parque Municipal Sóller', 'Camí de sa figuera', 'Sóller', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12331.png'), 
      (6873, 'Campo Municipal de El Paso', 'Prol. Ronda, 14A', 'El Paso', 'Spain', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/6873.png'), 
      (6874, 'Barranco Las Lajas Campo De Futbol', 'Calle los Andes, 17', 'Tacoronte', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6874.png'), 
      (6875, 'Campo Municipal de Fútbol Clementina de Bello', 'Calle Idelfonso Bello, 1', 'Buzanada', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6875.png'), 
      (6876, 'Estadio de Tasagaya', 'Calle del Poeta Aristides Hernandez Mora, 13', 'Güímar', 'Spain', 3500, 'artificial turf', 'https://media.api-sports.io/football/venues/6876.png'), 
      (6877, 'Estadio Villa Isabel', 'El Fraile', 'Tenerife', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6877.png'), 
      (6878, 'Estadio Municipal de Los Pozos', 'Calle Carretera los Pozos', 'Puerto Rosario', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6878.png'), 
      (6879, 'Ciudad Deportiva de Lanzarote', 'Avenida Alcalde Ginés de la Hoz', 'Lanzarote', 'Spain', 6000, 'grass', 'https://media.api-sports.io/football/venues/6879.png'), 
      (6880, 'Estadio Antonio Domínguez Alfonso', 'Playa de las Américas', 'Tenerife', 'Spain', 7500, 'grass', 'https://media.api-sports.io/football/venues/6880.png'), 
      (6881, 'Campo de Futbol Vega de San Mateo', 'Calle del Agua', 'Vega de San Mateo', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6881.png'), 
      (6882, 'Estadio Argelio Tabares', 'Calle Finca Pastor 3-11', 'Santa Úrsula', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6882.png'), 
      (12339, 'Centro Insular de Atletismo de Tenerife', 'Calle Volcán Birigoyo', 'Santa Cruz de Tenerife', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/12339.png'), 
      (6884, 'Estadio Virgen de Las Nieves', 'Carratera Gral Mirca', 'La Palma', 'Spain', 5500, 'grass', 'https://media.api-sports.io/football/venues/6884.png'), 
      (6885, 'Ciudad Deportiva de Maspalomas', 'Avenida Finnair, Parque Sur', 'Gran Canaria', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6885.png'), 
      (6886, 'Estadio Alfonso Silva', 'Calle de Gustavo Julio Navarro Nieto, La Ballena', 'Las Palmas de Gran Canaria', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/6886.png'), 
      (11045, 'Estadio Las Viñas', 'Calle Mojigato, Cella', 'Vera', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/11045.png'), 
      (12340, 'Estadio El Guiniguada', 'Carretera a los Olivos', 'Gran Canaria', 'Spain', 1100, 'artificial turf', 'https://media.api-sports.io/football/venues/12340.png'), 
      (6889, 'Estadio San Miguel', 'Av. los Escolares', 'Pulpí', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6889.png'), 
      (6890, 'Estadio José Barnés', 'Calle Mar Menor', 'Murcia', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6890.png'), 
      (12465, 'Ciudad Deportiva Gómez Meseguer', 'Calle Londres, Polígono Cabezo Beaza', 'Cartagena', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/12465.png'), 
      (6891, 'Estadio Municipal Ángel Celdrán', 'Calle General Vives', 'El Llano del Beal', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6891.png'), 
      (6892, 'Campo de EDMF Churra', 'Juan Aguilar Amat', 'Murcia', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6892.png'), 
      (6893, 'Estadio El Hornillo', 'Avenida Guillermo Reyna', 'Huércal-Overa', 'Spain', 1785, 'artificial turf', 'https://media.api-sports.io/football/venues/6893.png'), 
      (6894, 'Estadio Las Tejeras', 'Calle Tejeras, Garres y Lages', 'Murcia', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6894.png'), 
      (6895, 'Estadio El Pitín', null, 'San Javier', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6895.png'), 
      (6896, 'Estadio Municipal de Mazarrón', 'Calle Viena, 3', 'Mazarrón', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6896.png'), 
      (6897, 'Estadio Municipal de Mula', 'Camino Curtis, 9', 'Mula', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6897.png'), 
      (6898, 'Estadio Juan Cayuela', 'Calle Olímpico 2', 'Totana', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6898.png'), 
      (6899, 'Estadio Municipal de Llano de Brujas', 'Vereda de los Zapatas', 'Llano de Brujas', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6899.png'), 
      (6900, 'Estadio Campus Universitario', 'Calle Campus Universitario, 18', 'Murcia', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6900.png'), 
      (6901, 'Campo Municipal El Secante', 'Calle San Francisco', 'Alumbres', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6901.png'), 
      (6902, 'Estadio El Mayayo', 'Carril El Mayayo', 'Sangonera la Verde', 'Spain', 1200, 'grass', 'https://media.api-sports.io/football/venues/6902.png'), 
      (6903, 'Estadio El Rubial', 'Calle Electra', 'Águilas', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/6903.png'), 
      (6904, 'Polideportivo Municipal Aceuchal', 'Ctra. Villafranca, 1', 'Aceuchal', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6904.png'), 
      (6905, 'Estadio Municipal de Arroyo de la Luz', null, 'Arroyo de la Luz', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6905.png'), 
      (6906, 'Estadio CD Azuaga', 'Calle Antonio Machado', 'Azuaga', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/6906.png'), 
      (6907, 'Estadio La Isla', 'Calle Cervantes', 'Coria', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6907.png'), 
      (6908, 'Municipal Calamonteño', null, 'Calamonte', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6908.png'), 
      (6909, 'Estadio Manuel Sánchez Delgado', 'Av. Héroes de Baler, 41', 'Cáceres', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6909.png'), 
      (6910, 'Polideportivo Municipal Tomás de la Hera', 'Calle Nicolás Mejias 2', 'Almendralejo', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6910.png'), 
      (6911, 'Estadio Municipal Francisco De Zurbarán', 'Calle Felipe Trigo 21', 'Fuente de Cantos', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6911.png'), 
      (6912, 'Estadio Manuel Calzado Galván', 'Pl. de Toros, 28', 'Jerez de los Caballeros', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6912.png'), 
      (6913, 'Estadio Fernando Robina', 'Av. Ancha de Sevilla', 'Llerena', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6913.png'), 
      (6914, 'Estadio Municipal de Miajadas', 'Carretera del Casar de Miajadas', 'Miajadas', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6914.png'), 
      (6915, 'Estadio Municipal Emilio Macarro Rodriguez', 'Avda. de la Estación, 10', 'Montijo', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6915.png'), 
      (6916, 'Estadio Municipal de Navalmoral de la Mata', 'Ctra. Jarandilla, 2', 'Navalmoral de la Mata', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6916.png'), 
      (6917, 'Ciudad Deportiva de Olivenza', 'Paseo de Hernán Cortés', 'Olivenza', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6917.png'), 
      (6918, 'Ciudad Deportiva de Plasencia', 'Avenida Ciudad Deportiva', 'Plasencia', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6918.png'), 
      (6919, 'Estadio Municipal San Roque', null, 'Valverde de Leganés', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6919.png'), 
      (6920, 'Estadio Municipal Julián García de Guadiana', 'Calle de Francisco de las Casas', 'Trujillo', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6920.png'), 
      (6921, 'Estadio Municipal Primero de Mayo', null, 'Valdivia', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6921.png'), 
      (6922, 'Estadio El Pinar II', null, 'Zizur Nagusia', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6922.png'), 
      (6923, 'Paraje Gilxaurdi', 'Paraje Giltxaurdi', 'Elizondo', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6923.png'), 
      (6924, 'Complejo Deportivo Plazaola', 'Calle Burundegia, 9', 'Lekunberri', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6924.png'), 
      (6925, 'Estadio Lorenzo Goikoa', null, 'Villava', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6925.png'), 
      (6926, 'Estadio Ripagaina', null, 'Burlada', 'Spain', 4000, 'grass', 'https://media.api-sports.io/football/venues/6926.png'), 
      (6927, 'Estadio San Juan', 'Avenida de Navarra', 'Cintruénigo', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6927.png'), 
      (6928, 'Campo CD Corellano', 'Calle Jose Luis Arrese', 'Corella', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6928.png'), 
      (6929, 'Estadio San Francisco Javier', 'Calle de los Donantes de Sangre', 'Navarra', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6929.png'), 
      (6930, 'Estadio Secarales', 'Calle Secarales', 'Fontellas', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6930.png'), 
      (6931, 'Estadio Areta', 'Paraje Ugarrandía', 'Uharte', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6931.png'), 
      (6932, 'Estadio Luis Asarta', 'Avenida de Huertas Mayores', 'Tudela', 'Spain', 1000, null, 'https://media.api-sports.io/football/venues/6932.png'), 
      (6933, 'Estadio San Roque', 'Carretera Cascante', 'Cascante', 'Spain', 1400, 'grass', 'https://media.api-sports.io/football/venues/6933.png'), 
      (10984, 'Campo Bidezarra de Noain', 'Calle Arcos de Noain', 'Noain', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/10984.png'), 
      (6935, 'Estadio San Juan', 'Avenida Sancho el Fuerte', 'Pamplona', 'Spain', 1250, 'artificial turf', 'https://media.api-sports.io/football/venues/6935.png'), 
      (6936, 'Estadio Sotoburu', 'Paraje de Sotoburu', 'Subiza', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6936.png'), 
      (6937, 'Instalaciones Deportivas Chantrea', 'Calle de Imarcoain 44', 'Pamplona', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/6937.png'), 
      (6938, 'Estadio Sarriguren', null, 'Sarriguren', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6938.png'), 
      (6939, 'Estadio Marino Sáenz', null, 'Alberite', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6939.png'), 
      (6940, 'Estadio La Molineta', 'Avenida de La Molineta', 'Alfaro', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6940.png'), 
      (6941, 'Estadio Isla Anguiano', 'Calle de Cenicero a Lerna', 'Anguiano', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6941.png'), 
      (6942, 'Estadio Sendero', 'Avenida de la Cruz Roja', 'Arnedo', 'Spain', 4500, 'grass', 'https://media.api-sports.io/football/venues/6942.png'), 
      (6943, 'Estadio La Isla', 'Calle El Cortijo', 'Logroño', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6943.png'), 
      (6944, 'Estadio La Estrella', null, 'Logroño', 'Spain', 500, null, 'https://media.api-sports.io/football/venues/6944.png'), 
      (6945, 'Estadio Municipal El Soto', 'c/Juan Carlos I, 1-3 E', 'Haro', 'Spain', 800, 'grass', 'https://media.api-sports.io/football/venues/6945.png'), 
      (6946, 'Estadio El Rollo', null, 'Santo Domingo de la Calzada', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6946.png'), 
      (6947, 'Estadio La Salera', null, 'Nájera', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6947.png'), 
      (6948, 'Oion Arena', 'Calle Cmno. Viejo Bidezar, 37', 'Oion', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6948.png'), 
      (6949, 'Polideportivo Municipal Pradejón', null, 'Pradejón', 'Spain', 1700, 'grass', 'https://media.api-sports.io/football/venues/6949.png'), 
      (6950, 'Estadio San Miguel', 'Carretera de Arnedo', 'Rincón de Soto', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6950.png'), 
      (12349, 'Estadio Municipal de Varea', 'Calle Canicalejo, 33', 'Varea', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/12349.png'), 
      (6952, 'Estadio Municipal de Viana', null, 'Viana', 'Spain', 500, 'grass', 'https://media.api-sports.io/football/venues/6952.png'), 
      (6953, 'Estadio La Ribera', 'Calle de la Madre de Dios', 'Logroño', 'Spain', 800, 'artificial turf', 'https://media.api-sports.io/football/venues/6953.png'), 
      (6954, 'Estadio El Salvador', 'Barrio de Yagüe', 'Logroño', 'Spain', 1161, 'artificial turf', 'https://media.api-sports.io/football/venues/6954.png'), 
      (6955, 'Estadio Virgen de la Corona', 'Camino de los Llanos de la Violada', 'Almudévar', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6955.png'), 
      (6956, 'Estadio Isidro Calderón', null, 'Monzón', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6956.png'), 
      (6957, 'Estadio Municipal de Deportes', null, 'Barbastro', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6957.png'), 
      (6958, 'Campo de Futbol Municipal de Belchite', 'Carretera Cariñena', 'Belchite', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6958.png'), 
      (6959, 'Estadio de Los Olmos', 'Calle Olriols', 'Binéfar', 'Spain', 1250, 'artificial turf', 'https://media.api-sports.io/football/venues/6959.png'), 
      (6960, 'Estadio Manuel Meler', 'Calle Barbalanca, s/n', 'Borja', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6960.png'), 
      (6961, 'Estadio Municipal de Piedrabuena', null, 'Brea de Aragón', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6961.png'), 
      (6962, 'Estadio La Colomina', 'La Colomina', 'Tamarite de Litera', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6962.png'), 
      (6963, 'Campo De Fútbol Jumaya Calamocha', 'Calle Paretera, 12A', 'Calamocha', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/6963.png'), 
      (12352, 'Nuevo Estadio Municipal Cuarte de Huerva', 'Calle Ramiro I', 'Cuarte de Huerva', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12352.png'), 
      (6965, 'Ciudad Deportiva del Real Zaragoza', 'Carretera Valencia', 'Cuarte de Huerva', 'Spain', 2500, 'grass', 'https://media.api-sports.io/football/venues/6965.png'), 
      (6966, 'Estadio San Blas', 'Camino de la Sierra', 'Robres', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6966.png'), 
      (6967, 'Campo Municipal el Gállego', 'Camino de Cogullada, San Juan de Mozarrifar', 'Zaragoza', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6967.png'), 
      (6968, 'Estadio El Carmen', 'Camino de Sasos', 'Sariñena', 'Spain', 4500, 'grass', 'https://media.api-sports.io/football/venues/6968.png'), 
      (6969, 'Estadio Santa Ana', 'Calle de Cuenca', 'Utebo', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/6969.png'), 
      (6970, 'CDM Valdefierro', 'Vía Lactea', 'Zaragoza', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6970.png'), 
      (6971, 'Estadio Nuevo Enrique Porta', 'Calle Riboberta Menchu', 'Villanueva de Gállego', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6971.png'), 
      (6972, 'Estadio Manuel Trujillo', 'Calle Pablo Molina s/n', 'Almagro', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6972.png'), 
      (6973, 'Ciudad Deportiva Andrés Iniesta', 'Prolongación de la Avenida de España, s/n', 'Albacete', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/6973.png'), 
      (6974, 'Polideportivo Municipal Paco Simón', null, 'Almansa', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/6974.png'), 
      (6975, 'Estádio Municipal de Casas Ibañés', null, 'Casas-Ibañés', 'Spain', 1800, 'artificial turf', 'https://media.api-sports.io/football/venues/6975.png'), 
      (6976, 'Estadio San Miguel', 'Carretera Villanueva de la Torre', 'Azuqueca de Henares', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6976.png'), 
      (6977, 'Estadio Ciudad de Puertollano', 'Avenida de Andalucía', 'Puertollano', 'Spain', 7240, 'grass', 'https://media.api-sports.io/football/venues/6977.png'), 
      (6978, 'Estadio Pedro Escartín', 'Calle de Julián Besteiro 14', 'Guadalajara', 'Spain', 7000, 'grass', 'https://media.api-sports.io/football/venues/6978.png'), 
      (6979, 'Estadio Municipal de Illescas', null, 'Illescas', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/6979.png'), 
      (6980, 'Estadio Municipal', null, 'La Roda', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/6980.png'), 
      (6981, 'Estadio La Moheda', 'Av. de la Paz, 9', 'La Solana', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/6981.png'), 
      (6982, 'Campo de Fútbol Nuevo', null, 'Madridejos', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/6982.png'), 
      (6983, 'Polideportivo Juan Carlos I', 'Calle Juan Ramón Jiménez 4', 'Ciudad Real', 'Spain', 2900, 'grass', 'https://media.api-sports.io/football/venues/6983.png'), 
      (10993, 'Estadio San Marcos', null, 'Quintanar del Rey', 'Spain', 2800, 'grass', 'https://media.api-sports.io/football/venues/10993.png'), 
      (6984, 'Polideportivo Estadio Municipal Tarancón', 'Calle Antonio Machado, 42', 'Tarancón', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/6984.png'), 
      (6985, 'Estadio Municipal Salto del Caballo', 'Calle Salto del Caballo', 'Toledo', 'Spain', 5300, 'grass', 'https://media.api-sports.io/football/venues/6985.png'), 
      (6986, 'Estadio San Francisco', null, 'Torrijos', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/6986.png'), 
      (6987, 'Campo De Fútbol Las Pirámides', 'Avenida Estadio', 'Villacañas', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/6987.png'), 
      (7132, 'Estadio Romano', 'Villafranca de los Barros', 'Mérida', 'Spain', 14600, 'grass', 'https://media.api-sports.io/football/venues/7132.png'), 
      (10967, 'Estatio Municipal de Santa Isabel', 'Rúa de Tras Santa Isabel', 'Santiago de Compostela', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/10967.png'), 
      (10968, 'Campo de futbol do Carballo', 'Lugar As Cavadas, 16', 'O Porriño', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/10968.png'), 
      (10969, 'Campo de fútbol Ara Solis', 'Aldea San Martiño de Abaixo, 70', 'Fisterra', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10969.png'), 
      (10970, 'Campo de Futbol de A Senra', 'Calle Valle inclán', 'Ribadumia', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/10970.png'), 
      (10971, 'Estadio Municipal de Cantarrana', 'Av. Vilalba', 'Viveiro', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/10971.png'), 
      (10972, 'Estadio Municipal Carlos Marchena', null, 'Las Cabezas de San Juan', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10972.png'), 
      (10973, 'Estadio Municipal Antonio Almendro', 'Camino del solis s/n, Castilleja de la Cuesta', 'Castilleja de la Cuesta', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10973.png'), 
      (10974, 'Estadio Municipal', 'Calle Bollullos del Condado', 'La Palma del Condado', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/10974.png'), 
      (10975, 'Camp Municipal D''esports Sant Llorenç des Cardassar', null, 'Sant Llorenç des Cardassar', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10975.png'), 
      (10976, 'Camp de Futbol Génova', 'Camí de Gènova a Sant Agustí, 2', 'Palma de Mallorca', 'Spain', 800, null, 'https://media.api-sports.io/football/venues/10976.png'), 
      (10977, 'Campo Municipal Kiko Serra', 'Carrer de l&apos;Arner, Zona Deportiva', 'Sant Josep de sa Talaia, Illes Balears', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/10977.png'), 
      (10979, 'Estadio Nicolás de las Peñas', null, 'Bullas', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/10979.png'), 
      (10980, 'Estadio Municipal', null, 'La Unión', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/10980.png'), 
      (10981, 'Polideportivo Municipal Virgen del Pasico', 'Av. Roldan, s/n', 'Murcia', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10981.png'), 
      (10983, 'Estadio Eras de las Matas', null, 'Cáceres', 'Spain', 700, 'grass', 'https://media.api-sports.io/football/venues/10983.png'), 
      (10985, 'Estadio Municipal Cantolagua', 'Municipal Cantolagua', 'Sangüesa', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/10985.png'), 
      (10986, 'Estadio Andola', 'Camino del Canto del Rio', 'Andosilla', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/10986.png'), 
      (10987, 'Estadio San Roque', null, 'Agoncillo', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/10987.png'), 
      (10988, 'Estadio San Miguel', 'Calle de Ebro', 'Navarrete', 'Spain', 600, 'artificial turf', 'https://media.api-sports.io/football/venues/10988.png'), 
      (10989, 'Campo de Futbol La Platera', 'Camino la Platera', 'Zaragoza', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/10989.png'), 
      (10990, 'Complejo Deportivo San Jorge', 'Calle Ricardo del Arco, 28', 'Huesca', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/10990.png'), 
      (10991, 'Estadio Joaquín Ascaso', 'Paseo de la Corona', 'Sabiñánigo', 'Spain', 3800, 'grass', 'https://media.api-sports.io/football/venues/10991.png'), 
      (10992, 'Estadio La Huerta', 'Calle Alfonso I el Batallador, 17', 'Épila', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/10992.png'), 
      (10994, 'Estadio Municipal de Balazote', 'Calle la Vega, 1T', 'Balazote', 'Spain', 1000, null, 'https://media.api-sports.io/football/venues/10994.png'), 
      (10995, 'Estadio José Camacho', 'Antigua Carretera Madrid', 'Manzanares', 'Spain', 3200, 'artificial turf', 'https://media.api-sports.io/football/venues/10995.png'), 
      (10996, 'Estadio La Solana', null, 'Marchamalo', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/10996.png'), 
      (10997, 'Campo Muro de Zaro', 'Calle Río Arlós', 'Avilés', 'Spain', 5352, 'grass', 'https://media.api-sports.io/football/venues/10997.png'), 
      (10998, 'Estadio De Fútbol Las Tolvas', 'Calle de Tejera Nte., 17', 'Pola de Laviana', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/10998.png'), 
      (10999, 'Estadio Villarea. Valdesoto C.F.', null, 'Asturias', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/10999.png'), 
      (12303, 'Estadio Mioño', 'Avenida de la Estación', 'Castro Urdiales', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12303.png'), 
      (11001, 'Estadio Municipal', 'El Crucero s/n', 'Revilla de Camargo', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11001.png'), 
      (11002, 'Campo Municipal de Polanco', 'Barrio Rinconeda', 'Polanco', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/11002.png'), 
      (11003, 'Estadio Fernando Astobiza', 'Barrio de San Lázaro', 'Sarón, Santa María de Cayón', 'Spain', 2700, 'grass', 'https://media.api-sports.io/football/venues/11003.png'), 
      (11006, 'Campo Txerloia', 'Barrio de Txerloia', 'Azkoitia', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/11006.png'), 
      (11007, 'Campo de fútbol de Zaldupe', null, 'Ondarroa', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/11007.png'), 
      (11008, 'Futbol zelaia Olabide Gasteiz', 'Lasarte errepidea', 'Vitoria-Gasteiz', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11008.png'), 
      (11009, 'Camp de Futbol Torres de Palau', 'Avinguda de Montilivi, 141', 'Girona', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11009.png'), 
      (11010, 'Nou Camp Municipal de Santa Coloma', 'Avinguda de Can Peixauet', 'Santa Coloma de Gramenet', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/11010.png'), 
      (11011, 'Estadio Municipal de Nou Barris', 'Via Júlia 170, Nou Barris, Barrio Prosperitat', 'Barcelona', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/11011.png'), 
      (11012, 'Estadi Municipal del Vilar', 'Carrer Prat de la Riba', 'Valls', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11012.png'), 
      (11013, 'Estadio Angel Pichi Alonso', 'Av. de Méndez Núñez', 'Benicarló', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/11013.png'), 
      (11014, 'Estadio San Gregorio', 'Avenida Pérez Galdós', 'Torrent', 'Spain', 4000, 'artificial turf', 'https://media.api-sports.io/football/venues/11014.png'), 
      (11015, 'Estadio Nou Pla', 'Calle Doctor Fleming 3', 'Villajoyosa / La Vila Joiosa', 'Spain', 2765, 'artificial turf', 'https://media.api-sports.io/football/venues/11015.png'), 
      (11017, 'Campo de Fútbol Recinto Ferial', 'Paseo de Aguadores, 7', 'Alcalá de Henares', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11017.png'), 
      (11018, 'Estadio El Deleite', null, 'Aranjuez', 'Spain', 7000, 'grass', 'https://media.api-sports.io/football/venues/11018.png'), 
      (12496, 'Campo Municipal Juan Manuel Angelina', 'Avenida de los Estudiantes, S/N', 'Villanueva del Pardillo', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12496.png'), 
      (11020, 'Campo de fútbol de Sancti Spiritu A', 'Calle Radio Nacional de España', 'Ávila', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/11020.png'), 
      (11021, 'Estadio El Mancho', 'Calle Villacastín', 'Cebreros', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/11021.png'), 
      (11022, 'Campo Futbol Peñaranda de Bracamonte', 'Av. de Salamanca, 16D', 'Peñaranda de Bracamonte', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/11022.png'), 
      (11023, 'Estadio Municipal Miguel Fijones', 'Carretera de Cartama', 'Alhaurín el Grande', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/11023.png'), 
      (11024, 'Estadio Municipal Francisco Muñoz Pérez', 'Avenida Juan Carlos I', 'Estepona', 'Spain', 7300, 'artificial turf', 'https://media.api-sports.io/football/venues/11024.png'), 
      (11025, 'Campo Municipal El Pozuelo', null, 'Torremolinos', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/11025.png'), 
      (11046, 'Complejo Antonio Afonso Moreno (Tonono)', 'Lugar Barreto 20A', 'Arucas', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/11046.png'), 
      (11047, 'Estadio Munincipal', null, 'Tenerife', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/11047.png'), 
      (11048, 'Estadio Octavio Estevez de Guia de Gran Canaria', null, 'Las Palmas', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/11048.png'), 
      (11067, 'Beltrán Baguena', null, 'Buñol', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/11067.png'), 
      (11068, 'Estadio Francisco Romero', null, 'Málaga', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/11068.png'), 
      (12328, 'Estadio Municipal San Sebastián', 'Avenida del Aljarafe', 'Tomares', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/12328.png'), 
      (12294, 'Estadio Basarte', 'Calle Abiaga 1', 'Amurrio', 'Spain', 3500, 'grass', 'https://media.api-sports.io/football/venues/12294.png'), 
      (12521, 'Estadio Juan Antonio Endeiza', null, 'Teruel', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/12521.png'), 
      (12522, 'Estadio Municipal', 'Avenida Diputación 67', 'Atarfe', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12522.png'), 
      (12358, 'Estadio Municipal Pedro Manuel Barrero Macias', 'C. Naranjos, 19', 'Don Álvaro', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12358.png'), 
      (12318, 'Estadio Galapagar', 'C. Guadarrama, 129, Galapagar', 'Madrid', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12318.png'), 
      (12310, 'Centre Esportiu de La Guineueta', 'Carrer del Castor', 'Barcelona', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12310.png'), 
      (12357, 'Estadio Municipal Miguelturra', 'P.º de Castilla la Mancha', 'Miguelturra', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/12357.png'), 
      (12332, 'Camp de Fútbol de Muro', 'Carrer Poliesportiu, 0', 'Muro', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12332.png'), 
      (12298, 'Campo Futbol San Lazaro Noia', 'Rúa Bolivia', 'Noia', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12298.png'), 
      (12304, 'Campo La Caseta', 'Avenida del Brusco', 'Noja', 'Spain', 3000, 'grass', 'https://media.api-sports.io/football/venues/12304.png'), 
      (12326, 'Estadio Juan Manuel Azuaga', 'Av. Juan Carlos I', 'Torre del Mar', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/12326.png'), 
      (12315, 'Polideportivo Isabel Fernández', null, 'Torrellano', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/12315.png'), 
      (12319, 'Campo Municipal de Fútbol Foresta A', 'Av de la Vega, Sector Foresta', 'Tres Cantos', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/12319.png'), 
      (12327, 'Estadio Municipal', 'Polideportivo Guadaiza', 'San Pedro de Alcántara', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/12327.png'), 
      (12320, 'Estadio Nuevo Municipal Villaviciosa de Odón', 'Calle Alexander Graham Bell', 'Villaviciosa de Odón', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12320.png'), 
      (12299, 'Estadio Municipal de Pardellas', 'Calle Freixa', 'Ponteareas', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12299.png'), 
      (12300, 'Campo del Sofan', 'AC-413, 10', 'La Coruña', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12300.png'), 
      (12301, 'Estadio La Veigona', 'Avenida de la Argentina', 'Luarca', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/12301.png'), 
      (12302, 'Campo de Fútbol Covadonga', 'Calle Sor Juana Inés de la Cruz, 5', 'Gijón', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12302.png'), 
      (12305, 'Campos del Carmen', 'Calle Ría del Asón', 'Colindres', 'Spain', 2500, 'artificial turf', 'https://media.api-sports.io/football/venues/12305.png'), 
      (12307, 'Campo de fútbol de Mastegi', 'C. Koskontako Bidea, 15', 'Lesaka', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12307.png'), 
      (12308, 'Estadio Errebale', 'Errebale', 'Larrabetzu', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12308.png'), 
      (12311, 'Estadio Municipal d''Ascó', 'Carrer Joan XXIII', 'Ascó', 'Spain', 1500, 'grass', 'https://media.api-sports.io/football/venues/12311.png'), 
      (12316, 'Campo de Fútbol El Palmeral', 'C. Zorrilla, 10', 'Callosa de Segura', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12316.png'), 
      (12317, 'Ciudad Deportiva FACSA', 'Cuadra Colomera, 9', 'Castellón de la Plana', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12317.png'), 
      (12321, 'Estadio Román Valero', 'Calle de Andrés Arteaga', 'Madrid', 'Spain', 14000, 'grass', 'https://media.api-sports.io/football/venues/12321.png'), 
      (12322, 'Estadio La Aldehuela', 'Calle de la Fuente', 'Fuenlabrada', 'Spain', 5000, 'grass', 'https://media.api-sports.io/football/venues/12322.png'), 
      (12323, 'Estadio Polideportivo la Dehesa', 'Cobeña', 'Madrid', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12323.png'), 
      (12324, 'Estadio Municipal de Fútbol Francisco Mateos', 'Calle Sta. Clara, 136 Ciudad Rodrigo', 'Salamanca', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12324.png'), 
      (12329, 'Estadio Municipal Luis Rodriguez Salvador', 'Carretera Cartaya-El Rompido, Km. 1', 'Cartaya', 'Spain', 3072, 'grass', 'https://media.api-sports.io/football/venues/12329.png'), 
      (12333, 'Camp Municipal d''Esports de Campos', 'Camí Vell de Ciutat, 0', 'Mallorca', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12333.png'), 
      (12334, 'Estadio Can Canto', 'Carrer des Cubells, 12', 'Ibiza', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12334.png'), 
      (12335, 'Estadio San Martì', null, 'Menorca', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12335.png'), 
      (12336, 'Camp De Futbol Municipal', 'Calle San Saul, El Molinar', 'Palma de Mallorca', 'Spain', 1500, 'artificial turf', 'https://media.api-sports.io/football/venues/12336.png'), 
      (12337, 'Estadio Son Servera', 'Calle Hospital', 'Son Servera, Illes Balears', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12337.png'), 
      (12338, 'Estadio Son Verí', 'Calle de Cala Blava', 'S&apos;Arenal de Llucmajor', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/12338.png'), 
      (12341, 'Estadio Juanito Marrero', 'Las Zocas', 'Tenerife', 'Spain', 3000, 'artificial turf', 'https://media.api-sports.io/football/venues/12341.png'), 
      (12342, 'Estadio Municipal de Yaiza', null, 'Lanzarote', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/12342.png'), 
      (12343, 'Campo Futbol Archena', 'Av. del Río Segura, s/n', 'Archena', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12343.png'), 
      (12344, 'Estadio Playa Sol', null, 'Puerto de Mazarrón', 'Spain', 4500, 'grass', 'https://media.api-sports.io/football/venues/12344.png'), 
      (12345, 'Complejo deportivo Francisco Fernández Torralba', 'C. Juan a Ruiz Piñero, 24', 'Caravaca de la Cruz', 'Spain', 1000, 'artificial turf', 'https://media.api-sports.io/football/venues/12345.png'), 
      (12346, 'Campo Igueldea', 'Calle De Igueldea', 'Arre', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12346.png'), 
      (12347, 'Estadio Las Luchas', 'Calle del Valle de Salazar', 'Navarra', 'Spain', 1800, 'artificial turf', 'https://media.api-sports.io/football/venues/12347.png'), 
      (12348, 'Complejo Polideportivo Municipal Osabidea', 'Paseo Osabidea, 2', 'Puente la Reina', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12348.png'), 
      (12350, 'Estadio de Las Viñas', null, 'Cenicero', 'Spain', 1200, 'grass', 'https://media.api-sports.io/football/venues/12350.png'), 
      (12351, 'Estadio El Rozo', null, 'Murillo de Río Leza', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12351.png'), 
      (12353, 'Campo Municipal De Futbol Fernando Escartin Coti', 'N-260', 'Biescas', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12353.png'), 
      (12354, 'Estadio Los Rosales', 'Calle Autonomia', 'Caspe', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12354.png'), 
      (12355, 'Estadio Municipal de Torrero', null, 'Zaragoza', 'Spain', 500, 'artificial turf', 'https://media.api-sports.io/football/venues/12355.png'), 
      (12356, 'Estadio Fontanazas', 'C. Moncayo', 'Santa Anastasia', 'Spain', 1000, 'grass', 'https://media.api-sports.io/football/venues/12356.png'), 
      (10978, 'Escuela De Fútbol Ciudad Jardín', 'Calle Carmen Conde, 75, Ciudad Jardín', 'Cartagena', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/10978.png'), 
      (12579, 'Estadio San Bartolomé', null, 'Ribaforada', 'Spain', 2000, 'grass', 'https://media.api-sports.io/football/venues/12579.png'), 
      (12580, 'Campo de Fútbol Municipal', 'Callejón De Ginés', 'Espiel', 'Spain', 5000, 'artificial turf', 'https://media.api-sports.io/football/venues/12580.png'), 
      (12581, 'Estadio Zubipe', 'La Florida Poligonoa', 'Guipúzcoa', 'Spain', 6820, 'artificial turf', 'https://media.api-sports.io/football/venues/12581.png'), 
      (12582, 'Estadio Francisco Peraza', 'Calle Fuente Cañizares', 'Tenerife', 'Spain', 8000, 'grass', 'https://media.api-sports.io/football/venues/12582.png'), 
      (12583, 'Estadio Municipal de Fumea', 'Barrio de Fumea', 'Olloniego', 'Spain', 300, null, 'https://media.api-sports.io/football/venues/12583.png'), 
      (12584, 'Campo De Futbol San Agustin De Guadalix', 'Calle Félix Cimas Prados, 1', 'San Agustín del Guadalix', 'Spain', 2000, 'artificial turf', 'https://media.api-sports.io/football/venues/12584.png'), 
      (12636, 'Estadio Municipal Joan Baptista Milà', 'Ronda Sant Ramon 159', 'Sant Boi de Llobregat', 'Spain', 5206, 'artificial turf', 'https://media.api-sports.io/football/venues/12636.png');